-- =============================================================================
-- Stage 05 settlement candidates (ENTITY_FAMILIES=settlements).
-- Independent of places extraction. Original OSM names only. No OSM footprint.
--
-- Also:
--   - deterministic OSM node/polygon dedup (no name-only merges)
--   - read-only township assignment from prod_mirror polygons
-- =============================================================================

\ir pipeline_prod_admin_assign.sql

DO $stage05_settlement_extraction$
DECLARE
    v_raw_schema text;
    v_staging_schema text;
    v_source_snapshot_id bigint;
    v_snapshot_version text;
    v_region_code text;
    v_prod_schema text := 'prod_mirror';
    v_has_prod boolean;
    v_available bigint;
    v_inserted bigint;
    v_merged bigint;
    v_review bigint;
    v_assigned bigint;
    v_unassigned bigint;
    v_multiple bigint;
    v_unavailable bigint;
    v_township_cte text;
    q text;
BEGIN
    SELECT p.raw_schema, p.staging_schema
    INTO v_raw_schema, v_staging_schema
    FROM stage05_params AS p;

    SELECT c.source_snapshot_id, c.snapshot_version, c.region_code
    INTO v_source_snapshot_id, v_snapshot_version, v_region_code
    FROM stage05_context AS c;

    IF NOT pg_temp.pipeline_stage05_extraction_enabled('settlement') THEN
        INSERT INTO stage05_report VALUES (
            'point_extraction', 'settlement',
            format('%s.staging_settlement_candidates', v_staging_schema),
            'inserted_rows', 0, 'SKIP', 'ENTITY_FAMILIES filter excludes settlements.'
        );
        RETURN;
    END IF;

    v_has_prod := to_regclass(format('%I.core_admin_areas', v_prod_schema)) IS NOT NULL
              AND to_regclass(format('%I.ref_admin_levels', v_prod_schema)) IS NOT NULL;

    EXECUTE format(
        $ddl$
        CREATE TABLE IF NOT EXISTS %1$I.staging_settlement_candidates (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_snapshot_id bigint NOT NULL,
            raw_id bigint NULL,
            source_entity_type text NOT NULL,
            external_id text NOT NULL,
            canonical_name text NULL,
            class_code text NOT NULL,
            source_place_type text NULL,
            name_mm text NULL,
            name_en text NULL,
            population integer NULL,
            point_geom geometry(Point, 4326) NULL,
            confidence_score numeric(6,2) NOT NULL DEFAULT 65,
            match_status text NOT NULL DEFAULT 'new_candidate',
            auto_action text NULL,
            review_status text NOT NULL DEFAULT 'pending',
            import_class text NULL,
            import_class_reason jsonb NULL,
            source_status text NULL,
            validation_status text NULL,
            validation_notes jsonb NULL,
            normalized_hash text NULL,
            normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
            source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        $ddl$,
        v_staging_schema
    );
    EXECUTE format(
        'CREATE UNIQUE INDEX IF NOT EXISTS staging_settlement_candidates_snap_ext_uidx
         ON %I.staging_settlement_candidates (source_snapshot_id, external_id)',
        v_staging_schema
    );
    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS staging_settlement_candidates_point_geom_gix
         ON %I.staging_settlement_candidates USING GIST (point_geom)
         WHERE point_geom IS NOT NULL',
        v_staging_schema
    );

    q := format(
        $q$
        SELECT count(*)::bigint
        FROM (
            SELECT 1
            FROM %1$I.raw_osm_points AS raw
            WHERE raw.source_snapshot_id = $1
              AND system.pipeline_is_settlement_place(raw.tags->>'place')
            UNION ALL
            SELECT 1
            FROM %1$I.raw_osm_polygons AS raw
            WHERE raw.source_snapshot_id = $1
              AND raw.geom IS NOT NULL
              AND NOT ST_IsEmpty(raw.geom)
              AND system.pipeline_is_settlement_place(raw.tags->>'place')
        ) AS src
        $q$,
        v_raw_schema
    );
    EXECUTE q INTO v_available USING v_source_snapshot_id;

    IF v_has_prod THEN
        v_township_cte := format(
            $t$
            township_ok AS MATERIALIZED (
                SELECT aa.id, aa.geom
                FROM %1$I.core_admin_areas AS aa
                INNER JOIN %1$I.ref_admin_levels AS al
                    ON al.id = aa.admin_level_id
                WHERE aa.deleted_at IS NULL
                  AND aa.geom IS NOT NULL
                  AND NOT ST_IsEmpty(aa.geom)
                  AND ST_IsValid(aa.geom)
                  AND system.pipeline_prod_admin_is_operational_township(aa.id, al.code)
            ),
            township_hits AS (
                SELECT
                    f.external_id,
                    t.id AS township_id
                FROM featured_base AS f
                INNER JOIN township_ok AS t
                    ON f.point_geom IS NOT NULL
                   AND ST_Covers(t.geom, f.point_geom)
            ),
            township_agg AS (
                SELECT
                    external_id,
                    count(*)::integer AS match_count,
                    CASE WHEN count(*) = 1 THEN min(township_id) ELSE NULL END AS township_id
                FROM township_hits
                GROUP BY 1
            ),
            $t$,
            v_prod_schema,
            v_prod_schema
        );
    ELSE
        v_township_cte :=
            $t$
            township_agg AS (
                SELECT
                    NULL::text AS external_id,
                    0::integer AS match_count,
                    NULL::bigint AS township_id
                WHERE false
            ),
            $t$;
    END IF;

    q := format(
        $q$
        WITH src AS MATERIALIZED (
            SELECT
                raw.id AS raw_id,
                'osm_point'::text AS source_entity_type,
                raw.osm_id,
                raw.osm_feature_type,
                coalesce(raw.tags, '{}'::jsonb) AS tags,
                raw.geom::geometry(Point, 4326) AS point_geom,
                NULL::geometry AS area_geom,
                'raw_osm_points'::text AS raw_table
            FROM %1$I.raw_osm_points AS raw
            WHERE raw.source_snapshot_id = $1
              AND system.pipeline_is_settlement_place(raw.tags->>'place')
            UNION ALL
            SELECT
                raw.id,
                'osm_polygon'::text,
                raw.osm_id,
                raw.osm_feature_type,
                coalesce(raw.tags, '{}'::jsonb),
                ST_PointOnSurface(raw.geom)::geometry(Point, 4326),
                raw.geom,
                'raw_osm_polygons'::text
            FROM %1$I.raw_osm_polygons AS raw
            WHERE raw.source_snapshot_id = $1
              AND raw.geom IS NOT NULL
              AND NOT ST_IsEmpty(raw.geom)
              AND system.pipeline_is_settlement_place(raw.tags->>'place')
        ),
        prepared AS MATERIALIZED (
            SELECT
                src.*,
                system.pipeline_osm_external_id(src.osm_feature_type, src.osm_id) AS external_id,
                system.pipeline_canonical_settlement_type(src.tags->>'place') AS class_code,
                system.pipeline_normalize_settlement_place(src.tags->>'place') AS source_place_type,
                system.pipeline_settlement_canonical_name(src.tags) AS canonical_name,
                system.pipeline_settlement_myanmar_name(src.tags) AS name_mm,
                system.pipeline_settlement_english_name(src.tags) AS name_en,
                system.pipeline_parse_osm_population(src.tags->>'population') AS population,
                system.pipeline_settlement_normalized_name(
                    system.pipeline_settlement_canonical_name(src.tags)
                ) AS name_norm,
                system.pipeline_settlement_source_key(src.tags) AS source_key
            FROM src
            WHERE system.pipeline_canonical_settlement_type(src.tags->>'place') IS NOT NULL
        ),
        featured_base AS MATERIALIZED (
            SELECT * FROM prepared
        ),
        %3$s
        featured AS MATERIALIZED (
            SELECT
                p.*,
                coalesce(t.match_count, 0) AS township_match_count,
                t.township_id,
                CASE
                    WHEN NOT %4$L::boolean THEN 'unavailable'
                    WHEN coalesce(t.match_count, 0) = 1 THEN 'assigned'
                    WHEN coalesce(t.match_count, 0) > 1 THEN 'multiple_match'
                    ELSE 'unassigned'
                END AS township_match_status
            FROM featured_base AS p
            LEFT JOIN township_agg AS t ON t.external_id = p.external_id
        ),
        nodes AS (
            SELECT * FROM featured WHERE source_entity_type = 'osm_point'
        ),
        polys AS (
            SELECT * FROM featured WHERE source_entity_type = 'osm_polygon'
        ),
        candidate_pairs AS MATERIALIZED (
            SELECT
                n.external_id AS node_eid,
                p.external_id AS poly_eid,
                n.point_geom AS node_geom,
                p.point_geom AS poly_point,
                p.area_geom,
                n.class_code,
                system.pipeline_settlement_osm_pair_rule(
                    n.source_key,
                    p.source_key,
                    n.name_norm,
                    p.name_norm,
                    n.class_code,
                    p.class_code,
                    (
                        p.area_geom IS NOT NULL
                        AND n.point_geom IS NOT NULL
                        AND ST_IsValid(p.area_geom)
                        AND ST_Covers(p.area_geom, n.point_geom)
                    ),
                    (
                        n.point_geom IS NOT NULL
                        AND p.point_geom IS NOT NULL
                        AND ST_DWithin(
                            n.point_geom::geography,
                            p.point_geom::geography,
                            coalesce(
                                system.pipeline_canonical_settlement_duplicate_threshold_m(n.class_code),
                                80
                            )::double precision
                        )
                    ),
                    n.township_id,
                    p.township_id,
                    n.township_match_status,
                    p.township_match_status
                ) AS pair_rule,
                system.pipeline_settlement_osm_pair_needs_review(
                    n.source_key,
                    p.source_key,
                    n.name_norm,
                    p.name_norm,
                    n.class_code,
                    p.class_code,
                    (
                        p.area_geom IS NOT NULL
                        AND n.point_geom IS NOT NULL
                        AND ST_IsValid(p.area_geom)
                        AND ST_Covers(p.area_geom, n.point_geom)
                    ),
                    (
                        n.point_geom IS NOT NULL
                        AND p.point_geom IS NOT NULL
                        AND ST_DWithin(
                            n.point_geom::geography,
                            p.point_geom::geography,
                            coalesce(
                                system.pipeline_canonical_settlement_duplicate_threshold_m(n.class_code),
                                80
                            )::double precision
                        )
                    ),
                    (
                        n.point_geom IS NOT NULL
                        AND p.point_geom IS NOT NULL
                        AND ST_DWithin(
                            n.point_geom::geography,
                            p.point_geom::geography,
                            (
                                2 * coalesce(
                                    system.pipeline_canonical_settlement_duplicate_threshold_m(n.class_code),
                                    80
                                )
                            )::double precision
                        )
                    ),
                    n.township_id,
                    p.township_id,
                    n.township_match_status,
                    p.township_match_status
                ) AS needs_review
            FROM nodes AS n
            INNER JOIN polys AS p
                ON p.class_code = n.class_code
               AND (
                    (n.source_key IS NOT NULL AND n.source_key = p.source_key)
                    OR (n.name_norm IS NOT NULL AND n.name_norm = p.name_norm)
               )
        ),
        scored AS (
            SELECT * FROM candidate_pairs WHERE pair_rule IS NOT NULL
        ),
        node_n AS (
            SELECT node_eid, count(*)::integer AS n FROM scored GROUP BY 1
        ),
        poly_n AS (
            SELECT poly_eid, count(*)::integer AS n FROM scored GROUP BY 1
        ),
        exclusive AS (
            SELECT s.*
            FROM scored AS s
            INNER JOIN node_n AS nn ON nn.node_eid = s.node_eid AND nn.n = 1
            INNER JOIN poly_n AS pn ON pn.poly_eid = s.poly_eid AND pn.n = 1
        ),
        review_ids AS (
            SELECT node_eid AS external_id
            FROM (
                SELECT node_eid FROM scored
                EXCEPT
                SELECT node_eid FROM exclusive
            ) AS ambiguous_nodes
            UNION
            SELECT poly_eid
            FROM (
                SELECT poly_eid FROM scored
                EXCEPT
                SELECT poly_eid FROM exclusive
            ) AS ambiguous_polys
            UNION
            SELECT node_eid FROM candidate_pairs WHERE needs_review
            UNION
            SELECT poly_eid FROM candidate_pairs WHERE needs_review
        ),
        dropped_nodes AS (
            SELECT node_eid AS external_id FROM exclusive
        ),
        survivors AS (
            SELECT
                f.*,
                e.pair_rule AS dedup_rule,
                e.node_eid AS merged_from_eid,
                CASE
                    WHEN e.poly_eid IS NOT NULL THEN 'merged'
                    WHEN r.external_id IS NOT NULL THEN 'needs_review'
                    ELSE 'unique'
                END AS dedup_status
            FROM featured AS f
            LEFT JOIN exclusive AS e ON e.poly_eid = f.external_id
            LEFT JOIN review_ids AS r ON r.external_id = f.external_id
            WHERE NOT EXISTS (
                SELECT 1 FROM dropped_nodes AS d WHERE d.external_id = f.external_id
            )
        ),
        merged AS (
            SELECT
                s.*,
                n.point_geom AS node_point_geom,
                n.population AS node_population,
                n.name_mm AS node_name_mm,
                n.name_en AS node_name_en,
                n.canonical_name AS node_canonical_name,
                n.raw_id AS node_raw_id,
                n.osm_id AS node_osm_id,
                n.osm_feature_type AS node_osm_feature_type,
                n.external_id AS node_external_id,
                n.tags AS node_tags,
                n.raw_table AS node_raw_table
            FROM survivors AS s
            LEFT JOIN featured AS n ON n.external_id = s.merged_from_eid
        ),
        inserted AS (
            INSERT INTO %2$I.staging_settlement_candidates (
                source_snapshot_id,
                raw_id,
                source_entity_type,
                external_id,
                canonical_name,
                class_code,
                source_place_type,
                name_mm,
                name_en,
                population,
                point_geom,
                confidence_score,
                match_status,
                auto_action,
                review_status,
                normalized_data,
                source_refs
            )
            SELECT
                $1,
                m.raw_id,
                m.source_entity_type,
                m.external_id,
                coalesce(m.canonical_name, m.node_canonical_name),
                m.class_code,
                m.source_place_type,
                coalesce(m.name_mm, m.node_name_mm),
                coalesce(m.name_en, m.node_name_en),
                COALESCE(
                    GREATEST(m.population, m.node_population),
                    m.population,
                    m.node_population
                ),
                coalesce(m.node_point_geom, m.point_geom),
                CASE
                    WHEN coalesce(m.canonical_name, m.node_canonical_name) IS NOT NULL
                         AND coalesce(m.node_point_geom, m.point_geom) IS NOT NULL THEN 70
                    WHEN coalesce(m.node_point_geom, m.point_geom) IS NOT NULL THEN 45
                    ELSE 25
                END,
                'new_candidate',
                NULL,
                CASE WHEN m.dedup_status = 'needs_review' THEN 'needs_review' ELSE 'pending' END,
                system.pipeline_apply_township_containment_normalized_data(
                    jsonb_strip_nulls(jsonb_build_object(
                        'source_place_type', m.source_place_type,
                        'canonical_settlement_type', m.class_code,
                        'name', m.tags->>'name',
                        'name:my', m.tags->>'name:my',
                        'name:mm', m.tags->>'name:mm',
                        'name:en', m.tags->>'name:en',
                        'population', m.tags->>'population',
                        'place', m.tags->>'place',
                        'is_settlement', true,
                        'duplicate_threshold_m', system.pipeline_canonical_settlement_duplicate_threshold_m(m.class_code),
                        'dedup_status', m.dedup_status,
                        'dedup_rule', m.dedup_rule,
                        'merged_from_external_id', m.merged_from_eid,
                        'selected_fields', jsonb_strip_nulls(jsonb_build_object(
                            'place', m.tags->>'place',
                            'population', m.tags->>'population',
                            'name', m.tags->>'name',
                            'name:my', m.tags->>'name:my',
                            'name:mm', m.tags->>'name:mm',
                            'name:en', m.tags->>'name:en',
                            'alt_name', m.tags->>'alt_name',
                            'old_name', m.tags->>'old_name',
                            'official_name', m.tags->>'official_name'
                        ))
                    )),
                    jsonb_build_object(
                        'township_id', to_jsonb(m.township_id),
                        'match_count', m.township_match_count,
                        'status', m.township_match_status
                    )
                ),
                jsonb_strip_nulls(jsonb_build_object(
                    'source_snapshot_id', $1,
                    'snapshot_version', $2,
                    'region_code', $3,
                    'raw_table', m.raw_table,
                    'raw_id', m.raw_id,
                    'osm_id', m.osm_id,
                    'osm_feature_type', m.osm_feature_type,
                    'source_place_type', m.source_place_type,
                    'external_id', m.external_id,
                    'merged_from_external_id', m.node_external_id,
                    'merged_from_osm_id', m.node_osm_id,
                    'merged_from_raw_id', m.node_raw_id,
                    'merged_from_raw_table', m.node_raw_table,
                    'merged_from_osm_feature_type', m.node_osm_feature_type
                ))
            FROM merged AS m
            RETURNING 1
        )
        SELECT count(*)::bigint FROM inserted
        $q$,
        v_raw_schema,
        v_staging_schema,
        v_township_cte,
        v_has_prod
    );

    EXECUTE q INTO v_inserted
    USING v_source_snapshot_id, v_snapshot_version, v_region_code;

    EXECUTE format(
        $m$
        SELECT
            count(*) FILTER (WHERE s.normalized_data->>'dedup_status' = 'merged'),
            count(*) FILTER (WHERE s.normalized_data->>'dedup_status' = 'needs_review'),
            count(*) FILTER (WHERE s.normalized_data->>'township_match_status' = 'assigned'),
            count(*) FILTER (WHERE s.normalized_data->>'township_match_status' = 'unassigned'),
            count(*) FILTER (WHERE s.normalized_data->>'township_match_status' = 'multiple_match'),
            count(*) FILTER (WHERE s.normalized_data->>'township_match_status' = 'unavailable')
        FROM %I.staging_settlement_candidates AS s
        WHERE s.source_snapshot_id = $1
        $m$,
        v_staging_schema
    )
    INTO v_merged, v_review, v_assigned, v_unassigned, v_multiple, v_unavailable
    USING v_source_snapshot_id;

    INSERT INTO stage05_report VALUES (
        'point_extraction',
        'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'inserted_rows',
        coalesce(v_inserted, 0),
        'PASS',
        format(
            'available_rows=%s unnamed_allowed=true footprint_geom=not_populated prod_mirror=%s',
            v_available,
            CASE WHEN v_has_prod THEN 'present' ELSE 'missing' END
        )
    );
    INSERT INTO stage05_report VALUES (
        'settlement_dedup', 'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'merged_pairs', coalesce(v_merged, 0), 'PASS',
        'OSM node dropped when 1:1 pair with polygon'
    );
    INSERT INTO stage05_report VALUES (
        'settlement_dedup', 'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'needs_review', coalesce(v_review, 0), 'PASS',
        'ambiguous pairs kept as separate candidates'
    );
    INSERT INTO stage05_report VALUES (
        'settlement_township', 'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'township_assigned', coalesce(v_assigned, 0), 'PASS',
        'exact-one ST_Covers against prod_mirror townships'
    );
    INSERT INTO stage05_report VALUES (
        'settlement_township', 'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'township_unassigned', coalesce(v_unassigned, 0),
        CASE WHEN coalesce(v_unassigned, 0) = 0 THEN 'PASS' ELSE 'WARN' END,
        'no operational township covers the point'
    );
    INSERT INTO stage05_report VALUES (
        'settlement_township', 'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'township_multiple_match', coalesce(v_multiple, 0),
        CASE WHEN coalesce(v_multiple, 0) = 0 THEN 'PASS' ELSE 'WARN' END,
        'two or more operational townships cover the point'
    );
    INSERT INTO stage05_report VALUES (
        'settlement_township', 'settlement',
        format('%s.staging_settlement_candidates', v_staging_schema),
        'township_unavailable', coalesce(v_unavailable, 0),
        CASE WHEN coalesce(v_unavailable, 0) = 0 THEN 'PASS' ELSE 'WARN' END,
        'prod_mirror township tables were not available'
    );
END
$stage05_settlement_extraction$;
