/**
 * Explicit public-map overlay stack above the basemap.
 *
 * Target order (bottom → top), aligned with product policy:
 * 1. Basemap polygons / land / water (style JSON — not listed here)
 * 2. Roads (PMTiles — not listed here)
 * 3. Road / admin labels (PMTiles + optional Yangon GeoJSON overlay)
 * 4. Transport route / infrastructure lines (+ active directions route lines)
 * 5. Normal bus stop points
 * 6. Station / terminal points (+ transport name labels)
 * 7. Normal POI points (+ POI labels)
 * 8. Search highlight overlays (area/route shapes under selected markers)
 * 9. Selected transport marker (hover halo + selected halo + pin)
 * 10. Selected POI marker (halo + pin)
 * 11. Clicked-location detail anchor
 *
 * `applyMapOverlayStackOrder` walks {@link PUBLIC_MAP_OVERLAY_STACK_BOTTOM_TO_TOP}
 * then lifts the user-location dot above everything.
 */
import {
  ROUTE_ACTIVE_CASING_LAYER_ID,
  ROUTE_ACTIVE_LINE_LAYER_ID,
  ROUTE_CONNECTOR_FROM_LAYER_ID,
  ROUTE_CONNECTOR_TO_LAYER_ID,
  ROUTE_END_HALO_LAYER_ID,
  ROUTE_END_POINT_LAYER_ID,
  ROUTE_START_HALO_LAYER_ID,
  ROUTE_START_POINT_LAYER_ID,
} from './directionsRouteOnMap';
import { CLICKED_LOCATION_LAYER_IDS } from './clickedLocationOnMap';
import {
  PLACES_IMPORTANT_LABEL_LAYER_ID,
  PLACES_IMPORTANT_LAYER_ID,
  PLACES_LABEL_LAYER_ID,
  PLACES_LAYER_ID,
  PLACES_SELECTED_HALO_LAYER_ID,
  PLACES_SELECTED_LABEL_LAYER_ID,
  PLACES_SELECTED_LAYER_ID,
  TRANSPORT_FERRY_LANDINGS_LAYER_ID,
  TRANSPORT_FERRY_LANDING_LABELS_LAYER_ID,
  TRANSPORT_FERRY_LANDINGS_HITBOX_LAYER_ID,
  TRANSPORT_HOVER_HALO_LAYER_ID,
  TRANSPORT_INFRASTRUCTURE_LINES_LAYER_ID,
  TRANSPORT_MAJOR_STOP_LABELS_LAYER_ID,
  TRANSPORT_MAJOR_TERMINALS_LAYER_ID,
  TRANSPORT_MAJOR_TERMINALS_HITBOX_LAYER_ID,
  TRANSPORT_MAJOR_TERMINAL_LABELS_LAYER_ID,
  TRANSPORT_ROUTE_LABELS_LAYER_ID,
  TRANSPORT_ROUTE_PATHS_LAYER_ID,
  TRANSPORT_SELECTED_CIRCLE_LAYER_ID,
  TRANSPORT_SELECTED_HALO_LAYER_ID,
  TRANSPORT_SELECTED_LABEL_LAYER_ID,
  TRANSPORT_SELECTED_PIN_LAYER_ID,
  TRANSPORT_STOP_LABELS_LAYER_ID,
  TRANSPORT_STOPS_LAYER_ID,
  TRANSPORT_STOPS_HITBOX_LAYER_ID,
} from './publicMapMarkerLayerIds';
import { PUBLIC_MAP_GEO_LABEL_LAYER_IDS } from './publicMapGeoLayers';
import { YANGON_ROAD_LABEL_OVERLAY_LAYER_IDS } from './roadLabelTextFields';
import { SEARCH_HIGHLIGHT_LAYER_IDS } from './searchHighlightOnMap';

/** Road-label overlays that should stay under transport route lines. */
const ROAD_LABEL_OVERLAY_STACK_BOTTOM_TO_TOP = [
  ...YANGON_ROAD_LABEL_OVERLAY_LAYER_IDS,
] as const;

/** Active directions route lines — above transport paths, below bus stops. */
const ACTIVE_DIRECTIONS_ROUTE_LINE_STACK_BOTTOM_TO_TOP = [
  ROUTE_CONNECTOR_FROM_LAYER_ID,
  ROUTE_CONNECTOR_TO_LAYER_ID,
  ROUTE_ACTIVE_CASING_LAYER_ID,
  ROUTE_ACTIVE_LINE_LAYER_ID,
] as const;

/** Directions start/end markers — above normal POIs, below selected POI pin. */
const ACTIVE_DIRECTIONS_ROUTE_ENDPOINT_STACK_BOTTOM_TO_TOP = [
  ROUTE_START_HALO_LAYER_ID,
  ROUTE_END_HALO_LAYER_ID,
  ROUTE_START_POINT_LAYER_ID,
  ROUTE_END_POINT_LAYER_ID,
] as const;

/**
 * Transport overlay internal order (lines → bus stops → stations → labels).
 * Selected transport markers are stacked separately after normal POIs.
 */
export const TRANSPORT_OVERLAY_STACK_BOTTOM_TO_TOP = [
  TRANSPORT_INFRASTRUCTURE_LINES_LAYER_ID,
  TRANSPORT_ROUTE_PATHS_LAYER_ID,
  TRANSPORT_ROUTE_LABELS_LAYER_ID,
  TRANSPORT_STOPS_LAYER_ID,
  TRANSPORT_FERRY_LANDINGS_LAYER_ID,
  TRANSPORT_MAJOR_TERMINALS_LAYER_ID,
  TRANSPORT_MAJOR_TERMINAL_LABELS_LAYER_ID,
  TRANSPORT_FERRY_LANDING_LABELS_LAYER_ID,
  TRANSPORT_MAJOR_STOP_LABELS_LAYER_ID,
  TRANSPORT_STOP_LABELS_LAYER_ID,
  TRANSPORT_STOPS_HITBOX_LAYER_ID,
  TRANSPORT_FERRY_LANDINGS_HITBOX_LAYER_ID,
  TRANSPORT_MAJOR_TERMINALS_HITBOX_LAYER_ID,
] as const;

/** Hover + selected transport stop pin (above normal POI circles). */
export const TRANSPORT_SELECTED_MARKER_STACK_BOTTOM_TO_TOP = [
  TRANSPORT_HOVER_HALO_LAYER_ID,
  TRANSPORT_SELECTED_HALO_LAYER_ID,
  TRANSPORT_SELECTED_CIRCLE_LAYER_ID,
  TRANSPORT_SELECTED_PIN_LAYER_ID,
  TRANSPORT_SELECTED_LABEL_LAYER_ID,
] as const;

/** Normal POI circles and labels (above transport normal points). */
export const POI_NORMAL_OVERLAY_STACK_BOTTOM_TO_TOP = [
  PLACES_IMPORTANT_LAYER_ID,
  PLACES_LAYER_ID,
  PLACES_IMPORTANT_LABEL_LAYER_ID,
  PLACES_LABEL_LAYER_ID,
] as const;

/** Selected POI halo + pin + caption (top of product markers). */
export const POI_SELECTED_OVERLAY_STACK_BOTTOM_TO_TOP = [
  PLACES_SELECTED_HALO_LAYER_ID,
  PLACES_SELECTED_LAYER_ID,
  PLACES_SELECTED_LABEL_LAYER_ID,
] as const;

/** @deprecated Use {@link POI_NORMAL_OVERLAY_STACK_BOTTOM_TO_TOP}. */
export const POI_OVERLAY_STACK_BOTTOM_TO_TOP = [
  ...POI_NORMAL_OVERLAY_STACK_BOTTOM_TO_TOP,
  ...POI_SELECTED_OVERLAY_STACK_BOTTOM_TO_TOP,
] as const;

/**
 * Full public-map overlay stack applied by `applyMapOverlayStackOrder`.
 * Basemap layers below this list are left untouched.
 */
export const PUBLIC_MAP_OVERLAY_STACK_BOTTOM_TO_TOP = [
  ...ROAD_LABEL_OVERLAY_STACK_BOTTOM_TO_TOP,
  TRANSPORT_INFRASTRUCTURE_LINES_LAYER_ID,
  TRANSPORT_ROUTE_PATHS_LAYER_ID,
  ...ACTIVE_DIRECTIONS_ROUTE_LINE_STACK_BOTTOM_TO_TOP,
  TRANSPORT_ROUTE_LABELS_LAYER_ID,
  TRANSPORT_STOPS_LAYER_ID,
  TRANSPORT_FERRY_LANDINGS_LAYER_ID,
  TRANSPORT_MAJOR_TERMINALS_LAYER_ID,
  TRANSPORT_MAJOR_TERMINAL_LABELS_LAYER_ID,
  TRANSPORT_FERRY_LANDING_LABELS_LAYER_ID,
  TRANSPORT_MAJOR_STOP_LABELS_LAYER_ID,
  TRANSPORT_STOP_LABELS_LAYER_ID,
  TRANSPORT_STOPS_HITBOX_LAYER_ID,
  TRANSPORT_FERRY_LANDINGS_HITBOX_LAYER_ID,
  TRANSPORT_MAJOR_TERMINALS_HITBOX_LAYER_ID,
  ...PUBLIC_MAP_GEO_LABEL_LAYER_IDS,
  ...POI_NORMAL_OVERLAY_STACK_BOTTOM_TO_TOP,
  ...SEARCH_HIGHLIGHT_LAYER_IDS,
  ...ACTIVE_DIRECTIONS_ROUTE_ENDPOINT_STACK_BOTTOM_TO_TOP,
  ...TRANSPORT_SELECTED_MARKER_STACK_BOTTOM_TO_TOP,
  ...POI_SELECTED_OVERLAY_STACK_BOTTOM_TO_TOP,
  ...CLICKED_LOCATION_LAYER_IDS,
] as const;
