listen_addresses: "0.0.0.0:3000"

postgres:
  connection_string: ${DATABASE_URL:?Set DATABASE_URL}

  auto_publish:
    from_schemas:
      - tiles

  tables:
    transport_stops_v:
      schema: tiles
      table: transport_stops_v
      srid: 4326
      geometry_column: geom
      id_column: id

    transport_terminals_v:
      schema: tiles
      table: transport_terminals_v
      srid: 4326
      geometry_column: geom
      id_column: id

    transport_route_paths_v:
      schema: tiles
      table: transport_route_paths_v
      srid: 4326
      geometry_column: geom
      id_column: id

    transport_infrastructure_lines_v:
      schema: tiles
      table: transport_infrastructure_lines_v
      srid: 4326
      geometry_column: geom
      id_column: id