-- Routing-ready street hierarchy: dimensional ref.ref_road_classes + core.core_streets attributes.
-- Idempotent: preserves existing data; additive DDL + UPSERT seeds + NOT NULL enforced after fill.

begin;

create schema if not exists ref;

-- ---------------------------------------------------------------------------
-- 1. ref.ref_road_classes (verify / extend legacy table — existing PK retained)
-- ---------------------------------------------------------------------------
create table if not exists ref.ref_road_classes (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    constraint ref_road_classes_code_key unique (code),
    constraint ref_road_classes_name_key unique (name)
);

alter table ref.ref_road_classes
    add column if not exists rank int,
    add column if not exists min_zoom numeric,
    add column if not exists default_width numeric,
    add column if not exists is_public boolean default true,
    add column if not exists created_at timestamptz default now();

insert into ref.ref_road_classes (code, name, rank, min_zoom, default_width, is_public)
values
    ('motorway', 'Motorway', 10, 5, 22, true),
    ('trunk', 'Trunk', 20, 6, 14, true),
    ('primary', 'Primary', 30, 8, 10, true),
    ('secondary', 'Secondary', 40, 10, 9, true),
    ('tertiary', 'Tertiary', 50, 11, 8, true),
    ('residential', 'Residential', 55, 12, 8, true),
    ('service', 'Service', 60, 13, 6, true),
    ('track', 'Track', 65, 14, 5, true),
    ('path', 'Path', 70, 15, 3, true),
    ('pedestrian', 'Pedestrian', 75, 15, 4, true),
    ('unknown', 'Unknown', 100, 12, 8, true)
on conflict (code) do update
set
    name = excluded.name,
    rank = excluded.rank,
    min_zoom = excluded.min_zoom,
    default_width = excluded.default_width,
    is_public = excluded.is_public;

update ref.ref_road_classes
set
    rank = coalesce(rank, 100),
    min_zoom = coalesce(min_zoom, 22::numeric),
    default_width = coalesce(default_width, 8::numeric),
    is_public = coalesce(is_public, true),
    created_at = coalesce(created_at, now());

alter table ref.ref_road_classes
    alter column rank set not null,
    alter column min_zoom set not null,
    alter column default_width set not null,
    alter column is_public set not null,
    alter column created_at set not null,
    alter column rank set default 100,
    alter column min_zoom set default 22,
    alter column default_width set default 8,
    alter column is_public set default true,
    alter column created_at set default now();

comment on table ref.ref_road_classes is
    'Normalized road/network class for styling, tiles, and routing prep (rank, widths, zoom).';

create index if not exists ref_road_classes_rank_idx
    on ref.ref_road_classes (rank);

-- ---------------------------------------------------------------------------
-- 2. core.core_streets — routing / lineage / lifecycle
-- ---------------------------------------------------------------------------
alter table core.core_streets
    add column if not exists road_class_id bigint,
    add column if not exists road_class text,
    add column if not exists surface text,
    add column if not exists is_oneway boolean not null default false,
    add column if not exists bridge boolean not null default false,
    add column if not exists tunnel boolean not null default false,
    add column if not exists layer int not null default 0,
    add column if not exists source_tags jsonb,
    add column if not exists is_verified boolean not null default false,
    add column if not exists manual_override boolean not null default false,
    add column if not exists edit_status text not null default 'published',
    add column if not exists routing_status text not null default 'synced',
    add column if not exists deleted_at timestamptz,
    add column if not exists last_edited_at timestamptz;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'core_streets_road_class_id_fkey'
          and conrelid = 'core.core_streets'::regclass
    ) then
        alter table core.core_streets
            add constraint core_streets_road_class_id_fkey
                foreign key (road_class_id) references ref.ref_road_classes (id);
    end if;
end $$;

comment on column core.core_streets.road_class is
    'Denormalized class code mirror (e.g. OSM highway) alongside road_class_id.';

comment on column core.core_streets.source_tags is 'Ingest/normalized tags (JSON) for lineage and reconciliation.';

-- ---------------------------------------------------------------------------
-- 3. Indexes on core.core_streets (geom GIST + editor / routing filters)
-- ---------------------------------------------------------------------------
create index if not exists core_streets_geom_gix
    on core.core_streets using gist (geom);

create index if not exists core_streets_road_class_id_idx
    on core.core_streets (road_class_id);

create index if not exists core_streets_is_active_idx
    on core.core_streets (is_active);

create index if not exists core_streets_deleted_at_idx
    on core.core_streets (deleted_at);

create index if not exists core_streets_routing_status_idx
    on core.core_streets (routing_status);

create index if not exists core_streets_edit_status_idx
    on core.core_streets (edit_status);

commit;
