-- Minimal system schema for production lineage: sources, imports, snapshots, diffs, review audit.
-- Apply in Supabase SQL Editor. Does not alter core, staging, or raw.

create schema if not exists system;

-- ---------------------------------------------------------------------------
-- system.system_source_registry
-- ---------------------------------------------------------------------------
create table if not exists system.system_source_registry (
    id bigint generated by default as identity,
    source_code text not null,
    source_name text not null,
    source_type_id bigint null,
    source_uri text null,
    is_active boolean not null default true,
    config jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint system_source_registry_pkey primary key (id),
    constraint system_source_registry_source_code_key unique (source_code),
    constraint system_source_registry_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types (id),
    constraint system_source_registry_source_code_chk
        check (btrim(source_code) <> ''),
    constraint system_source_registry_source_name_chk
        check (btrim(source_name) <> '')
);

comment on table system.system_source_registry is
    'Catalog of external data sources (OSM extracts, manual imports, partners) used for lineage and import control.';
comment on column system.system_source_registry.source_code is
    'Stable machine identifier, e.g. osm_myanmar, kyauktan_boundary.';
comment on column system.system_source_registry.config is
    'Source-specific options (paths, filters, API settings) as JSON.';

-- ---------------------------------------------------------------------------
-- system.system_import_batches
-- ---------------------------------------------------------------------------
create table if not exists system.system_import_batches (
    id bigint generated by default as identity,
    source_registry_id bigint not null,
    batch_name text not null,
    trigger_type text not null default 'manual',
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz null,
    note text null,
    constraint system_import_batches_pkey primary key (id),
    constraint system_import_batches_source_registry_id_fkey
        foreign key (source_registry_id) references system.system_source_registry (id),
    constraint system_import_batches_batch_name_chk
        check (btrim(batch_name) <> ''),
    constraint system_import_batches_trigger_type_chk
        check (btrim(trigger_type) <> ''),
    constraint system_import_batches_status_chk
        check (status in ('running', 'completed', 'failed', 'cancelled')),
    constraint system_import_batches_finished_at_chk
        check (finished_at is null or finished_at >= started_at)
);

create index if not exists system_import_batches_source_registry_id_idx
    on system.system_import_batches (source_registry_id);

comment on table system.system_import_batches is
    'One ingestion run for a registered source (manual job, scheduled pull, or pipeline step).';

-- ---------------------------------------------------------------------------
-- system.system_source_snapshots
-- ---------------------------------------------------------------------------
create table if not exists system.system_source_snapshots (
    id bigint generated by default as identity,
    source_registry_id bigint not null,
    import_batch_id bigint null,
    snapshot_ref text not null,
    snapshot_version text not null,
    region_code text null,
    checksum text null,
    captured_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint system_source_snapshots_pkey primary key (id),
    constraint system_source_snapshots_source_registry_id_fkey
        foreign key (source_registry_id) references system.system_source_registry (id),
    constraint system_source_snapshots_import_batch_id_fkey
        foreign key (import_batch_id) references system.system_import_batches (id),
    constraint system_source_snapshots_snapshot_version_key unique (snapshot_version),
    constraint system_source_snapshots_snapshot_ref_chk
        check (btrim(snapshot_ref) <> ''),
    constraint system_source_snapshots_snapshot_version_chk
        check (btrim(snapshot_version) <> '')
);

create index if not exists system_source_snapshots_source_registry_id_idx
    on system.system_source_snapshots (source_registry_id);

create index if not exists system_source_snapshots_snapshot_version_idx
    on system.system_source_snapshots (snapshot_version);

comment on table system.system_source_snapshots is
    'Immutable capture of a dataset version (file hash, region, batch) for diffing and promotion traceability.';
comment on column system.system_source_snapshots.snapshot_ref is
    'Human or pipeline label for this capture within a source.';
comment on column system.system_source_snapshots.snapshot_version is
    'Globally unique version string (e.g. 2026-05-15T12:00:00Z or myanmar-260513).';

-- ---------------------------------------------------------------------------
-- system.system_diff_runs
-- ---------------------------------------------------------------------------
create table if not exists system.system_diff_runs (
    id bigint generated by default as identity,
    previous_snapshot_id bigint null,
    current_snapshot_id bigint not null,
    entity_family text not null,
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz null,
    summary jsonb not null default '{}'::jsonb,
    constraint system_diff_runs_pkey primary key (id),
    constraint system_diff_runs_previous_snapshot_id_fkey
        foreign key (previous_snapshot_id) references system.system_source_snapshots (id),
    constraint system_diff_runs_current_snapshot_id_fkey
        foreign key (current_snapshot_id) references system.system_source_snapshots (id),
    constraint system_diff_runs_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_diff_runs_status_chk
        check (status in ('running', 'completed', 'failed', 'cancelled')),
    constraint system_diff_runs_snapshot_pair_chk
        check (previous_snapshot_id is null or previous_snapshot_id <> current_snapshot_id),
    constraint system_diff_runs_finished_at_chk
        check (finished_at is null or finished_at >= started_at)
);

create index if not exists system_diff_runs_previous_snapshot_id_idx
    on system.system_diff_runs (previous_snapshot_id);

create index if not exists system_diff_runs_current_snapshot_id_idx
    on system.system_diff_runs (current_snapshot_id);

comment on table system.system_diff_runs is
    'Comparison job between two source snapshots for one entity family (places, streets, admin, etc.).';
comment on column system.system_diff_runs.summary is
    'Aggregate counts and metadata produced when the diff completes.';

-- ---------------------------------------------------------------------------
-- system.system_diff_items
-- ---------------------------------------------------------------------------
create table if not exists system.system_diff_items (
    id bigint generated by default as identity,
    diff_run_id bigint not null,
    entity_family text not null,
    diff_type text not null,
    external_id text null,
    local_entity_id bigint null,
    before_data jsonb null,
    after_data jsonb null,
    confidence_score numeric null,
    auto_action text null,
    review_status text not null default 'pending',
    created_at timestamptz not null default now(),
    constraint system_diff_items_pkey primary key (id),
    constraint system_diff_items_diff_run_id_fkey
        foreign key (diff_run_id) references system.system_diff_runs (id) on delete cascade,
    constraint system_diff_items_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_diff_items_diff_type_chk
        check (diff_type in ('new', 'changed', 'deleted_candidate', 'unchanged', 'conflict')),
    constraint system_diff_items_review_status_chk
        check (review_status in ('pending', 'approved', 'rejected', 'ignored', 'auto_applied')),
    constraint system_diff_items_payload_presence_chk
        check (before_data is not null or after_data is not null)
);

create index if not exists system_diff_items_diff_run_id_idx
    on system.system_diff_items (diff_run_id);

create index if not exists system_diff_items_entity_family_diff_type_idx
    on system.system_diff_items (entity_family, diff_type);

create index if not exists system_diff_items_external_id_idx
    on system.system_diff_items (external_id);

comment on table system.system_diff_items is
    'Per-entity diff outcome from a diff run; drives review and optional auto-apply.';
comment on column system.system_diff_items.external_id is
    'Upstream identifier (e.g. OSM id) when the entity is not yet in core.';
comment on column system.system_diff_items.local_entity_id is
    'Core row id when the entity already exists locally.';

-- ---------------------------------------------------------------------------
-- system.system_review_logs
-- ---------------------------------------------------------------------------
create table if not exists system.system_review_logs (
    id bigint generated by default as identity,
    entity_family text not null,
    entity_id bigint null,
    reviewer_user_id bigint null,
    action_type text not null,
    before_snapshot jsonb null,
    after_snapshot jsonb null,
    reason text null,
    created_at timestamptz not null default now(),
    constraint system_review_logs_pkey primary key (id),
    constraint system_review_logs_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_review_logs_action_type_chk
        check (btrim(action_type) <> ''),
    constraint system_review_logs_audit_presence_chk
        check (
            before_snapshot is not null
            or after_snapshot is not null
            or reason is not null
        )
);

create index if not exists system_review_logs_entity_family_entity_id_idx
    on system.system_review_logs (entity_family, entity_id);

comment on table system.system_review_logs is
    'Append-only audit trail of human or automated review actions on entities and diff outcomes.';
comment on column system.system_review_logs.reviewer_user_id is
    'Optional link to app_auth user when dashboard/API records who acted.';
