-- =============================================================================
-- Supabase system tracking upgrade (non-destructive)
-- =============================================================================
--
-- Depends on:
--   infrastructure/database/migrations/supabase/021_system_import_lineage_tracking.sql
--
-- Purpose:
--   Extend the production-safe system schema toward the fuller local workflow:
--   sources, imports, snapshots, diffs, review logs, conflict queue, review tasks,
--   and publish batches/items.
--
-- Safety rules:
--   - Does not DROP, TRUNCATE, rename, or recreate existing system tables.
--   - Does not store raw OSM payloads in Supabase.
--   - Uses CREATE TABLE IF NOT EXISTS, ALTER TABLE ... ADD COLUMN IF NOT EXISTS,
--     CREATE INDEX IF NOT EXISTS, and guarded DO blocks for constraints.
--   - Does not assume Supabase numeric IDs match local numeric IDs.
--   - Stable cross-environment keys are source_code, snapshot_version, region_code,
--     and checksum.
--
-- Naming decision:
--   021_system_import_lineage_tracking.sql uses system.system_source_registry,
--   system.system_import_batches, etc. This migration continues that style and
--   intentionally does not create system.source_registry-style duplicates.
--
-- Suggested preflight checks before applying:
--
-- select table_schema, table_name
-- from information_schema.tables
-- where table_schema = 'system'
-- order by table_name;
--
-- select source_code, count(*)
-- from system.system_source_registry
-- group by source_code
-- having count(*) > 1;
--
-- select snapshot_version, count(*)
-- from system.system_source_snapshots
-- where snapshot_version is not null
-- group by snapshot_version
-- having count(*) > 1;
--
-- =============================================================================

create schema if not exists system;

-- -----------------------------------------------------------------------------
-- Shared six tables: ensure columns exist if 021 was partially applied or edited.
-- -----------------------------------------------------------------------------

create table if not exists system.system_source_registry (
    id bigint generated by default as identity primary key,
    source_code text not null,
    source_name text not null,
    source_type_id bigint null,
    source_uri text null,
    is_active boolean not null default true,
    config jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table system.system_source_registry
    add column if not exists source_code text,
    add column if not exists source_name text,
    add column if not exists source_type_id bigint null,
    add column if not exists source_uri text null,
    add column if not exists is_active boolean not null default true,
    add column if not exists config jsonb not null default '{}'::jsonb,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

create table if not exists system.system_import_batches (
    id bigint generated by default as identity primary key,
    source_registry_id bigint not null,
    batch_name text not null,
    trigger_type text not null default 'manual',
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz null,
    note text null
);

alter table system.system_import_batches
    add column if not exists source_registry_id bigint,
    add column if not exists batch_name text,
    add column if not exists trigger_type text not null default 'manual',
    add column if not exists status text not null default 'running',
    add column if not exists started_at timestamptz not null default now(),
    add column if not exists finished_at timestamptz null,
    add column if not exists note text null;

create table if not exists system.system_source_snapshots (
    id bigint generated by default as identity primary key,
    source_registry_id bigint not null,
    import_batch_id bigint null,
    snapshot_ref text not null,
    snapshot_version text not null,
    region_code text null,
    checksum text null,
    captured_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

alter table system.system_source_snapshots
    add column if not exists source_registry_id bigint,
    add column if not exists import_batch_id bigint null,
    add column if not exists snapshot_ref text,
    add column if not exists snapshot_version text,
    add column if not exists region_code text null,
    add column if not exists checksum text null,
    add column if not exists captured_at timestamptz not null default now(),
    add column if not exists created_at timestamptz not null default now();

create table if not exists system.system_diff_runs (
    id bigint generated by default as identity primary key,
    previous_snapshot_id bigint null,
    current_snapshot_id bigint not null,
    entity_family text not null,
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz null,
    summary jsonb not null default '{}'::jsonb
);

alter table system.system_diff_runs
    add column if not exists previous_snapshot_id bigint null,
    add column if not exists current_snapshot_id bigint,
    add column if not exists entity_family text,
    add column if not exists status text not null default 'running',
    add column if not exists started_at timestamptz not null default now(),
    add column if not exists finished_at timestamptz null,
    add column if not exists summary jsonb not null default '{}'::jsonb;

create table if not exists system.system_diff_items (
    id bigint generated by default as identity primary key,
    diff_run_id bigint not null,
    entity_family text not null,
    diff_type text not null,
    external_id text null,
    local_entity_id bigint null,
    before_data jsonb null,
    after_data jsonb null,
    confidence_score numeric null,
    auto_action text null,
    review_status text not null default 'pending',
    created_at timestamptz not null default now()
);

alter table system.system_diff_items
    add column if not exists diff_run_id bigint,
    add column if not exists entity_family text,
    add column if not exists diff_type text,
    add column if not exists external_id text null,
    add column if not exists local_entity_id bigint null,
    add column if not exists before_data jsonb null,
    add column if not exists after_data jsonb null,
    add column if not exists confidence_score numeric null,
    add column if not exists auto_action text null,
    add column if not exists review_status text not null default 'pending',
    add column if not exists created_at timestamptz not null default now();

create table if not exists system.system_review_logs (
    id bigint generated by default as identity primary key,
    entity_family text not null,
    entity_id bigint null,
    reviewer_user_id bigint null,
    action_type text not null,
    before_snapshot jsonb null,
    after_snapshot jsonb null,
    reason text null,
    created_at timestamptz not null default now()
);

alter table system.system_review_logs
    add column if not exists entity_family text,
    add column if not exists entity_id bigint null,
    add column if not exists reviewer_user_id bigint null,
    add column if not exists action_type text,
    add column if not exists before_snapshot jsonb null,
    add column if not exists after_snapshot jsonb null,
    add column if not exists reason text null,
    add column if not exists created_at timestamptz not null default now();

-- -----------------------------------------------------------------------------
-- Fuller workflow tables from local baseline (production-safe metadata only).
-- -----------------------------------------------------------------------------

create table if not exists system.system_conflict_queue (
    id bigint generated by default as identity primary key,
    diff_item_id bigint not null,
    conflict_type text not null,
    resolution_status text not null,
    assigned_to bigint null,
    resolution_note text null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz null
);

alter table system.system_conflict_queue
    add column if not exists diff_item_id bigint,
    add column if not exists conflict_type text,
    add column if not exists resolution_status text,
    add column if not exists assigned_to bigint null,
    add column if not exists resolution_note text null,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists resolved_at timestamptz null;

create table if not exists system.system_review_tasks (
    id bigint generated by default as identity primary key,
    task_type_id bigint not null,
    status_id bigint not null,
    entity_family text not null,
    entity_id bigint not null,
    assigned_to bigint null,
    priority integer not null default 0,
    note text null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz null
);

alter table system.system_review_tasks
    add column if not exists task_type_id bigint,
    add column if not exists status_id bigint,
    add column if not exists entity_family text,
    add column if not exists entity_id bigint,
    add column if not exists assigned_to bigint null,
    add column if not exists priority integer not null default 0,
    add column if not exists note text null,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists resolved_at timestamptz null;

create table if not exists system.system_publish_batches (
    id bigint generated by default as identity primary key,
    batch_name text not null,
    created_by bigint null,
    approved_by bigint null,
    status text not null default 'draft',
    created_at timestamptz not null default now(),
    published_at timestamptz null,
    note text null
);

alter table system.system_publish_batches
    add column if not exists batch_name text,
    add column if not exists created_by bigint null,
    add column if not exists approved_by bigint null,
    add column if not exists status text not null default 'draft',
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists published_at timestamptz null,
    add column if not exists note text null;

create table if not exists system.system_publish_items (
    id bigint generated by default as identity primary key,
    publish_batch_id bigint not null,
    entity_family text not null,
    entity_id bigint not null,
    version_id bigint null,
    publish_action text not null,
    publish_status text not null default 'pending',
    created_at timestamptz not null default now()
);

alter table system.system_publish_items
    add column if not exists publish_batch_id bigint,
    add column if not exists entity_family text,
    add column if not exists entity_id bigint,
    add column if not exists version_id bigint null,
    add column if not exists publish_action text,
    add column if not exists publish_status text not null default 'pending',
    add column if not exists created_at timestamptz not null default now();

-- -----------------------------------------------------------------------------
-- Constraint helpers: add only when absent and existing data is compatible.
-- -----------------------------------------------------------------------------

do $$
begin
    if to_regclass('ref.ref_source_types') is not null
       and not exists (
           select 1 from pg_constraint
           where conname = 'system_source_registry_source_type_id_fkey'
             and conrelid = 'system.system_source_registry'::regclass
       ) then
        alter table system.system_source_registry
            add constraint system_source_registry_source_type_id_fkey
            foreign key (source_type_id) references ref.ref_source_types (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_source_registry_source_code_key'
          and conrelid = 'system.system_source_registry'::regclass
    ) then
        if not exists (
            select 1
            from system.system_source_registry
            group by source_code
            having count(*) > 1
        ) then
            alter table system.system_source_registry
                add constraint system_source_registry_source_code_key unique (source_code);
        else
            raise notice 'Skipped system_source_registry_source_code_key: duplicate source_code values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_source_snapshots_snapshot_version_key'
          and conrelid = 'system.system_source_snapshots'::regclass
    ) then
        if not exists (
            select 1
            from system.system_source_snapshots
            where snapshot_version is not null
            group by snapshot_version
            having count(*) > 1
        ) then
            alter table system.system_source_snapshots
                add constraint system_source_snapshots_snapshot_version_key unique (snapshot_version);
        else
            raise notice 'Skipped system_source_snapshots_snapshot_version_key: duplicate snapshot_version values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_source_snapshots_source_registry_id_snapshot_ref_key'
          and conrelid = 'system.system_source_snapshots'::regclass
    ) then
        if not exists (
            select 1
            from system.system_source_snapshots
            group by source_registry_id, snapshot_ref
            having count(*) > 1
        ) then
            alter table system.system_source_snapshots
                add constraint system_source_snapshots_source_registry_id_snapshot_ref_key
                unique (source_registry_id, snapshot_ref);
        else
            raise notice 'Skipped source_registry_id/snapshot_ref unique: duplicates exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_import_batches_source_registry_id_fkey'
          and conrelid = 'system.system_import_batches'::regclass
    ) then
        alter table system.system_import_batches
            add constraint system_import_batches_source_registry_id_fkey
            foreign key (source_registry_id) references system.system_source_registry (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_source_snapshots_source_registry_id_fkey'
          and conrelid = 'system.system_source_snapshots'::regclass
    ) then
        alter table system.system_source_snapshots
            add constraint system_source_snapshots_source_registry_id_fkey
            foreign key (source_registry_id) references system.system_source_registry (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_source_snapshots_import_batch_id_fkey'
          and conrelid = 'system.system_source_snapshots'::regclass
    ) then
        alter table system.system_source_snapshots
            add constraint system_source_snapshots_import_batch_id_fkey
            foreign key (import_batch_id) references system.system_import_batches (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_runs_previous_snapshot_id_fkey'
          and conrelid = 'system.system_diff_runs'::regclass
    ) then
        alter table system.system_diff_runs
            add constraint system_diff_runs_previous_snapshot_id_fkey
            foreign key (previous_snapshot_id) references system.system_source_snapshots (id);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_runs_current_snapshot_id_fkey'
          and conrelid = 'system.system_diff_runs'::regclass
    ) then
        alter table system.system_diff_runs
            add constraint system_diff_runs_current_snapshot_id_fkey
            foreign key (current_snapshot_id) references system.system_source_snapshots (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_items_diff_run_id_fkey'
          and conrelid = 'system.system_diff_items'::regclass
    ) then
        alter table system.system_diff_items
            add constraint system_diff_items_diff_run_id_fkey
            foreign key (diff_run_id) references system.system_diff_runs (id) on delete cascade;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_conflict_queue_diff_item_id_fkey'
          and conrelid = 'system.system_conflict_queue'::regclass
    ) then
        alter table system.system_conflict_queue
            add constraint system_conflict_queue_diff_item_id_fkey
            foreign key (diff_item_id) references system.system_diff_items (id);
    end if;
end $$;

do $$
begin
    if to_regclass('ref.ref_validation_task_types') is not null
       and not exists (
           select 1 from pg_constraint
           where conname = 'system_review_tasks_task_type_id_fkey'
             and conrelid = 'system.system_review_tasks'::regclass
       ) then
        alter table system.system_review_tasks
            add constraint system_review_tasks_task_type_id_fkey
            foreign key (task_type_id) references ref.ref_validation_task_types (id);
    end if;

    if to_regclass('ref.ref_validation_statuses') is not null
       and not exists (
           select 1 from pg_constraint
           where conname = 'system_review_tasks_status_id_fkey'
             and conrelid = 'system.system_review_tasks'::regclass
       ) then
        alter table system.system_review_tasks
            add constraint system_review_tasks_status_id_fkey
            foreign key (status_id) references ref.ref_validation_statuses (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_publish_items_publish_batch_id_fkey'
          and conrelid = 'system.system_publish_items'::regclass
    ) then
        alter table system.system_publish_items
            add constraint system_publish_items_publish_batch_id_fkey
            foreign key (publish_batch_id) references system.system_publish_batches (id);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_publish_items_publish_batch_id_entity_family_entity_id_p'
          and conrelid = 'system.system_publish_items'::regclass
    ) then
        if not exists (
            select 1
            from system.system_publish_items
            group by publish_batch_id, entity_family, entity_id, publish_action
            having count(*) > 1
        ) then
            alter table system.system_publish_items
                add constraint system_publish_items_publish_batch_id_entity_family_entity_id_p
                unique (publish_batch_id, entity_family, entity_id, publish_action);
        else
            raise notice 'Skipped publish item unique constraint: duplicate publish items exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_items_confidence_score_chk'
          and conrelid = 'system.system_diff_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_items
            where confidence_score is not null
              and (confidence_score < 0 or confidence_score > 1)
        ) then
            alter table system.system_diff_items
                add constraint system_diff_items_confidence_score_chk
                check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1));
        else
            raise notice 'Skipped confidence score check: values outside [0,1] exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_review_tasks_priority_chk'
          and conrelid = 'system.system_review_tasks'::regclass
    ) then
        if not exists (select 1 from system.system_review_tasks where priority < 0) then
            alter table system.system_review_tasks
                add constraint system_review_tasks_priority_chk check (priority >= 0);
        else
            raise notice 'Skipped review task priority check: negative priority values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_import_batches_status_chk'
          and conrelid = 'system.system_import_batches'::regclass
    ) then
        if not exists (
            select 1 from system.system_import_batches
            where status not in ('running', 'completed', 'failed', 'cancelled')
        ) then
            alter table system.system_import_batches
                add constraint system_import_batches_status_chk
                check (status in ('running', 'completed', 'failed', 'cancelled'));
        else
            raise notice 'Skipped import batch status check: unsupported values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_runs_status_chk'
          and conrelid = 'system.system_diff_runs'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_runs
            where status not in ('running', 'completed', 'failed', 'cancelled')
        ) then
            alter table system.system_diff_runs
                add constraint system_diff_runs_status_chk
                check (status in ('running', 'completed', 'failed', 'cancelled'));
        else
            raise notice 'Skipped diff run status check: unsupported values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_items_diff_type_chk'
          and conrelid = 'system.system_diff_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_items
            where diff_type not in ('new', 'changed', 'deleted_candidate', 'unchanged', 'conflict')
        ) then
            alter table system.system_diff_items
                add constraint system_diff_items_diff_type_chk
                check (diff_type in ('new', 'changed', 'deleted_candidate', 'unchanged', 'conflict'));
        else
            raise notice 'Skipped diff type check: unsupported values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_items_review_status_chk'
          and conrelid = 'system.system_diff_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_items
            where review_status not in ('pending', 'approved', 'rejected', 'ignored', 'auto_applied')
        ) then
            alter table system.system_diff_items
                add constraint system_diff_items_review_status_chk
                check (review_status in ('pending', 'approved', 'rejected', 'ignored', 'auto_applied'));
        else
            raise notice 'Skipped diff item review status check: unsupported values exist.';
        end if;
    end if;
end $$;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

create index if not exists system_source_registry_source_type_id_idx
    on system.system_source_registry (source_type_id);

create index if not exists system_import_batches_source_registry_id_idx
    on system.system_import_batches (source_registry_id);

create index if not exists system_import_batches_status_idx
    on system.system_import_batches (status);

create index if not exists system_source_snapshots_source_registry_id_idx
    on system.system_source_snapshots (source_registry_id);

create index if not exists system_source_snapshots_import_batch_id_idx
    on system.system_source_snapshots (import_batch_id);

create index if not exists system_source_snapshots_snapshot_version_idx
    on system.system_source_snapshots (snapshot_version);

create index if not exists system_source_snapshots_region_code_idx
    on system.system_source_snapshots (region_code);

create index if not exists system_source_snapshots_checksum_idx
    on system.system_source_snapshots (checksum);

create index if not exists system_diff_runs_previous_snapshot_id_idx
    on system.system_diff_runs (previous_snapshot_id);

create index if not exists system_diff_runs_current_snapshot_id_idx
    on system.system_diff_runs (current_snapshot_id);

create index if not exists system_diff_runs_entity_family_idx
    on system.system_diff_runs (entity_family);

create index if not exists system_diff_items_diff_run_id_idx
    on system.system_diff_items (diff_run_id);

create index if not exists system_diff_items_entity_family_diff_type_idx
    on system.system_diff_items (entity_family, diff_type);

create index if not exists system_diff_items_entity_family_external_id_idx
    on system.system_diff_items (entity_family, external_id);

create index if not exists system_diff_items_external_id_idx
    on system.system_diff_items (external_id);

create index if not exists system_diff_items_review_status_idx
    on system.system_diff_items (review_status);

create index if not exists system_review_logs_entity_family_entity_id_idx
    on system.system_review_logs (entity_family, entity_id);

create index if not exists system_conflict_queue_diff_item_id_idx
    on system.system_conflict_queue (diff_item_id);

create index if not exists system_conflict_queue_resolution_status_idx
    on system.system_conflict_queue (resolution_status);

create index if not exists system_review_tasks_task_type_id_idx
    on system.system_review_tasks (task_type_id);

create index if not exists system_review_tasks_status_id_idx
    on system.system_review_tasks (status_id);

create index if not exists system_review_tasks_assigned_to_idx
    on system.system_review_tasks (assigned_to);

create index if not exists system_review_tasks_entity_family_entity_id_idx
    on system.system_review_tasks (entity_family, entity_id);

create index if not exists system_publish_batches_status_idx
    on system.system_publish_batches (status);

create index if not exists system_publish_items_entity_family_entity_id_idx
    on system.system_publish_items (entity_family, entity_id);

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------

comment on schema system is
    'Production metadata for data lineage, imports, snapshots, diffs, review audit, and release tracking.';

comment on table system.system_source_registry is
    'Data source catalog: stable registry for OSM extracts, manual dashboard edits, GTFS, government, and partner sources.';
comment on column system.system_source_registry.source_code is
    'Stable source key used across local and Supabase; do not rely on matching numeric ids.';

comment on table system.system_import_batches is
    'Import job tracking: one execution of an import or ingestion process for a registered source.';
comment on table system.system_source_snapshots is
    'Exact source version tracking: captured source dataset versions keyed by snapshot_version, region_code, and checksum.';
comment on column system.system_source_snapshots.snapshot_version is
    'Stable source version key for cross-environment lineage and diffing.';
comment on column system.system_source_snapshots.region_code is
    'Stable region/scope code for the captured snapshot.';
comment on column system.system_source_snapshots.checksum is
    'Checksum for verifying the exact captured source payload.';

comment on table system.system_diff_runs is
    'Snapshot comparison runs: tracks comparisons between previous and current source snapshots.';
comment on table system.system_diff_items is
    'Individual changes detected by a diff run; stores before/after JSON for review and optional application.';
comment on table system.system_review_logs is
    'Human audit logs for review, approval, rejection, promotion, and other workflow actions.';
comment on table system.system_conflict_queue is
    'Conflict queue for diff items that need manual or automated resolution before publishing.';
comment on table system.system_review_tasks is
    'Review task queue for validation work against entities or diff results.';
comment on table system.system_publish_batches is
    'Approved production release tracking: groups changes intended for publication.';
comment on table system.system_publish_items is
    'Per-entity publish decisions inside a publish batch.';

-- -----------------------------------------------------------------------------
-- Verification queries (optional; run after applying)
-- -----------------------------------------------------------------------------
--
-- select table_schema, table_name
-- from information_schema.tables
-- where table_schema = 'system'
-- order by table_name;
--
-- select conrelid::regclass as table_name, conname, contype
-- from pg_constraint
-- where connamespace = 'system'::regnamespace
-- order by table_name::text, conname;
--
-- select schemaname, tablename, indexname
-- from pg_indexes
-- where schemaname = 'system'
-- order by tablename, indexname;
--
-- select source_code
-- from system.system_source_registry
-- order by source_code;
--
-- select snapshot_version, region_code, checksum
-- from system.system_source_snapshots
-- order by created_at desc;
