-- =============================================================================
-- Supabase production readiness: core/search/routing/address (non-destructive)
-- =============================================================================
--
-- Purpose:
--   Prepare production-safe schemas/tables for future approved data promoted
--   from local review workflows.
--
-- Scope:
--   - Supabase / production schema only.
--   - Does NOT create raw OSM tables.
--   - Does NOT copy local staging tables or import OSM data.
--   - Does NOT change core promotion logic.
--   - Non-destructive only: CREATE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS,
--     CREATE INDEX IF NOT EXISTS.
--
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Part A: schemas
-- -----------------------------------------------------------------------------

create schema if not exists core;
create schema if not exists search;
create schema if not exists routing;
create schema if not exists system;
create schema if not exists ref;

-- -----------------------------------------------------------------------------
-- Part B: production core address tables
-- -----------------------------------------------------------------------------

create table if not exists core.core_addresses (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    full_address text null,
    house_number text null,
    street_name text null,
    quarter text null,
    suburb text null,
    township text null,
    city text null,
    district text null,
    state_region text null,
    postcode text null,
    country text not null default 'MM',
    point_geom geometry(Point, 4326) null,
    geom geometry(Geometry, 4326) null,
    plus_code text null,
    confidence_score numeric,
    is_verified boolean not null default false,
    manual_override boolean not null default false,
    source_type_id bigint null references ref.ref_source_types(id),
    source_refs jsonb not null default '{}'::jsonb,
    normalized_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null
);

alter table if exists core.core_addresses
    add column if not exists public_id uuid not null default gen_random_uuid(),
    add column if not exists street_name text null,
    add column if not exists quarter text null,
    add column if not exists suburb text null,
    add column if not exists township text null,
    add column if not exists city text null,
    add column if not exists district text null,
    add column if not exists state_region text null,
    add column if not exists postcode text null,
    add column if not exists country text not null default 'MM',
    add column if not exists geom geometry(Geometry, 4326) null,
    add column if not exists plus_code text null,
    add column if not exists confidence_score numeric,
    add column if not exists manual_override boolean not null default false,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb,
    add column if not exists deleted_at timestamptz null;

create unique index if not exists core_addresses_public_id_uq
    on core.core_addresses (public_id);

create table if not exists core.core_address_components (
    id bigint generated by default as identity primary key,
    address_id bigint not null references core.core_addresses(id) on delete cascade,
    component_type_id bigint null references ref.ref_address_component_types(id),
    component_type_code text not null,
    component_value text not null,
    language_code text not null default 'und',
    sort_order integer not null default 100,
    created_at timestamptz not null default now()
);

alter table if exists core.core_address_components
    add column if not exists component_type_code text not null default 'unknown',
    add column if not exists language_code text not null default 'und',
    add column if not exists created_at timestamptz not null default now();

create unique index if not exists core_address_components_address_component_uq
    on core.core_address_components (address_id, component_type_code, language_code, component_value);

create table if not exists core.core_place_addresses (
    place_id bigint references core.core_places(id) on delete cascade,
    address_id bigint references core.core_addresses(id) on delete cascade,
    relation_type text not null default 'located_at',
    is_primary boolean not null default false,
    created_at timestamptz not null default now(),
    primary key (place_id, address_id)
);

alter table if exists core.core_place_addresses
    add column if not exists relation_type text not null default 'located_at',
    add column if not exists is_primary boolean not null default false,
    add column if not exists created_at timestamptz not null default now();

-- -----------------------------------------------------------------------------
-- Part C: production search schema
-- -----------------------------------------------------------------------------

create table if not exists search.search_names (
    id bigint generated by default as identity primary key,
    entity_family text not null,
    entity_id bigint not null,
    public_id uuid null,
    name text not null,
    normalized_name text not null,
    language_code text not null default 'und',
    script_code text null,
    name_type text not null default 'official',
    search_weight integer not null default 100,
    tokens jsonb not null default '{}'::jsonb,
    geom geometry(Geometry, 4326) null,
    admin_area_id bigint null,
    source_refs jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create unique index if not exists search_names_entity_name_uq
    on search.search_names (entity_family, entity_id, language_code, name_type, name);

create table if not exists search.search_addresses (
    id bigint generated by default as identity primary key,
    address_id bigint not null references core.core_addresses(id) on delete cascade,
    search_text text not null,
    normalized_search_text text not null,
    language_code text not null default 'und',
    tokens jsonb not null default '{}'::jsonb,
    point_geom geometry(Point, 4326) null,
    updated_at timestamptz not null default now()
);

create unique index if not exists search_addresses_address_text_uq
    on search.search_addresses (address_id, language_code, search_text);

-- -----------------------------------------------------------------------------
-- Part D: production routing schema (derived from approved core streets)
-- -----------------------------------------------------------------------------

create table if not exists routing.road_nodes (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    node_key text unique null,
    geom geometry(Point, 4326) not null,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists road_nodes_public_id_uq
    on routing.road_nodes (public_id);

create table if not exists routing.road_edges (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    street_id bigint null references core.core_streets(id),
    from_node_id bigint not null references routing.road_nodes(id),
    to_node_id bigint not null references routing.road_nodes(id),
    geom geometry(LineString, 4326) not null,
    length_m numeric not null,
    road_class_id bigint null references ref.ref_road_classes(id),
    road_class text null,
    is_oneway boolean not null default false,
    reverse_cost_factor numeric not null default 1,
    maxspeed_kph numeric null,
    surface text null,
    access_tags jsonb not null default '{}'::jsonb,
    routing_tags jsonb not null default '{}'::jsonb,
    is_active boolean not null default true,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists road_edges_public_id_uq
    on routing.road_edges (public_id);

create table if not exists routing.turn_restrictions (
    id bigint generated by default as identity primary key,
    restriction_type text not null,
    from_edge_id bigint null references routing.road_edges(id),
    via_node_id bigint null references routing.road_nodes(id),
    to_edge_id bigint null references routing.road_edges(id),
    source_refs jsonb not null default '{}'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists routing.edge_names (
    edge_id bigint not null references routing.road_edges(id) on delete cascade,
    name text not null,
    language_code text not null default 'und',
    script_code text null,
    name_type text not null default 'official',
    is_primary boolean not null default false,
    primary key (edge_id, language_code, name_type, name)
);

create table if not exists routing.routing_build_metadata (
    id bigint generated by default as identity primary key,
    build_name text not null,
    source_snapshot_id bigint null references system.system_source_snapshots(id),
    status text not null default 'running',
    summary jsonb not null default '{}'::jsonb,
    started_at timestamptz not null default now(),
    finished_at timestamptz null,
    created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Part E: core table upgrades for source lineage
-- -----------------------------------------------------------------------------

alter table if exists core.core_streets
    add column if not exists external_id text null,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb;

alter table if exists core.core_places
    add column if not exists external_id text null,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb;

alter table if exists core.core_map_buildings
    add column if not exists external_id text null,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb;

alter table if exists core.core_admin_areas
    add column if not exists external_id text null,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb;

alter table if exists core.core_bus_stops
    add column if not exists external_id text null,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb;

alter table if exists core.core_bus_routes
    add column if not exists external_id text null,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb;

-- -----------------------------------------------------------------------------
-- Part F: indexes
-- -----------------------------------------------------------------------------

-- Core address/search indexes.
create index if not exists core_addresses_point_geom_gix on core.core_addresses using gist (point_geom);
create index if not exists core_addresses_geom_gix on core.core_addresses using gist (geom);
create index if not exists core_addresses_source_type_id_idx on core.core_addresses (source_type_id);
create index if not exists core_addresses_deleted_at_idx on core.core_addresses (deleted_at);
create index if not exists core_addresses_source_refs_gin_idx on core.core_addresses using gin (source_refs);
create index if not exists core_addresses_normalized_data_gin_idx on core.core_addresses using gin (normalized_data);
create index if not exists core_address_components_address_id_idx on core.core_address_components (address_id);
create index if not exists core_address_components_component_type_id_idx on core.core_address_components (component_type_id);
create index if not exists core_place_addresses_address_id_idx on core.core_place_addresses (address_id);

create index if not exists search_names_lower_normalized_name_idx on search.search_names (lower(normalized_name));
create index if not exists search_names_language_code_idx on search.search_names (language_code);
create index if not exists search_names_entity_family_idx on search.search_names (entity_family);
create index if not exists search_names_geom_gix on search.search_names using gist (geom);
create index if not exists search_names_tokens_gin_idx on search.search_names using gin (tokens);
create index if not exists search_names_source_refs_gin_idx on search.search_names using gin (source_refs);

create index if not exists search_addresses_lower_normalized_search_text_idx on search.search_addresses (lower(normalized_search_text));
create index if not exists search_addresses_language_code_idx on search.search_addresses (language_code);
create index if not exists search_addresses_point_geom_gix on search.search_addresses using gist (point_geom);
create index if not exists search_addresses_tokens_gin_idx on search.search_addresses using gin (tokens);

-- Routing indexes.
create index if not exists road_nodes_geom_gix on routing.road_nodes using gist (geom);
create index if not exists road_nodes_source_refs_gin_idx on routing.road_nodes using gin (source_refs);

create index if not exists road_edges_street_id_idx on routing.road_edges (street_id);
create index if not exists road_edges_from_node_id_idx on routing.road_edges (from_node_id);
create index if not exists road_edges_to_node_id_idx on routing.road_edges (to_node_id);
create index if not exists road_edges_road_class_id_idx on routing.road_edges (road_class_id);
create index if not exists road_edges_is_active_idx on routing.road_edges (is_active);
create index if not exists road_edges_geom_gix on routing.road_edges using gist (geom);
create index if not exists road_edges_access_tags_gin_idx on routing.road_edges using gin (access_tags);
create index if not exists road_edges_routing_tags_gin_idx on routing.road_edges using gin (routing_tags);
create index if not exists road_edges_source_refs_gin_idx on routing.road_edges using gin (source_refs);

create index if not exists turn_restrictions_from_edge_id_idx on routing.turn_restrictions (from_edge_id);
create index if not exists turn_restrictions_via_node_id_idx on routing.turn_restrictions (via_node_id);
create index if not exists turn_restrictions_to_edge_id_idx on routing.turn_restrictions (to_edge_id);
create index if not exists turn_restrictions_is_active_idx on routing.turn_restrictions (is_active);
create index if not exists turn_restrictions_source_refs_gin_idx on routing.turn_restrictions using gin (source_refs);

create index if not exists edge_names_name_idx on routing.edge_names (name);
create index if not exists edge_names_lower_name_idx on routing.edge_names (lower(name));
create index if not exists edge_names_language_code_idx on routing.edge_names (language_code);

create index if not exists routing_build_metadata_source_snapshot_id_idx on routing.routing_build_metadata (source_snapshot_id);
create index if not exists routing_build_metadata_status_idx on routing.routing_build_metadata (status);
create index if not exists routing_build_metadata_created_at_idx on routing.routing_build_metadata (created_at);

-- Geometry indexes on existing core geometry columns (production-safe).
create index if not exists core_streets_geom_gix on core.core_streets using gist (geom);
create index if not exists core_places_point_geom_gix on core.core_places using gist (point_geom);
create index if not exists core_places_entry_geom_gix on core.core_places using gist (entry_geom);
create index if not exists core_places_footprint_geom_gix on core.core_places using gist (footprint_geom);
create index if not exists core_map_buildings_geom_gix on core.core_map_buildings using gist (geom);
create index if not exists core_admin_areas_geom_gix on core.core_admin_areas using gist (geom);
create index if not exists core_bus_stops_geom_gix on core.core_bus_stops using gist (geom);

-- Core source lineage indexes.
create index if not exists core_streets_source_refs_gin_idx on core.core_streets using gin (source_refs);
create index if not exists core_streets_normalized_data_gin_idx on core.core_streets using gin (normalized_data);
create index if not exists core_places_source_refs_gin_idx on core.core_places using gin (source_refs);
create index if not exists core_places_normalized_data_gin_idx on core.core_places using gin (normalized_data);
create index if not exists core_map_buildings_source_refs_gin_idx on core.core_map_buildings using gin (source_refs);
create index if not exists core_map_buildings_normalized_data_gin_idx on core.core_map_buildings using gin (normalized_data);
create index if not exists core_admin_areas_source_refs_gin_idx on core.core_admin_areas using gin (source_refs);
create index if not exists core_admin_areas_normalized_data_gin_idx on core.core_admin_areas using gin (normalized_data);
create index if not exists core_bus_stops_source_refs_gin_idx on core.core_bus_stops using gin (source_refs);
create index if not exists core_bus_stops_normalized_data_gin_idx on core.core_bus_stops using gin (normalized_data);
create index if not exists core_bus_routes_source_refs_gin_idx on core.core_bus_routes using gin (source_refs);
create index if not exists core_bus_routes_normalized_data_gin_idx on core.core_bus_routes using gin (normalized_data);

create index if not exists core_streets_road_class_id_idx on core.core_streets (road_class_id);
create index if not exists core_streets_source_type_id_idx on core.core_streets (source_type_id);
create index if not exists core_places_source_type_id_idx on core.core_places (source_type_id);
create index if not exists core_admin_areas_source_type_id_idx on core.core_admin_areas (source_type_id);
create index if not exists core_bus_stops_source_type_id_idx on core.core_bus_stops (source_type_id);
create index if not exists core_bus_routes_source_type_id_idx on core.core_bus_routes (source_type_id);

-- Partial external_id indexes: use deleted_at condition only where the table has deleted_at.
do $$
declare
    r record;
    v_has_deleted_at boolean;
    v_sql text;
begin
    for r in
        select *
        from (values
            ('core', 'core_streets', 'core_streets_external_id_idx'),
            ('core', 'core_places', 'core_places_external_id_idx'),
            ('core', 'core_map_buildings', 'core_map_buildings_external_id_idx'),
            ('core', 'core_admin_areas', 'core_admin_areas_external_id_idx'),
            ('core', 'core_bus_stops', 'core_bus_stops_external_id_idx'),
            ('core', 'core_bus_routes', 'core_bus_routes_external_id_idx')
        ) as t(schema_name, table_name, index_name)
    loop
        select exists (
            select 1
            from information_schema.columns c
            where c.table_schema = r.schema_name
              and c.table_name = r.table_name
              and c.column_name = 'deleted_at'
        )
        into v_has_deleted_at;

        if to_regclass(format('%I.%I', r.schema_name, r.table_name)) is not null then
            v_sql := format(
                'create index if not exists %I on %I.%I (external_id) where external_id is not null%s',
                r.index_name,
                r.schema_name,
                r.table_name,
                case when v_has_deleted_at then ' and deleted_at is null' else '' end
            );
            execute v_sql;
        end if;
    end loop;
end $$;

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------

comment on schema search is 'Production search indexes derived from approved core data only.';
comment on schema routing is 'Production routing graph derived from approved core streets only.';

comment on table core.core_addresses is 'Production-approved addresses linked to places/buildings/streets; no raw OSM dumps.';
comment on table core.core_address_components is 'Normalized components for production core addresses.';
comment on table core.core_place_addresses is 'Join table linking approved places to approved addresses.';

comment on table search.search_names is 'Production search names derived from approved core entities.';
comment on table search.search_addresses is 'Production address search rows derived from approved core addresses.';

comment on table routing.road_nodes is 'Routing graph nodes derived from approved core street geometry.';
comment on table routing.road_edges is 'Routing graph edges derived from approved core streets.';
comment on table routing.turn_restrictions is 'Production turn restrictions for routing graph.';
comment on table routing.edge_names is 'Names attached to routing edges.';
comment on table routing.routing_build_metadata is 'Audit metadata for production routing graph builds.';

comment on column core.core_addresses.source_refs is 'Production source lineage references. Do not store raw OSM dumps here.';
comment on column search.search_names.tokens is 'Tokenized search payload derived from approved core names.';
comment on column routing.road_edges.source_refs is 'Approved source lineage for routing edge generation.';
comment on column routing.routing_build_metadata.source_snapshot_id is 'Optional approved source snapshot used for routing build lineage.';

-- =============================================================================
-- Validation (run manually after applying in Supabase SQL Editor)
-- =============================================================================
--
-- 1) List new schemas/tables:
-- select table_schema, table_name
-- from information_schema.tables
-- where table_schema in ('search', 'routing')
--    or (table_schema = 'core' and table_name in ('core_addresses', 'core_address_components', 'core_place_addresses'))
-- order by table_schema, table_name;
--
-- 2) Check geometry indexes:
-- select schemaname, tablename, indexname, indexdef
-- from pg_indexes
-- where schemaname in ('core', 'search', 'routing')
--   and indexdef ilike '%gist%'
-- order by schemaname, tablename, indexname;
--
-- 3) Count lineage columns added to target core tables:
-- select table_schema, table_name, count(*) filter (where column_name in ('external_id', 'source_refs', 'normalized_data')) as lineage_columns
-- from information_schema.columns
-- where table_schema = 'core'
--   and table_name in ('core_streets', 'core_places', 'core_map_buildings', 'core_admin_areas', 'core_bus_stops', 'core_bus_routes')
-- group by table_schema, table_name
-- order by table_name;
--
-- 4) Check routing tables exist:
-- select table_name
-- from information_schema.tables
-- where table_schema = 'routing'
-- order by table_name;
--
-- 5) Check search tables exist:
-- select table_name
-- from information_schema.tables
-- where table_schema = 'search'
-- order by table_name;
--
-- 6) Check address tables exist:
-- select table_name
-- from information_schema.tables
-- where table_schema = 'core'
--   and table_name in ('core_addresses', 'core_address_components', 'core_place_addresses')
-- order by table_name;
--
