-- =============================================================================
-- Supabase migration 040: systematic ref.ref_address_component_types
-- =============================================================================
--
-- Purpose:
--   DB-driven address component taxonomy for bilingual address composition.
--   Full address strings (full_address, full_address_en, full_address_my) are
--   generated caches — composers sort components by rank ascending (then code)
--   and join language-specific values (language_code en / my / und).
--
-- Safety:
--   - CREATE / ALTER IF NOT EXISTS only; no DELETE of existing rows.
--   - Seeds use ON CONFLICT (code) DO UPDATE.
--   - Drops legacy UNIQUE(rank) so street and road may share rank 400.
--
-- =============================================================================

begin;

create schema if not exists ref;

-- ---------------------------------------------------------------------------
-- Table (legacy baseline: id, code, name, rank)
-- ---------------------------------------------------------------------------
create table if not exists ref.ref_address_component_types (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    rank integer not null
);

-- ---------------------------------------------------------------------------
-- Columns for bilingual composition + composer metadata
-- ---------------------------------------------------------------------------
alter table ref.ref_address_component_types
    add column if not exists name_en text,
    add column if not exists name_my text,
    add column if not exists is_admin_component boolean not null default false,
    add column if not exists is_street_component boolean not null default false,
    add column if not exists is_required_for_search boolean not null default false,
    add column if not exists is_public boolean not null default true;

-- Backfill bilingual labels from legacy name where missing
update ref.ref_address_component_types
set
    name_en = coalesce(nullif(btrim(name_en), ''), nullif(btrim(name), '')),
    name_my = coalesce(nullif(btrim(name_my), ''), nullif(btrim(name), ''))
where nullif(btrim(name_en), '') is null
   or nullif(btrim(name_my), '') is null;

-- Stable code slug (idempotent)
do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'ref.ref_address_component_types'::regclass
          and conname = 'ref_address_component_types_code_key'
    ) then
        alter table ref.ref_address_component_types
            add constraint ref_address_component_types_code_key unique (code);
    end if;
end
$migration$;

do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'ref.ref_address_component_types'::regclass
          and conname = 'ref_address_component_types_code_format_chk'
    ) then
        alter table ref.ref_address_component_types
            add constraint ref_address_component_types_code_format_chk
                check (btrim(code) <> '' and code ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$');
    end if;
end
$migration$;

-- street and road both use rank 400; legacy UNIQUE(rank) blocks that
alter table ref.ref_address_component_types
    drop constraint if exists ref_address_component_types_rank_key;

create index if not exists ref_address_component_types_code_idx
    on ref.ref_address_component_types (code);

create index if not exists ref_address_component_types_rank_code_idx
    on ref.ref_address_component_types (rank asc, code asc);

create index if not exists ref_address_component_types_is_public_idx
    on ref.ref_address_component_types (is_public)
    where is_public = true;

comment on table ref.ref_address_component_types is
    'Taxonomy of structured address component roles. Full address text is generated from '
    'core/import_review address_components rows — not stored as the source of truth. '
    'Composers order by rank ascending (then code); en/my lines use language_code on each component.';

comment on column ref.ref_address_component_types.code is
    'Stable lowercase snake_case slug referenced by component_type_code (never hardcode numeric ids in app logic).';

comment on column ref.ref_address_component_types.rank is
    'Composition sort key: lower rank appears earlier in generated full address (admin block before street before house_number). '
    'Multiple codes may share the same rank (e.g. street and road at 400).';

comment on column ref.ref_address_component_types.name_en is
    'English label for dashboards and generated full_address_en segments.';

comment on column ref.ref_address_component_types.name_my is
    'Myanmar label for dashboards and generated full_address_my segments.';

comment on column ref.ref_address_component_types.is_admin_component is
    'True when the line typically comes from admin-area hierarchy (country … village).';

comment on column ref.ref_address_component_types.is_street_component is
    'True when the line is a street/road name (often matched to core.core_streets).';

comment on column ref.ref_address_component_types.is_required_for_search is
    'When true, search indexing should prefer addresses that include this component type.';

-- ---------------------------------------------------------------------------
-- Seed systematic component types (ON CONFLICT code — never delete extras)
-- ---------------------------------------------------------------------------
insert into ref.ref_address_component_types (
    code,
    name,
    name_en,
    name_my,
    rank,
    is_admin_component,
    is_street_component,
    is_required_for_search,
    is_public
)
values
    ('country', 'Country', 'Country', 'နိုင်ငံ', 1000, true, false, false, true),
    ('region', 'Region', 'Region', 'တိုင်းဒေသကြီး', 900, true, false, false, true),
    ('district', 'District', 'District', 'ခရိုင်', 800, true, false, false, true),
    ('township', 'Township', 'Township', 'မြို့နယ်', 700, true, false, false, true),
    ('city', 'City', 'City', 'မြို့', 650, true, false, false, true),
    ('town', 'Town', 'Town', 'မြို့ငယ်', 640, true, false, false, true),
    ('ward', 'Ward', 'Ward', 'ရပ်ကွက်', 600, true, false, false, true),
    ('quarter', 'Quarter', 'Quarter', 'ရပ်ကွက်ခွဲ', 590, true, false, false, true),
    ('village_tract', 'Village tract', 'Village tract', 'ကျေးရွာအုပ်စု', 580, true, false, false, true),
    ('village', 'Village', 'Village', 'ကျေးရွာ', 570, true, false, false, true),
    ('street', 'Street', 'Street', 'လမ်း', 400, false, true, false, true),
    ('road', 'Road', 'Road', 'လမ်းကြောင်း', 400, false, true, false, true),
    ('building', 'Building', 'Building', 'အဆောက်အဦ', 300, false, false, false, true),
    ('floor', 'Floor', 'Floor', 'အထပ်', 250, false, false, false, true),
    ('unit', 'Unit', 'Unit', 'ယူနစ်', 240, false, false, false, true),
    ('house_number', 'House number', 'House number', 'အိမ်အမှတ်', 200, false, false, false, true),
    ('landmark', 'Landmark', 'Landmark', 'နေရာလမ်းညွှန်', 150, false, false, false, true),
    ('postcode', 'Postcode', 'Postcode', 'စာပို့သင်္ကေတ', 100, false, false, false, true),
    ('plus_code', 'Plus code', 'Plus code', 'Plus Code', 90, false, false, false, true)
on conflict (code) do update
set
    name = excluded.name,
    name_en = excluded.name_en,
    name_my = excluded.name_my,
    rank = excluded.rank,
    is_admin_component = excluded.is_admin_component,
    is_street_component = excluded.is_street_component,
    is_required_for_search = excluded.is_required_for_search,
    is_public = excluded.is_public;

commit;

-- =============================================================================
-- Verification (read-only; safe to re-run after migration)
-- =============================================================================

-- 1) All component types ordered by composition rank
select
    code,
    rank,
    name_en,
    name_my,
    is_admin_component,
    is_street_component,
    is_required_for_search,
    is_public
from ref.ref_address_component_types
order by rank asc, code asc;

-- 2) Duplicate codes (expect zero rows)
select code, count(*) as row_count
from ref.ref_address_component_types
group by code
having count(*) > 1
order by code;

-- 3) Required / role flags summary
select
    code,
    rank,
    is_admin_component,
    is_street_component,
    is_required_for_search,
    is_public,
    case
        when is_admin_component then 'admin'
        when is_street_component then 'street'
        else 'other'
    end as composition_group
from ref.ref_address_component_types
order by rank asc, code asc;
