-- =============================================================================
-- Supabase migration 041: import_review.address_components (bilingual review)
-- =============================================================================
--
-- Purpose:
--   Review-time structured address parts for import_review.address_candidates.
--   Full address strings on the candidate row are generated caches only — editors
--   work on component_value + language_code (en / my / und) here.
--
-- Safety:
--   - CREATE TABLE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS (repair partial DDL).
--   - No DELETE; no UPDATE of existing component_value or language_code.
--   - Optional backfill: component_type_id and sort_order only where currently NULL.
--   - Guarded FK blocks (skip with NOTICE when parent tables missing).
--
-- Depends on: 024 (address_candidates), 040 (ref_address_component_types), 037 (admin metadata).
--
-- =============================================================================

begin;

create schema if not exists import_review;

-- ---------------------------------------------------------------------------
-- Table (create if missing; legacy/partial shapes repaired via ALTER below)
-- ---------------------------------------------------------------------------
create table if not exists import_review.address_components (
    id bigint generated by default as identity primary key,
    address_candidate_id bigint not null,
    component_type_code text not null,
    component_value text not null,
    language_code text not null default 'und',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Columns (idempotent repair)
-- ---------------------------------------------------------------------------
alter table import_review.address_components
    add column if not exists component_type_id bigint,
    add column if not exists source_tag text,
    add column if not exists sort_order integer,
    add column if not exists confidence_score numeric,
    add column if not exists match_type text,
    add column if not exists is_inferred boolean not null default false,
    add column if not exists is_reviewed boolean not null default false,
    add column if not exists is_deleted boolean not null default false,
    add column if not exists source_refs jsonb not null default '{}'::jsonb,
    add column if not exists normalized_data jsonb not null default '{}'::jsonb,
    add column if not exists review_note text,
    add column if not exists source_admin_area_id bigint,
    add column if not exists boundary_status text,
    add column if not exists address_usage text;

-- Ensure jsonb / boolean defaults on columns added without NOT NULL in older passes
alter table import_review.address_components
    alter column source_refs set default '{}'::jsonb,
    alter column normalized_data set default '{}'::jsonb,
    alter column is_inferred set default false,
    alter column is_reviewed set default false,
    alter column is_deleted set default false;

update import_review.address_components
set source_refs = '{}'::jsonb
where source_refs is null;

update import_review.address_components
set normalized_data = '{}'::jsonb
where normalized_data is null;

update import_review.address_components
set language_code = 'und'
where language_code is null
   or btrim(language_code) = '';

-- ---------------------------------------------------------------------------
-- Check constraints (add only if missing)
-- ---------------------------------------------------------------------------
do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_language_code_chk'
    ) then
        alter table import_review.address_components
            add constraint irr_acmp_language_code_chk
                check (language_code in ('en', 'my', 'und'));
    end if;
end
$migration$;

do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_component_value_chk'
    ) then
        alter table import_review.address_components
            add constraint irr_acmp_component_value_chk
                check (btrim(component_value) <> '');
    end if;
end
$migration$;

do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_component_type_code_format_chk'
    ) then
        alter table import_review.address_components
            add constraint irr_acmp_component_type_code_format_chk
                check (
                    btrim(component_type_code) <> ''
                    and component_type_code ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'
                );
    end if;
end
$migration$;

do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_confidence_chk'
    ) then
        alter table import_review.address_components
            add constraint irr_acmp_confidence_chk
                check (
                    confidence_score is null
                    or (confidence_score >= 0 and confidence_score <= 100)
                );
    end if;
end
$migration$;

do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_sort_order_chk'
    ) then
        alter table import_review.address_components
            add constraint irr_acmp_sort_order_chk
                check (sort_order is null or sort_order >= 0);
    end if;
end
$migration$;

-- ---------------------------------------------------------------------------
-- Backfill (NULL-only; never overwrite existing values)
-- ---------------------------------------------------------------------------
update import_review.address_components AS ac
set component_type_id = t.id
from ref.ref_address_component_types AS t
where ac.component_type_id is null
  and ac.component_type_code = t.code;

update import_review.address_components AS ac
set sort_order = t.rank
from ref.ref_address_component_types AS t
where ac.sort_order is null
  and ac.component_type_id = t.id;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists irr_acmp_address_candidate_id_idx
    on import_review.address_components (address_candidate_id);

create index if not exists irr_acmp_component_type_code_idx
    on import_review.address_components (component_type_code);

create index if not exists irr_acmp_language_code_idx
    on import_review.address_components (language_code);

create index if not exists irr_acmp_candidate_type_lang_idx
    on import_review.address_components (address_candidate_id, component_type_code, language_code);

create index if not exists irr_acmp_source_admin_area_id_idx
    on import_review.address_components (source_admin_area_id)
    where source_admin_area_id is not null;

create index if not exists irr_acmp_active_candidate_idx
    on import_review.address_components (address_candidate_id)
    where is_deleted = false;

-- ---------------------------------------------------------------------------
-- Foreign keys (guarded)
-- ---------------------------------------------------------------------------
do $migration$
declare
    v_orphan_count bigint;
begin
    if to_regclass('import_review.address_candidates') is null then
        raise notice 'Skipping irr_acmp_address_candidate_id_fkey: import_review.address_candidates missing';
        return;
    end if;

    if exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_address_candidate_id_fkey'
    ) then
        return;
    end if;

    select count(*)::bigint
    into v_orphan_count
    from import_review.address_components AS ac
    where not exists (
        select 1
        from import_review.address_candidates AS c
        where c.id = ac.address_candidate_id
    );

    if v_orphan_count > 0 then
        raise notice
            'Skipping irr_acmp_address_candidate_id_fkey: % orphan address_candidate_id row(s); fix data then re-run',
            v_orphan_count;
        return;
    end if;

    alter table import_review.address_components
        add constraint irr_acmp_address_candidate_id_fkey
            foreign key (address_candidate_id)
            references import_review.address_candidates (id)
            on delete cascade;
end
$migration$;

do $migration$
declare
    v_orphan_count bigint;
begin
    if to_regclass('ref.ref_address_component_types') is null then
        raise notice 'Skipping irr_acmp_component_type_id_fkey: ref.ref_address_component_types missing';
        return;
    end if;

    if exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_component_type_id_fkey'
    ) then
        return;
    end if;

    select count(*)::bigint
    into v_orphan_count
    from import_review.address_components AS ac
    where ac.component_type_id is not null
      and not exists (
          select 1
          from ref.ref_address_component_types AS t
          where t.id = ac.component_type_id
      );

    if v_orphan_count > 0 then
        raise notice
            'Skipping irr_acmp_component_type_id_fkey: % orphan component_type_id row(s); fix data then re-run',
            v_orphan_count;
        return;
    end if;

    alter table import_review.address_components
        add constraint irr_acmp_component_type_id_fkey
            foreign key (component_type_id)
            references ref.ref_address_component_types (id);
end
$migration$;

do $migration$
declare
    v_orphan_count bigint;
begin
    if to_regclass('core.core_admin_areas') is null then
        raise notice 'Skipping irr_acmp_source_admin_area_id_fkey: core.core_admin_areas missing';
        return;
    end if;

    if exists (
        select 1
        from pg_constraint
        where conrelid = 'import_review.address_components'::regclass
          and conname = 'irr_acmp_source_admin_area_id_fkey'
    ) then
        return;
    end if;

    select count(*)::bigint
    into v_orphan_count
    from import_review.address_components AS ac
    where ac.source_admin_area_id is not null
      and not exists (
          select 1
          from core.core_admin_areas AS aa
          where aa.id = ac.source_admin_area_id
      );

    if v_orphan_count > 0 then
        raise notice
            'Skipping irr_acmp_source_admin_area_id_fkey: % orphan source_admin_area_id row(s); fix data then re-run',
            v_orphan_count;
        return;
    end if;

    alter table import_review.address_components
        add constraint irr_acmp_source_admin_area_id_fkey
            foreign key (source_admin_area_id)
            references core.core_admin_areas (id);
end
$migration$;

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------
comment on table import_review.address_components is
    'Editable structured address lines for import_review.address_candidates during remote review. '
    'Bilingual values use language_code en, my, or und (neutral tokens). '
    'Generated full_address / full_address_en / full_address_my on the parent candidate are readonly caches — not edited here.';

comment on column import_review.address_components.component_type_code is
    'Stable slug from ref.ref_address_component_types.code; use code in app logic, not numeric id alone.';

comment on column import_review.address_components.language_code is
    'en or my for display prose; und for house_number, postcode, plus_code, country code, etc.';

comment on column import_review.address_components.sort_order is
    'Optional override for composition order; when null, composers may use ref.ref_address_component_types.rank.';

comment on column import_review.address_components.boundary_status is
    'Snapshot of admin-area boundary_status when this line came from a matched polygon (composition metadata).';

comment on column import_review.address_components.address_usage is
    'Snapshot of admin-area address_usage (official, locality_hint, search_only, disabled).';

comment on column import_review.address_components.match_type is
    'How the line was matched, e.g. point_in_polygon, nearest_centroid, parent_fallback, explicit_override.';

commit;

-- =============================================================================
-- Verification (read-only; safe to re-run)
-- =============================================================================

-- 1) Count by component_type_code and language_code
select
    component_type_code,
    language_code,
    count(*)::bigint AS row_count,
    count(*) filter (where is_deleted)::bigint AS deleted_count
from import_review.address_components
group by component_type_code, language_code
order by component_type_code, language_code;

-- 2) Sample active components (newest first)
select
    id,
    address_candidate_id,
    component_type_code,
    component_value,
    language_code,
    sort_order,
    confidence_score,
    match_type,
    is_inferred,
    is_reviewed,
    is_deleted,
    source_admin_area_id,
    boundary_status,
    address_usage,
    created_at
from import_review.address_components
where is_deleted = false
order by updated_at desc nulls last, id desc
limit 25;

-- 3) Invalid language_code (expect zero rows)
select
    id,
    address_candidate_id,
    component_type_code,
    language_code,
    component_value
from import_review.address_components
where language_code is null
   or language_code not in ('en', 'my', 'und');
