-- Minimal append-only audit trail for Transport dashboard write actions.
--
-- Records who changed what for Transport admin mutations (routes, route variants,
-- stops, terminals, infrastructure lines, route_stops) with minimal storage impact:
--   * only the fields that actually changed, plus their old/new values
--   * point moves store only old/new lat/lng (never full geometry)
--   * route_stop removal stores the full (small) deleted row, since the row is gone
--   * full source_refs / normalized_data are intentionally NOT stored
--
-- Per AGENTS.md performance ordering, no query indexes are added yet; add them when
-- an audit-log viewer is built. The table is append-only and never updated in place.

begin;

create schema if not exists transport;

create table if not exists transport.transport_audit_logs (
    id bigint generated by default as identity,
    action text not null,
    entity_type text not null,
    entity_id bigint not null,
    entity_public_id uuid null,
    changed_fields jsonb not null default '[]'::jsonb,
    old_values jsonb null,
    new_values jsonb null,
    actor_user_id bigint null,
    request_id text null,
    metadata jsonb null,
    created_at timestamptz not null default now(),
    constraint transport_audit_logs_pkey primary key (id)
);

comment on table transport.transport_audit_logs is
    'Append-only audit trail of Transport dashboard write actions. Stores only changed fields and their old/new values (not full rows), except route_stop removal which stores the small deleted row.';
comment on column transport.transport_audit_logs.action is
    'Action code, e.g. transport.route.update, transport.stop.point_move, transport.route_stop.reorder, transport.route_stop.remove.';
comment on column transport.transport_audit_logs.entity_type is
    'Entity family, e.g. transport_route, transport_route_variant, transport_stop, transport_terminal, transport_infrastructure_line, transport_route_stop.';
comment on column transport.transport_audit_logs.entity_id is
    'Internal bigint primary key of the affected row.';
comment on column transport.transport_audit_logs.entity_public_id is
    'Public uuid when the entity exposes one; null for route_stops (no public_id).';
comment on column transport.transport_audit_logs.changed_fields is
    'JSON array of field names that actually changed (empty for whole-row deletions).';
comment on column transport.transport_audit_logs.old_values is
    'Old values of changed fields only (point moves: {lat,lng}; route_stop remove: full small deleted row).';
comment on column transport.transport_audit_logs.new_values is
    'New values of changed fields only (null for deletions).';
comment on column transport.transport_audit_logs.actor_user_id is
    'App user id of the admin who performed the action when resolvable, else null. No FK so audited writes are never blocked.';
comment on column transport.transport_audit_logs.request_id is
    'Correlating API request id when available.';
comment on column transport.transport_audit_logs.metadata is
    'Optional small context (e.g. reorder direction, related variant public id).';

commit;
