-- 114_share_links_mvp.sql
--
-- Purpose:
--   Add minimal CoreMap-only short share links. A share link points at either a
--   core place (by its public uuid) or an arbitrary map point (by coordinates).
--   Resolving a code lets the web app re-open the map focused on that target.
--
-- Source-of-truth rules:
--   * The database remains the source of truth for share links.
--   * 'place' shares reference a core place via place_public_id (the place's
--     public uuid). The reference is validated in the API, not by an FK, so a
--     share survives internal id churn and resolves against the public contract.
--   * 'point' shares store their own lat/lng (+ optional zoom/address/plus_code)
--     and do not reference a core entity.
--   * `code` is a short, unguessable string generated by the API (not a uuid);
--     the API retries on the unique(code) violation.
--
-- Scope (intentionally minimal — do NOT add here):
--   * no user ownership, no privacy/permissions, no expiry
--   * no analytics tables, no QR codes, no external map links
--   access_count / last_accessed_at are lightweight counters on the row itself
--   (updated by the API on resolve); they are not an analytics subsystem.
--
-- Safety:
--   * Idempotent where practical (IF NOT EXISTS / guarded constraint swaps).
--   * NOT applied automatically — apply via the standard Supabase migration flow.

BEGIN;

-- 1) Schema for share-link entities.
CREATE SCHEMA IF NOT EXISTS share;

-- 2) Table.
CREATE TABLE IF NOT EXISTS share.share_links (
    id               bigserial      PRIMARY KEY,
    code             text           NOT NULL,
    target_type      text           NOT NULL,
    place_public_id  uuid,
    lat              double precision,
    lng              double precision,
    zoom             numeric,
    address_line     text,
    plus_code        text,
    created_at       timestamptz    NOT NULL DEFAULT now(),
    last_accessed_at timestamptz,
    access_count     bigint         NOT NULL DEFAULT 0
);

-- 3) Allowed target types.
ALTER TABLE share.share_links
    DROP CONSTRAINT IF EXISTS share_links_target_type_chk;
ALTER TABLE share.share_links
    ADD CONSTRAINT share_links_target_type_chk
        CHECK (target_type IN ('point', 'place'));

-- 4) Shape constraints per target_type:
--    place -> place_public_id required
--    point -> lat/lng required and within valid ranges
ALTER TABLE share.share_links
    DROP CONSTRAINT IF EXISTS share_links_shape_chk;
ALTER TABLE share.share_links
    ADD CONSTRAINT share_links_shape_chk CHECK (
        (target_type = 'place' AND place_public_id IS NOT NULL)
        OR (
            target_type = 'point'
            AND lat IS NOT NULL
            AND lng IS NOT NULL
            AND lat BETWEEN -90 AND 90
            AND lng BETWEEN -180 AND 180
        )
    );

-- 5) The public lookup key. UNIQUE enforces the short-code contract and backs
--    GET /share/:code equality lookups.
CREATE UNIQUE INDEX IF NOT EXISTS share_links_code_key
    ON share.share_links (code);

-- 6) Dedup for 'place' shares: one row per shared place.
CREATE UNIQUE INDEX IF NOT EXISTS share_links_place_unique
    ON share.share_links (place_public_id)
    WHERE target_type = 'place';

-- 7) Dedup for 'point' shares via an immutable expression index.
--    round(double precision::numeric, n) and coalesce() are IMMUTABLE, so this is
--    safe as a unique index. Coordinates are rounded to ~1m (5 dp) and zoom to
--    2 dp; NULL zoom is coalesced to -1 so two coordinate-only point shares still
--    dedup instead of being treated as distinct NULLs.
CREATE UNIQUE INDEX IF NOT EXISTS share_links_point_unique
    ON share.share_links (
        round(lat::numeric, 5),
        round(lng::numeric, 5),
        round(coalesce(zoom, -1), 2)
    )
    WHERE target_type = 'point';

COMMIT;
