-- =============================================================================
-- Supabase migration 136: import_work schema + places pilot work table
-- =============================================================================
--
-- Purpose:
--   Temporary, private set-based loading workspace for classified local-osm
--   rows before safe core writes. NOT raw OSM. NOT import_review.
--
-- Scope (pilot):
--   - import_work.import_batches   (shared batch metadata only)
--   - import_work.place_rows       (settlements/places family only)
--
-- Safety:
--   - Does not modify core.*, import_review.*, tiles.*, or public.
--   - No anon / authenticated / authenticator / service_role grants.
--   - Schema USAGE revoked from PUBLIC and API roles (matches import_review).
--   - RLS enabled with ZERO policies (defense in depth if ever exposed).
--   - No production data load in this migration.
--
-- Apply: deliberate Supabase migration / SQL Editor. Not CI auto-apply.
--
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS import_work;

COMMENT ON SCHEMA import_work IS
    'Temporary private workspace for set-based core loads from local classification. '
    'Not raw OSM. Not public API. Not import_review.';

-- ---------------------------------------------------------------------------
-- Shared batch metadata (minimal — not a generic workflow engine)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS import_work.import_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code text NOT NULL,
    entity_family text NOT NULL,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    status text NOT NULL DEFAULT 'draft',
    expected_row_count bigint NULL,
    loaded_row_count bigint NULL,
    validation_status text NOT NULL DEFAULT 'not_started',
    validation_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    loaded_at timestamptz NULL,
    cleaned_at timestamptz NULL,
    CONSTRAINT import_batches_batch_code_key UNIQUE (batch_code),
    CONSTRAINT import_batches_batch_code_nonempty_chk CHECK (btrim(batch_code) <> ''),
    CONSTRAINT import_batches_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT import_batches_entity_family_chk CHECK (
        entity_family IN (
            'places'
            -- additional families added only with explicit migrations
        )
    ),
    CONSTRAINT import_batches_status_chk CHECK (
        status IN (
            'draft',
            'loading',
            'loaded',
            'validated',
            'applied',
            'failed',
            'cleaned'
        )
    ),
    CONSTRAINT import_batches_validation_status_chk CHECK (
        validation_status IN (
            'not_started',
            'passed',
            'failed',
            'skipped'
        )
    )
);

CREATE INDEX IF NOT EXISTS import_batches_entity_family_status_idx
    ON import_work.import_batches (entity_family, status);

CREATE INDEX IF NOT EXISTS import_batches_snapshot_version_idx
    ON import_work.import_batches (source_snapshot_version);

COMMENT ON TABLE import_work.import_batches IS
    'Minimal batch header for temporary import_work family loads. Retry deletes prior work rows for the same batch.';

-- ---------------------------------------------------------------------------
-- Pilot family: places / settlements → core.core_places
-- Only load-ready normalized columns + classification metadata.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS import_work.place_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    -- Normalized fields required (or commonly set) for core.core_places
    primary_name text NULL,
    display_name text NULL,
    category_id bigint NULL,
    admin_area_id bigint NULL,
    point_geom geometry(Point, 4326) NULL,
    lat double precision NULL,
    lng double precision NULL,
    plus_code text NULL,
    importance_score numeric NULL,
    popularity_score numeric NULL,
    confidence_score numeric NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    loaded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT place_rows_batch_external_id_key UNIQUE (import_batch_id, external_id),
    CONSTRAINT place_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT place_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT place_rows_classification_chk CHECK (
        classification IN (
            'safe_new',
            'safe_update',
            'unchanged',
            'duplicate',
            'conflict',
            'manual_protected',
            'verified_conflict',
            'possible_delete',
            'invalid'
        )
    ),
    CONSTRAINT place_rows_validation_status_chk CHECK (
        validation_status IN ('pending', 'passed', 'failed', 'skipped')
    ),
    CONSTRAINT place_rows_lat_chk CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    CONSTRAINT place_rows_lng_chk CHECK (lng IS NULL OR lng BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS place_rows_batch_id_idx
    ON import_work.place_rows (import_batch_id);

CREATE INDEX IF NOT EXISTS place_rows_classification_idx
    ON import_work.place_rows (import_batch_id, classification);

CREATE INDEX IF NOT EXISTS place_rows_external_id_idx
    ON import_work.place_rows (external_id);

CREATE INDEX IF NOT EXISTS place_rows_target_core_id_idx
    ON import_work.place_rows (target_core_id)
    WHERE target_core_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS place_rows_point_geom_gix
    ON import_work.place_rows USING GIST (point_geom)
    WHERE point_geom IS NOT NULL;

COMMENT ON TABLE import_work.place_rows IS
    'Temporary places/settlements load rows. Retry: DELETE WHERE import_batch_id = :id then COPY again. Not raw OSM.';

COMMENT ON COLUMN import_work.place_rows.classification IS
    'Final local import_class from pipeline Stage 08b/18.';

COMMENT ON COLUMN import_work.place_rows.target_core_id IS
    'Matched core.core_places.id for safe_update / protected / conflict paths; NULL for safe_new.';

COMMENT ON COLUMN import_work.place_rows.source_hash IS
    'Content/fingerprint hash from local staging (e.g. normalized_hash / source_content_hash).';

-- ---------------------------------------------------------------------------
-- Privacy: no public client access (match live import_review posture)
-- ---------------------------------------------------------------------------

REVOKE ALL ON SCHEMA import_work FROM PUBLIC;
REVOKE ALL ON SCHEMA import_work FROM anon, authenticated, authenticator, service_role;

REVOKE ALL ON ALL TABLES IN SCHEMA import_work FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA import_work FROM anon, authenticated, authenticator, service_role;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA import_work FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA import_work FROM anon, authenticated, authenticator, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA import_work
    REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated, authenticator, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA import_work
    REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated, authenticator, service_role;

ALTER TABLE import_work.import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE import_work.place_rows ENABLE ROW LEVEL SECURITY;
-- Intentionally no policies: API roles have no schema USAGE; RLS blocks residual access.

COMMIT;
