-- =============================================================================
-- Supabase migration 141: import_work.building_rows (important/named buildings)
-- =============================================================================
--
-- Purpose:
--   Typed temporary work table for core-eligible buildings only
--   (eligible_for_core / safe_new|safe_update). Not ordinary footprints.
--
-- Safety:
--   - Does not modify core.* data.
--   - Extends import_work.import_batches.entity_family to allow 'buildings'.
--   - No anon / authenticated grants (same posture as migration 136).
--
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

-- Allow buildings family on shared batch header
ALTER TABLE import_work.import_batches
    DROP CONSTRAINT IF EXISTS import_batches_entity_family_chk;

ALTER TABLE import_work.import_batches
    ADD CONSTRAINT import_batches_entity_family_chk CHECK (
        entity_family IN (
            'places',
            'buildings'
        )
    );

CREATE TABLE IF NOT EXISTS import_work.building_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    -- Core-facing fields
    name text NULL,
    name_en text NULL,
    name_mm text NULL,
    building_type_id bigint NULL,
    class_code text NULL,
    admin_area_id bigint NULL,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    centroid geometry(Point, 4326) NULL,
    area_m2 numeric NULL,
    levels integer NULL,
    height_m numeric NULL,
    confidence_score numeric NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    core_selection_reason text NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT building_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT building_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT building_rows_classification_chk CHECK (
        classification IN (
            'safe_new',
            'safe_update',
            'unchanged',
            'duplicate',
            'conflict',
            'manual_protected',
            'verified_conflict',
            'invalid',
            'pmtiles_only'
        )
    ),
    CONSTRAINT building_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS building_rows_batch_id_idx
    ON import_work.building_rows (import_batch_id);

CREATE INDEX IF NOT EXISTS building_rows_classification_idx
    ON import_work.building_rows (classification);

CREATE INDEX IF NOT EXISTS building_rows_external_id_idx
    ON import_work.building_rows (external_id);

CREATE INDEX IF NOT EXISTS building_rows_geom_gix
    ON import_work.building_rows USING GIST (geom);

COMMENT ON TABLE import_work.building_rows IS
    'Temporary core-eligible building load rows. Never load pmtiles_only footprints here.';

COMMENT ON COLUMN import_work.building_rows.classification IS
    'Final local import_class; loader only writes safe_new / safe_update.';

COMMENT ON COLUMN import_work.building_rows.target_core_id IS
    'Matched core.core_map_buildings.id for safe_update; NULL for safe_new.';

-- Privacy: match import_work places posture when Supabase API roles exist
DO $$
BEGIN
    REVOKE ALL ON TABLE import_work.building_rows FROM PUBLIC;
    BEGIN
        REVOKE ALL ON TABLE import_work.building_rows
            FROM anon, authenticated, authenticator, service_role;
    EXCEPTION
        WHEN undefined_object THEN
            NULL;
    END;
    ALTER TABLE import_work.building_rows ENABLE ROW LEVEL SECURITY;
END $$;

COMMIT;
