-- =============================================================================
-- Supabase migration 142: import_work landuse + water typed work tables
-- =============================================================================
--
-- Purpose:
--   Temporary work tables for core-eligible landuse / water only
--   (safe_new|safe_update). Never ordinary PMTiles basemap geometry.
--
-- Safety:
--   - Does not modify core.* data.
--   - Extends import_work.import_batches.entity_family allowlist.
--   - No anon / authenticated grants.
--
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE import_work.import_batches
    DROP CONSTRAINT IF EXISTS import_batches_entity_family_chk;

ALTER TABLE import_work.import_batches
    ADD CONSTRAINT import_batches_entity_family_chk CHECK (
        entity_family IN (
            'places',
            'buildings',
            'landuse',
            'water_lines',
            'water_polygons'
        )
    );

-- ---------------------------------------------------------------------------
-- landuse_rows
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS import_work.landuse_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    name text NULL,
    name_en text NULL,
    name_mm text NULL,
    landuse_class_id bigint NULL,
    class_code text NULL,
    admin_area_id bigint NULL,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    centroid geometry(Point, 4326) NULL,
    area_m2 numeric NULL,
    confidence_score numeric NULL,
    source_tags jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    core_selection_reason text NULL,
    crop_code text NULL,
    detail_level text NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT landuse_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT landuse_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT landuse_rows_classification_chk CHECK (
        classification IN (
            'safe_new', 'safe_update', 'unchanged', 'duplicate', 'conflict',
            'manual_protected', 'verified_conflict', 'invalid', 'pmtiles_only'
        )
    ),
    CONSTRAINT landuse_rows_detail_level_chk CHECK (
        detail_level IS NULL OR detail_level IN ('zone', 'parcel')
    ),
    CONSTRAINT landuse_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS landuse_rows_batch_id_idx
    ON import_work.landuse_rows (import_batch_id);
CREATE INDEX IF NOT EXISTS landuse_rows_classification_idx
    ON import_work.landuse_rows (classification);
CREATE INDEX IF NOT EXISTS landuse_rows_external_id_idx
    ON import_work.landuse_rows (external_id);
CREATE INDEX IF NOT EXISTS landuse_rows_geom_gix
    ON import_work.landuse_rows USING GIST (geom);

COMMENT ON TABLE import_work.landuse_rows IS
    'Temporary core-eligible landuse load rows. Never load pmtiles_only here.';

-- ---------------------------------------------------------------------------
-- water_line_rows
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS import_work.water_line_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    name text NULL,
    name_en text NULL,
    name_mm text NULL,
    class_code text NOT NULL,
    geom geometry(MultiLineString, 4326) NOT NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    core_selection_reason text NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT water_line_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT water_line_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT water_line_rows_class_code_nonempty_chk CHECK (btrim(class_code) <> ''),
    CONSTRAINT water_line_rows_classification_chk CHECK (
        classification IN (
            'safe_new', 'safe_update', 'unchanged', 'duplicate', 'conflict',
            'manual_protected', 'verified_conflict', 'invalid', 'pmtiles_only'
        )
    ),
    CONSTRAINT water_line_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS water_line_rows_batch_id_idx
    ON import_work.water_line_rows (import_batch_id);
CREATE INDEX IF NOT EXISTS water_line_rows_classification_idx
    ON import_work.water_line_rows (classification);
CREATE INDEX IF NOT EXISTS water_line_rows_external_id_idx
    ON import_work.water_line_rows (external_id);
CREATE INDEX IF NOT EXISTS water_line_rows_geom_gix
    ON import_work.water_line_rows USING GIST (geom);

COMMENT ON TABLE import_work.water_line_rows IS
    'Temporary core-eligible named water line load rows. Never pmtiles_only.';

-- ---------------------------------------------------------------------------
-- water_polygon_rows
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS import_work.water_polygon_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    name text NULL,
    name_en text NULL,
    name_mm text NULL,
    class_code text NOT NULL,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    core_selection_reason text NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT water_polygon_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT water_polygon_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT water_polygon_rows_class_code_nonempty_chk CHECK (btrim(class_code) <> ''),
    CONSTRAINT water_polygon_rows_classification_chk CHECK (
        classification IN (
            'safe_new', 'safe_update', 'unchanged', 'duplicate', 'conflict',
            'manual_protected', 'verified_conflict', 'invalid', 'pmtiles_only'
        )
    ),
    CONSTRAINT water_polygon_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS water_polygon_rows_batch_id_idx
    ON import_work.water_polygon_rows (import_batch_id);
CREATE INDEX IF NOT EXISTS water_polygon_rows_classification_idx
    ON import_work.water_polygon_rows (classification);
CREATE INDEX IF NOT EXISTS water_polygon_rows_external_id_idx
    ON import_work.water_polygon_rows (external_id);
CREATE INDEX IF NOT EXISTS water_polygon_rows_geom_gix
    ON import_work.water_polygon_rows USING GIST (geom);

COMMENT ON TABLE import_work.water_polygon_rows IS
    'Temporary core-eligible named water polygon load rows. Never pmtiles_only.';

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'import_work.landuse_rows',
        'import_work.water_line_rows',
        'import_work.water_polygon_rows'
    ]
    LOOP
        EXECUTE format('REVOKE ALL ON TABLE %s FROM PUBLIC', t);
        BEGIN
            EXECUTE format(
                'REVOKE ALL ON TABLE %s FROM anon, authenticated, authenticator, service_role',
                t
            );
        EXCEPTION
            WHEN undefined_object THEN
                NULL;
        END;
        EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;

COMMIT;
