-- =============================================================================
-- Supabase migration 143: import_work.routing_barrier_rows
-- =============================================================================
--
-- Temporary work table for routing barrier safe_new / safe_update only.
-- Does not modify routing.routing_barriers data.
-- Does not rebuild Valhalla.
--
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE import_work.import_batches
    DROP CONSTRAINT IF EXISTS import_batches_entity_family_chk;

ALTER TABLE import_work.import_batches
    ADD CONSTRAINT import_batches_entity_family_chk CHECK (
        entity_family IN (
            'places',
            'buildings',
            'landuse',
            'water_lines',
            'water_polygons',
            'routing_barriers'
        )
    );

CREATE TABLE IF NOT EXISTS import_work.routing_barrier_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    barrier_type text NOT NULL,
    access_tags jsonb NOT NULL DEFAULT '{}'::jsonb,
    point_geom geometry(Point, 4326) NULL,
    geom geometry NULL,
    core_street_id bigint NULL,
    confidence_score numeric NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    local_staging_id bigint NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT routing_barrier_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT routing_barrier_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT routing_barrier_rows_barrier_type_nonempty_chk CHECK (btrim(barrier_type) <> ''),
    CONSTRAINT routing_barrier_rows_classification_chk CHECK (
        classification IN (
            'safe_new', 'safe_update', 'unchanged', 'duplicate', 'conflict',
            'manual_protected', 'verified_conflict', 'invalid', 'pmtiles_only'
        )
    ),
    CONSTRAINT routing_barrier_rows_confidence_chk CHECK (
        confidence_score IS NULL
        OR (confidence_score >= 0 AND confidence_score <= 100)
    ),
    CONSTRAINT routing_barrier_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS routing_barrier_rows_batch_id_idx
    ON import_work.routing_barrier_rows (import_batch_id);
CREATE INDEX IF NOT EXISTS routing_barrier_rows_classification_idx
    ON import_work.routing_barrier_rows (classification);
CREATE INDEX IF NOT EXISTS routing_barrier_rows_external_id_idx
    ON import_work.routing_barrier_rows (external_id);
CREATE INDEX IF NOT EXISTS routing_barrier_rows_point_geom_gix
    ON import_work.routing_barrier_rows USING GIST (point_geom);

COMMENT ON TABLE import_work.routing_barrier_rows IS
    'Temporary routing barrier load rows (safe_new/safe_update). High-risk changes go to Import Review.';

DO $$
BEGIN
    REVOKE ALL ON TABLE import_work.routing_barrier_rows FROM PUBLIC;
    BEGIN
        REVOKE ALL ON TABLE import_work.routing_barrier_rows
            FROM anon, authenticated, authenticator, service_role;
    EXCEPTION
        WHEN undefined_object THEN
            NULL;
    END;
    ALTER TABLE import_work.routing_barrier_rows ENABLE ROW LEVEL SECURITY;
END $$;

COMMIT;
