-- =============================================================================
-- Supabase migration 144: import_work.road_rows
-- =============================================================================
--
-- Temporary work table for road safe_new / safe_update only.
-- Does not modify core.core_streets data.
-- Does not start a national road import.
--
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE import_work.import_batches
    DROP CONSTRAINT IF EXISTS import_batches_entity_family_chk;

ALTER TABLE import_work.import_batches
    ADD CONSTRAINT import_batches_entity_family_chk CHECK (
        entity_family IN (
            'places',
            'buildings',
            'landuse',
            'water_lines',
            'water_polygons',
            'routing_barriers',
            'roads'
        )
    );

CREATE TABLE IF NOT EXISTS import_work.road_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    -- Core-facing fields (only what safe apply needs)
    canonical_name text NOT NULL,
    name_en text NULL,
    name_mm text NULL,
    road_class_id bigint NULL,
    class_code text NULL,
    admin_area_id bigint NULL,
    geom geometry NOT NULL,
    is_oneway boolean NOT NULL DEFAULT false,
    bridge boolean NOT NULL DEFAULT false,
    tunnel boolean NOT NULL DEFAULT false,
    layer integer NOT NULL DEFAULT 0,
    surface text NULL,
    confidence_score numeric NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    local_staging_id bigint NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT road_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT road_rows_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT road_rows_canonical_name_nonempty_chk CHECK (btrim(canonical_name) <> ''),
    CONSTRAINT road_rows_classification_chk CHECK (
        classification IN (
            'safe_new', 'safe_update', 'unchanged', 'duplicate', 'conflict',
            'manual_protected', 'verified_conflict', 'invalid', 'pmtiles_only'
        )
    ),
    CONSTRAINT road_rows_confidence_chk CHECK (
        confidence_score IS NULL
        OR (confidence_score >= 0 AND confidence_score <= 100)
    ),
    CONSTRAINT road_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS road_rows_batch_id_idx
    ON import_work.road_rows (import_batch_id);
CREATE INDEX IF NOT EXISTS road_rows_classification_idx
    ON import_work.road_rows (classification);
CREATE INDEX IF NOT EXISTS road_rows_external_id_idx
    ON import_work.road_rows (external_id);
CREATE INDEX IF NOT EXISTS road_rows_geom_gix
    ON import_work.road_rows USING GIST (geom);

COMMENT ON TABLE import_work.road_rows IS
    'Temporary road load rows (safe_new/safe_update). High-risk changes go to Import Review.';

COMMENT ON COLUMN import_work.road_rows.classification IS
    'Final local import_class; loader only writes safe_new / safe_update.';

COMMENT ON COLUMN import_work.road_rows.target_core_id IS
    'Matched core.core_streets.id for safe_update; NULL for safe_new.';

DO $$
BEGIN
    REVOKE ALL ON TABLE import_work.road_rows FROM PUBLIC;
    BEGIN
        REVOKE ALL ON TABLE import_work.road_rows
            FROM anon, authenticated, authenticator, service_role;
    EXCEPTION
        WHEN undefined_object THEN
            NULL;
    END;
    ALTER TABLE import_work.road_rows ENABLE ROW LEVEL SECURITY;
END $$;

COMMIT;
