-- =============================================================================
-- Supabase migration 156: water taxonomy (ref.ref_water_classes) + lineage
-- =============================================================================
--
-- Scope:
--   * Create ONE taxonomy: ref.ref_water_classes (shared by lines + polygons)
--   * Add core.core_water_lines.water_class_id / core.core_water_polygons.water_class_id
--   * Add import_review water candidate water_class_id columns
--   * Intelligent backfill from tags then legacy class_code
--   * Persist anomaly report for invalid/ambiguous codes
--   * Add buildings-style OSM lineage columns + safe source_refs backfill
--   * Refresh tiles + search views to prefer water_class_id + ref labels
--
-- Does NOT:
--   * drop legacy class_code
--   * change Martin/PMTiles source-layer names
--   * change RLS
--   * invent categories from yes / seasonal / intermittent / eris / lake;pond
-- =============================================================================

BEGIN;

SET LOCAL lock_timeout = '30s';
SET LOCAL statement_timeout = '30min';

CREATE TEMP TABLE _m156_before ON COMMIT DROP AS
SELECT
  (SELECT count(*)::bigint FROM core.core_water_lines) AS water_lines,
  (SELECT count(*)::bigint FROM core.core_water_polygons) AS water_polygons,
  (SELECT count(*)::bigint FROM core.core_water_line_names) AS water_line_names,
  (SELECT count(*)::bigint FROM core.core_water_polygon_names) AS water_polygon_names,
  (SELECT count(*)::bigint FROM core.core_water_lines WHERE geom IS NOT NULL) AS lines_with_geom,
  (SELECT count(*)::bigint FROM core.core_water_polygons WHERE geom IS NOT NULL) AS polygons_with_geom;

DO $$
BEGIN
  RAISE NOTICE '156 before: %', (SELECT row_to_json(b) FROM _m156_before b);
END $$;

-- ---------------------------------------------------------------------------
-- 1) Taxonomy table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref.ref_water_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name_en text NOT NULL,
  name_mm text NULL,
  parent_id bigint NULL REFERENCES ref.ref_water_classes (id),
  sort_order integer NOT NULL DEFAULT 100,
  min_zoom numeric NOT NULL DEFAULT 12,
  is_public boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_water_classes_code_key UNIQUE (code),
  CONSTRAINT ref_water_classes_code_format_chk
    CHECK (btrim(code) <> '' AND code ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'),
  CONSTRAINT ref_water_classes_min_zoom_chk
    CHECK (min_zoom >= 0 AND min_zoom <= 24)
);

CREATE INDEX IF NOT EXISTS ref_water_classes_parent_id_idx
  ON ref.ref_water_classes (parent_id);
CREATE INDEX IF NOT EXISTS ref_water_classes_is_active_idx
  ON ref.ref_water_classes (is_active);
CREATE INDEX IF NOT EXISTS ref_water_classes_code_idx
  ON ref.ref_water_classes (code);

COMMENT ON TABLE ref.ref_water_classes IS
  'CoreMap water taxonomy for lines + polygons. Not an OSM tag dump.';

-- Seed hierarchy (idempotent by code)
INSERT INTO ref.ref_water_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active
)
VALUES
  ('flowing_water', 'Flowing water', NULL, NULL, 10, 8, true, true),
  ('standing_water', 'Standing water', NULL, NULL, 20, 8, true, true),
  ('water_structure', 'Water structure', NULL, NULL, 30, 12, true, true),
  ('other', 'Other water', NULL, NULL, 90, 12, true, true)
ON CONFLICT (code) DO UPDATE
SET name_en = EXCLUDED.name_en,
    parent_id = NULL,
    is_active = true,
    updated_at = now();

INSERT INTO ref.ref_water_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active
)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, true, true
FROM (VALUES
  ('river', 'River', 0, 8::numeric),
  ('stream', 'Stream', 1, 11),
  ('canal', 'Canal', 2, 11),
  ('tidal_channel', 'Tidal channel', 3, 12),
  ('ditch', 'Ditch', 4, 13),
  ('drain', 'Drain', 5, 13)
) AS v(code, name_en, sort_order, min_zoom)
JOIN ref.ref_water_classes p ON p.code = 'flowing_water'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name_en = EXCLUDED.name_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

INSERT INTO ref.ref_water_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active
)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, true, true
FROM (VALUES
  ('water', 'Water body', 0, 8::numeric),
  ('lake', 'Lake', 1, 9),
  ('reservoir', 'Reservoir', 2, 10),
  ('pond', 'Pond', 3, 13),
  ('basin', 'Basin', 4, 13),
  ('lagoon', 'Lagoon', 5, 12),
  ('oxbow', 'Oxbow', 6, 12),
  ('fishpond', 'Fishpond', 7, 13),
  ('moat', 'Moat', 8, 13),
  ('stream_pool', 'Stream pool', 9, 14),
  ('wastewater', 'Wastewater', 10, 14)
) AS v(code, name_en, sort_order, min_zoom)
JOIN ref.ref_water_classes p ON p.code = 'standing_water'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name_en = EXCLUDED.name_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

INSERT INTO ref.ref_water_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active
)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, true, true
FROM (VALUES
  ('dam', 'Dam', 0, 12::numeric),
  ('weir', 'Weir', 1, 13),
  ('lock', 'Lock', 2, 13),
  ('lock_gate', 'Lock gate', 3, 14),
  ('sluice_gate', 'Sluice gate', 4, 14),
  ('waterfall', 'Waterfall', 5, 13),
  ('dock', 'Dock', 6, 13),
  ('boatyard', 'Boatyard', 7, 14)
) AS v(code, name_en, sort_order, min_zoom)
JOIN ref.ref_water_classes p ON p.code = 'water_structure'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name_en = EXCLUDED.name_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

-- ---------------------------------------------------------------------------
-- 2) Core + import_review columns
-- ---------------------------------------------------------------------------
ALTER TABLE core.core_water_lines
  ADD COLUMN IF NOT EXISTS water_class_id bigint,
  ADD COLUMN IF NOT EXISTS source_registry_id bigint,
  ADD COLUMN IF NOT EXISTS source_snapshot_id bigint,
  ADD COLUMN IF NOT EXISTS source_feature_type text,
  ADD COLUMN IF NOT EXISTS source_feature_id bigint,
  ADD COLUMN IF NOT EXISTS region_code text;

ALTER TABLE core.core_water_polygons
  ADD COLUMN IF NOT EXISTS water_class_id bigint,
  ADD COLUMN IF NOT EXISTS source_registry_id bigint,
  ADD COLUMN IF NOT EXISTS source_snapshot_id bigint,
  ADD COLUMN IF NOT EXISTS source_feature_type text,
  ADD COLUMN IF NOT EXISTS source_feature_id bigint,
  ADD COLUMN IF NOT EXISTS region_code text;

ALTER TABLE import_review.water_line_candidates
  ADD COLUMN IF NOT EXISTS water_class_id bigint;
ALTER TABLE import_review.water_polygon_candidates
  ADD COLUMN IF NOT EXISTS water_class_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'core_water_lines_water_class_id_fkey'
      AND conrelid = 'core.core_water_lines'::regclass
  ) THEN
    ALTER TABLE core.core_water_lines
      ADD CONSTRAINT core_water_lines_water_class_id_fkey
        FOREIGN KEY (water_class_id) REFERENCES ref.ref_water_classes (id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'core_water_polygons_water_class_id_fkey'
      AND conrelid = 'core.core_water_polygons'::regclass
  ) THEN
    ALTER TABLE core.core_water_polygons
      ADD CONSTRAINT core_water_polygons_water_class_id_fkey
        FOREIGN KEY (water_class_id) REFERENCES ref.ref_water_classes (id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'irr_wl_water_class_id_fkey'
      AND conrelid = 'import_review.water_line_candidates'::regclass
  ) THEN
    ALTER TABLE import_review.water_line_candidates
      ADD CONSTRAINT irr_wl_water_class_id_fkey
        FOREIGN KEY (water_class_id) REFERENCES ref.ref_water_classes (id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'irr_wp_water_class_id_fkey'
      AND conrelid = 'import_review.water_polygon_candidates'::regclass
  ) THEN
    ALTER TABLE import_review.water_polygon_candidates
      ADD CONSTRAINT irr_wp_water_class_id_fkey
        FOREIGN KEY (water_class_id) REFERENCES ref.ref_water_classes (id) NOT VALID;
  END IF;

  -- lineage FKs/checks for lines
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='core_water_lines_source_registry_id_fkey'
      AND conrelid='core.core_water_lines'::regclass
  ) THEN
    ALTER TABLE core.core_water_lines
      ADD CONSTRAINT core_water_lines_source_registry_id_fkey
        FOREIGN KEY (source_registry_id) REFERENCES system.system_source_registry(id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='core_water_lines_source_snapshot_id_fkey'
      AND conrelid='core.core_water_lines'::regclass
  ) THEN
    ALTER TABLE core.core_water_lines
      ADD CONSTRAINT core_water_lines_source_snapshot_id_fkey
        FOREIGN KEY (source_snapshot_id) REFERENCES system.system_source_snapshots(id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='core_water_lines_source_feature_type_chk'
      AND conrelid='core.core_water_lines'::regclass
  ) THEN
    ALTER TABLE core.core_water_lines
      ADD CONSTRAINT core_water_lines_source_feature_type_chk
        CHECK (source_feature_type IS NULL OR source_feature_type IN ('way','relation','node'))
        NOT VALID;
  END IF;

  -- lineage FKs/checks for polygons
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='core_water_polygons_source_registry_id_fkey'
      AND conrelid='core.core_water_polygons'::regclass
  ) THEN
    ALTER TABLE core.core_water_polygons
      ADD CONSTRAINT core_water_polygons_source_registry_id_fkey
        FOREIGN KEY (source_registry_id) REFERENCES system.system_source_registry(id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='core_water_polygons_source_snapshot_id_fkey'
      AND conrelid='core.core_water_polygons'::regclass
  ) THEN
    ALTER TABLE core.core_water_polygons
      ADD CONSTRAINT core_water_polygons_source_snapshot_id_fkey
        FOREIGN KEY (source_snapshot_id) REFERENCES system.system_source_snapshots(id) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname='core_water_polygons_source_feature_type_chk'
      AND conrelid='core.core_water_polygons'::regclass
  ) THEN
    ALTER TABLE core.core_water_polygons
      ADD CONSTRAINT core_water_polygons_source_feature_type_chk
        CHECK (source_feature_type IS NULL OR source_feature_type IN ('way','relation'))
        NOT VALID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS core_water_lines_water_class_id_idx
  ON core.core_water_lines (water_class_id);
CREATE INDEX IF NOT EXISTS core_water_polygons_water_class_id_idx
  ON core.core_water_polygons (water_class_id);
CREATE INDEX IF NOT EXISTS irr_wl_water_class_id_idx
  ON import_review.water_line_candidates (water_class_id);
CREATE INDEX IF NOT EXISTS irr_wp_water_class_id_idx
  ON import_review.water_polygon_candidates (water_class_id);

-- ---------------------------------------------------------------------------
-- 3) Classification helper mapping + anomaly report
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system.migration_156_water_class_anomalies (
  entity_table text NOT NULL,
  entity_id bigint NOT NULL,
  legacy_class_code text,
  tag_waterway text,
  tag_water text,
  tag_natural text,
  resolved_code text NOT NULL,
  reason text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (entity_table, entity_id)
);

TRUNCATE system.migration_156_water_class_anomalies;

CREATE TEMP TABLE _m156_resolve ON COMMIT DROP AS
WITH src AS (
  SELECT
    'core.core_water_lines'::text AS entity_table,
    w.id,
    lower(nullif(btrim(w.class_code), '')) AS legacy_code,
    lower(nullif(btrim(w.normalized_data #>> '{tags,waterway}'), '')) AS tag_waterway,
    lower(nullif(btrim(w.normalized_data #>> '{tags,water}'), '')) AS tag_water,
    lower(nullif(btrim(w.normalized_data #>> '{tags,natural}'), '')) AS tag_natural,
    lower(nullif(btrim(w.normalized_data #>> '{waterway}'), '')) AS nd_waterway,
    lower(nullif(btrim(w.normalized_data #>> '{water}'), '')) AS nd_water
  FROM core.core_water_lines w
  UNION ALL
  SELECT
    'core.core_water_polygons',
    w.id,
    lower(nullif(btrim(w.class_code), '')),
    lower(nullif(btrim(w.normalized_data #>> '{tags,waterway}'), '')),
    lower(nullif(btrim(w.normalized_data #>> '{tags,water}'), '')),
    lower(nullif(btrim(w.normalized_data #>> '{tags,natural}'), '')),
    lower(nullif(btrim(w.normalized_data #>> '{waterway}'), '')),
    lower(nullif(btrim(w.normalized_data #>> '{water}'), ''))
  FROM core.core_water_polygons w
),
norm AS (
  SELECT
    s.*,
    -- Prefer OSM tags when present; fall back to legacy class_code.
    coalesce(
      nullif(s.tag_waterway, ''),
      nullif(s.nd_waterway, ''),
      nullif(s.tag_water, ''),
      nullif(s.nd_water, ''),
      s.legacy_code
    ) AS primary_hint,
    coalesce(nullif(s.tag_water, ''), nullif(s.nd_water, ''), s.legacy_code) AS water_hint
  FROM src s
),
mapped AS (
  SELECT
    n.*,
    CASE
      -- Invalid / property-like values → other (anomaly)
      WHEN n.primary_hint IN ('yes', 'seasonal', 'intermittent', 'eris', 'pressurised')
        OR n.legacy_code IN ('yes', 'seasonal', 'intermittent', 'eris', 'pressurised')
        THEN 'other'
      WHEN n.primary_hint = 'lake;pond' OR n.legacy_code = 'lake;pond'
        THEN 'lake'
      WHEN n.primary_hint IN ('fish farming pond', 'fish_farming_pond')
        OR n.legacy_code IN ('fish farming pond', 'fish_farming_pond')
        THEN 'fishpond'
      WHEN n.primary_hint IN ('pool', 'small_water_hole')
        OR n.legacy_code IN ('pool', 'small_water_hole')
        THEN CASE
          WHEN n.entity_table = 'core.core_water_lines' THEN 'stream_pool'
          ELSE 'pond'
        END
      WHEN n.primary_hint = 'fish_pass' OR n.legacy_code = 'fish_pass'
        THEN 'other'
      -- Canonical leaf codes
      WHEN n.primary_hint IN (
        'river','stream','canal','tidal_channel','ditch','drain',
        'water','lake','reservoir','pond','basin','lagoon','oxbow','fishpond','moat','stream_pool','wastewater',
        'dam','weir','lock','lock_gate','sluice_gate','waterfall','dock','boatyard'
      ) THEN n.primary_hint
      WHEN n.water_hint IN (
        'river','stream','canal','tidal_channel','ditch','drain',
        'water','lake','reservoir','pond','basin','lagoon','oxbow','fishpond','moat','stream_pool','wastewater',
        'dam','weir','lock','lock_gate','sluice_gate','waterfall','dock','boatyard'
      ) THEN n.water_hint
      WHEN n.tag_natural = 'water' AND n.water_hint IS NULL AND n.primary_hint IS NULL
        THEN 'water'
      ELSE 'other'
    END AS resolved_code,
    CASE
      WHEN n.primary_hint IN ('yes', 'seasonal', 'intermittent', 'eris', 'pressurised')
        OR n.legacy_code IN ('yes', 'seasonal', 'intermittent', 'eris', 'pressurised')
        THEN 'invalid_or_property_value'
      WHEN n.primary_hint = 'lake;pond' OR n.legacy_code = 'lake;pond'
        THEN 'compound_value_normalized_to_lake'
      WHEN n.primary_hint IN ('fish farming pond', 'fish_farming_pond', 'pool', 'small_water_hole', 'fish_pass')
        OR n.legacy_code IN ('fish farming pond', 'fish_farming_pond', 'pool', 'small_water_hole', 'fish_pass')
        THEN 'alias_normalized'
      WHEN n.primary_hint IN (
        'river','stream','canal','tidal_channel','ditch','drain',
        'water','lake','reservoir','pond','basin','lagoon','oxbow','fishpond','moat','stream_pool','wastewater',
        'dam','weir','lock','lock_gate','sluice_gate','waterfall','dock','boatyard'
      ) OR n.water_hint IN (
        'river','stream','canal','tidal_channel','ditch','drain',
        'water','lake','reservoir','pond','basin','lagoon','oxbow','fishpond','moat','stream_pool','wastewater',
        'dam','weir','lock','lock_gate','sluice_gate','waterfall','dock','boatyard'
      )
        THEN 'canonical'
      ELSE 'unresolved_fallback_other'
    END AS reason
  FROM norm n
)
SELECT * FROM mapped;

INSERT INTO system.migration_156_water_class_anomalies (
  entity_table, entity_id, legacy_class_code, tag_waterway, tag_water, tag_natural,
  resolved_code, reason
)
SELECT
  entity_table, id, legacy_code, tag_waterway, tag_water, tag_natural,
  resolved_code, reason
FROM _m156_resolve
WHERE reason <> 'canonical';

UPDATE core.core_water_lines AS w
SET water_class_id = c.id
FROM _m156_resolve r
JOIN ref.ref_water_classes c ON c.code = r.resolved_code
WHERE r.entity_table = 'core.core_water_lines'
  AND w.id = r.id
  AND w.water_class_id IS DISTINCT FROM c.id;

UPDATE core.core_water_polygons AS w
SET water_class_id = c.id
FROM _m156_resolve r
JOIN ref.ref_water_classes c ON c.code = r.resolved_code
WHERE r.entity_table = 'core.core_water_polygons'
  AND w.id = r.id
  AND w.water_class_id IS DISTINCT FROM c.id;

-- ---------------------------------------------------------------------------
-- 4) Lineage backfill (stable codes/versions only)
-- ---------------------------------------------------------------------------
WITH raw AS (
  SELECT
    'lines'::text AS kind,
    w.id,
    nullif(btrim(w.source_refs ->> 'osm_id'), '') AS osm_id_text,
    lower(nullif(btrim(w.source_refs ->> 'osm_feature_type'), '')) AS osm_ft,
    nullif(btrim(w.source_refs ->> 'region_code'), '') AS region_code,
    coalesce(
      nullif(btrim(w.source_refs ->> 'source_snapshot_version'), ''),
      nullif(btrim(w.source_refs ->> 'snapshot_version'), '')
    ) AS snapshot_version,
    nullif(btrim(w.external_id), '') AS external_id
  FROM core.core_water_lines w
  UNION ALL
  SELECT
    'polygons',
    w.id,
    nullif(btrim(w.source_refs ->> 'osm_id'), ''),
    lower(nullif(btrim(w.source_refs ->> 'osm_feature_type'), '')),
    nullif(btrim(w.source_refs ->> 'region_code'), ''),
    coalesce(
      nullif(btrim(w.source_refs ->> 'source_snapshot_version'), ''),
      nullif(btrim(w.source_refs ->> 'snapshot_version'), '')
    ),
    nullif(btrim(w.external_id), '')
  FROM core.core_water_polygons w
),
parsed AS (
  SELECT
    r.*,
    CASE
      WHEN r.osm_id_text ~ '^[1-9][0-9]*$'
        OR r.external_id ~* '^osm:(way|relation|node|w|r|n):'
        THEN 'osm_myanmar'
      ELSE NULL
    END AS source_code,
    CASE
      WHEN r.osm_ft IN ('w','way') THEN 'way'
      WHEN r.osm_ft IN ('r','rel','relation') THEN 'relation'
      WHEN r.osm_ft IN ('n','node') THEN 'node'
      WHEN r.external_id ~* '^osm:(way|w):' THEN 'way'
      WHEN r.external_id ~* '^osm:(relation|r):' THEN 'relation'
      WHEN r.external_id ~* '^osm:(node|n):' THEN 'node'
      ELSE NULL
    END AS source_feature_type,
    CASE
      WHEN r.osm_id_text ~ '^[1-9][0-9]*$'
       AND r.osm_id_text::numeric <= 9223372036854775807::numeric
        THEN r.osm_id_text::bigint
      WHEN r.external_id ~* '^osm:(way|relation|node|w|r|n):([1-9][0-9]*)$'
        THEN (regexp_match(r.external_id, '([1-9][0-9]*)$'))[1]::bigint
      ELSE NULL
    END AS source_feature_id,
    lower(nullif(btrim(r.region_code), '')) AS region_norm
  FROM raw r
)
UPDATE core.core_water_lines AS w
SET
  source_registry_id = COALESCE(w.source_registry_id, reg.id),
  source_snapshot_id = COALESCE(w.source_snapshot_id, snap.id),
  source_feature_type = COALESCE(w.source_feature_type, p.source_feature_type),
  source_feature_id = COALESCE(w.source_feature_id, p.source_feature_id),
  region_code = COALESCE(w.region_code, p.region_norm)
FROM parsed p
LEFT JOIN system.system_source_registry reg
  ON reg.source_code = p.source_code AND reg.is_active IS TRUE
LEFT JOIN system.system_source_snapshots snap
  ON snap.source_registry_id = reg.id
 AND snap.snapshot_version = p.snapshot_version
WHERE p.kind = 'lines' AND w.id = p.id;

WITH raw AS (
  SELECT
    w.id,
    nullif(btrim(w.source_refs ->> 'osm_id'), '') AS osm_id_text,
    lower(nullif(btrim(w.source_refs ->> 'osm_feature_type'), '')) AS osm_ft,
    nullif(btrim(w.source_refs ->> 'region_code'), '') AS region_code,
    coalesce(
      nullif(btrim(w.source_refs ->> 'source_snapshot_version'), ''),
      nullif(btrim(w.source_refs ->> 'snapshot_version'), '')
    ) AS snapshot_version,
    nullif(btrim(w.external_id), '') AS external_id
  FROM core.core_water_polygons w
),
parsed AS (
  SELECT
    r.*,
    CASE
      WHEN r.osm_id_text ~ '^[1-9][0-9]*$'
        OR r.external_id ~* '^osm:(way|relation|w|r):'
        THEN 'osm_myanmar'
      ELSE NULL
    END AS source_code,
    CASE
      WHEN r.osm_ft IN ('w','way') THEN 'way'
      WHEN r.osm_ft IN ('r','rel','relation') THEN 'relation'
      WHEN r.external_id ~* '^osm:(way|w):' THEN 'way'
      WHEN r.external_id ~* '^osm:(relation|r):' THEN 'relation'
      ELSE NULL
    END AS source_feature_type,
    CASE
      WHEN r.osm_id_text ~ '^[1-9][0-9]*$'
       AND r.osm_id_text::numeric <= 9223372036854775807::numeric
        THEN r.osm_id_text::bigint
      WHEN r.external_id ~* '^osm:(way|relation|w|r):([1-9][0-9]*)$'
        THEN (regexp_match(r.external_id, '([1-9][0-9]*)$'))[1]::bigint
      ELSE NULL
    END AS source_feature_id,
    lower(nullif(btrim(r.region_code), '')) AS region_norm
  FROM raw r
)
UPDATE core.core_water_polygons AS w
SET
  source_registry_id = COALESCE(w.source_registry_id, reg.id),
  source_snapshot_id = COALESCE(w.source_snapshot_id, snap.id),
  source_feature_type = COALESCE(w.source_feature_type, p.source_feature_type),
  source_feature_id = COALESCE(w.source_feature_id, p.source_feature_id),
  region_code = COALESCE(w.region_code, p.region_norm)
FROM parsed p
LEFT JOIN system.system_source_registry reg
  ON reg.source_code = p.source_code AND reg.is_active IS TRUE
LEFT JOIN system.system_source_snapshots snap
  ON snap.source_registry_id = reg.id
 AND snap.snapshot_version = p.snapshot_version
WHERE w.id = p.id;

ALTER TABLE core.core_water_lines VALIDATE CONSTRAINT core_water_lines_water_class_id_fkey;
ALTER TABLE core.core_water_polygons VALIDATE CONSTRAINT core_water_polygons_water_class_id_fkey;
ALTER TABLE import_review.water_line_candidates VALIDATE CONSTRAINT irr_wl_water_class_id_fkey;
ALTER TABLE import_review.water_polygon_candidates VALIDATE CONSTRAINT irr_wp_water_class_id_fkey;
ALTER TABLE core.core_water_lines VALIDATE CONSTRAINT core_water_lines_source_registry_id_fkey;
ALTER TABLE core.core_water_lines VALIDATE CONSTRAINT core_water_lines_source_snapshot_id_fkey;
ALTER TABLE core.core_water_lines VALIDATE CONSTRAINT core_water_lines_source_feature_type_chk;
ALTER TABLE core.core_water_polygons VALIDATE CONSTRAINT core_water_polygons_source_registry_id_fkey;
ALTER TABLE core.core_water_polygons VALIDATE CONSTRAINT core_water_polygons_source_snapshot_id_fkey;
ALTER TABLE core.core_water_polygons VALIDATE CONSTRAINT core_water_polygons_source_feature_type_chk;

CREATE UNIQUE INDEX IF NOT EXISTS core_water_lines_source_identity_uidx
  ON core.core_water_lines (source_registry_id, source_feature_type, source_feature_id)
  WHERE source_registry_id IS NOT NULL AND source_feature_type IS NOT NULL AND source_feature_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS core_water_polygons_source_identity_uidx
  ON core.core_water_polygons (source_registry_id, source_feature_type, source_feature_id)
  WHERE source_registry_id IS NOT NULL AND source_feature_type IS NOT NULL AND source_feature_id IS NOT NULL;

COMMENT ON COLUMN core.core_water_lines.water_class_id IS
  'Authoritative water class → ref.ref_water_classes.id';
COMMENT ON COLUMN core.core_water_polygons.water_class_id IS
  'Authoritative water class → ref.ref_water_classes.id';
COMMENT ON COLUMN core.core_water_lines.class_code IS
  'DEPRECATED as authoritative. Prefer water_class_id. Kept temporarily for compatibility.';
COMMENT ON COLUMN core.core_water_polygons.class_code IS
  'DEPRECATED as authoritative. Prefer water_class_id. Kept temporarily for compatibility.';

-- ---------------------------------------------------------------------------
-- 5) Tile views — keep source-layer names; expose ref labels
-- ---------------------------------------------------------------------------
-- DROP required: CREATE OR REPLACE cannot insert columns before geom.
DROP VIEW IF EXISTS tiles.tiles_water_lines_v;
CREATE VIEW tiles.tiles_water_lines_v AS
SELECT
  w.id,
  w.name,
  coalesce(wc.code, w.class_code) AS waterway_class,
  wc.code AS water_class_code,
  wc.name_en AS water_class_name_en,
  wc.name_mm AS water_class_name_mm,
  w.geom
FROM core.core_water_lines AS w
LEFT JOIN ref.ref_water_classes AS wc ON wc.id = w.water_class_id
WHERE w.is_active IS TRUE
  AND w.deleted_at IS NULL
  AND w.geom IS NOT NULL
  AND NOT st_isempty(w.geom);

COMMENT ON VIEW tiles.tiles_water_lines_v IS
  'Water lines MVT. Source-layer tiles_water_lines_v unchanged. Class from water_class_id + ref.';

DROP VIEW IF EXISTS tiles.tiles_water_polygons_v;
CREATE VIEW tiles.tiles_water_polygons_v AS
SELECT
  w.id,
  w.name,
  coalesce(wc.code, w.class_code) AS water_class,
  wc.code AS water_class_code,
  wc.name_en AS water_class_name_en,
  wc.name_mm AS water_class_name_mm,
  w.geom
FROM core.core_water_polygons AS w
LEFT JOIN ref.ref_water_classes AS wc ON wc.id = w.water_class_id
WHERE w.is_active IS TRUE
  AND w.deleted_at IS NULL
  AND w.geom IS NOT NULL
  AND NOT st_isempty(w.geom);

COMMENT ON VIEW tiles.tiles_water_polygons_v IS
  'Water polygons MVT. Source-layer tiles_water_polygons_v unchanged. Class from water_class_id + ref.';

REVOKE ALL ON TABLE tiles.tiles_water_lines_v FROM PUBLIC;
REVOKE ALL ON TABLE tiles.tiles_water_polygons_v FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- 6) Search views — category from ref
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS search.v_search_water_lines_source;
CREATE VIEW search.v_search_water_lines_source AS
SELECT
  'water_line'::text AS entity_type,
  w.id AS entity_id,
  NULL::text AS public_id,
  COALESCE(nm.name_en, nm.name_my, w.name) AS display_name,
  COALESCE(wc.name_en, NULLIF(btrim(w.class_code), ''), 'Waterway') AS subtitle,
  COALESCE(nm.name_my, w.name) AS primary_name_my,
  COALESCE(nm.name_en, w.name) AS primary_name_en,
  w.name AS primary_name_und,
  COALESCE(wc.code, w.class_code) AS code,
  w.external_id,
  COALESCE(wc.code, w.class_code) AS category_code,
  wc.name_mm AS category_name_my,
  wc.name_en AS category_name_en,
  NULL::bigint AS admin_area_id,
  NULL::text AS admin_area_name_my,
  NULL::text AS admin_area_name_en,
  '{}'::jsonb AS admin_hierarchy,
  NULL::text AS address_text,
  NULL::jsonb AS address_parts,
  geometrytype(w.geom) AS geometry_type,
  search.safe_centroid(w.geom) AS centroid,
  search.safe_bbox(w.geom) AS bbox,
  search.safe_centroid(w.geom) IS NOT NULL AS has_geometry,
  search.safe_centroid(w.geom) IS NOT NULL AS supports_plus_code,
  concat_ws(' ', w.name, nm.all_names, wc.name_en, wc.name_mm, wc.code, w.class_code) AS searchable_text,
  0::numeric AS importance_score,
  0::numeric AS popularity_score,
  0::numeric AS confidence_score,
  0::numeric AS boundary_confidence_score,
  COALESCE(w.is_verified, false) AS is_verified,
  true AS is_public,
  COALESCE(w.is_active, false) AS is_active,
  w.updated_at AS source_updated_at,
  COALESCE(nm.names_json, '[]'::jsonb) AS names
FROM core.core_water_lines w
LEFT JOIN ref.ref_water_classes wc ON wc.id = w.water_class_id
LEFT JOIN LATERAL (
  SELECT
    (SELECT x.name FROM core.core_water_line_names x
      WHERE x.water_line_id = w.id
        AND (x.language_code = 'my' OR upper(trim(coalesce(x.script_code, ''))) = 'MYMR')
      ORDER BY CASE WHEN x.name_type = 'official' AND x.is_primary THEN 1
                    WHEN x.is_primary THEN 2
                    WHEN x.name_type = 'official' THEN 3 ELSE 4 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_my,
    (SELECT x.name FROM core.core_water_line_names x
      WHERE x.water_line_id = w.id
        AND (x.language_code = 'en' OR upper(trim(coalesce(x.script_code, ''))) = 'LATN')
      ORDER BY CASE WHEN x.name_type = 'official' AND x.is_primary THEN 1
                    WHEN x.is_primary THEN 2
                    WHEN x.name_type = 'official' THEN 3 ELSE 4 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_en,
    (SELECT jsonb_agg(jsonb_build_object(
              'name', x.name, 'language_code', x.language_code,
              'script_code', x.script_code, 'name_type', x.name_type,
              'is_primary', x.is_primary, 'search_weight', coalesce(x.search_weight, 0))
              ORDER BY x.is_primary DESC, x.name)
      FROM core.core_water_line_names x WHERE x.water_line_id = w.id) AS names_json,
    (SELECT string_agg(DISTINCT x.name, ' ')
      FROM core.core_water_line_names x WHERE x.water_line_id = w.id) AS all_names
) nm ON true
WHERE w.deleted_at IS NULL
  AND w.is_active = true
  AND w.geom IS NOT NULL
  AND NOT st_isempty(w.geom)
  AND (
    nullif(btrim(w.name), '') IS NOT NULL
    OR EXISTS (SELECT 1 FROM core.core_water_line_names x WHERE x.water_line_id = w.id)
  );

DROP VIEW IF EXISTS search.v_search_water_polygons_source;
CREATE VIEW search.v_search_water_polygons_source AS
SELECT
  'water_polygon'::text AS entity_type,
  w.id AS entity_id,
  NULL::text AS public_id,
  COALESCE(nm.name_en, nm.name_my, w.name) AS display_name,
  COALESCE(wc.name_en, NULLIF(btrim(w.class_code), ''), 'Water') AS subtitle,
  COALESCE(nm.name_my, w.name) AS primary_name_my,
  COALESCE(nm.name_en, w.name) AS primary_name_en,
  w.name AS primary_name_und,
  COALESCE(wc.code, w.class_code) AS code,
  w.external_id,
  COALESCE(wc.code, w.class_code) AS category_code,
  wc.name_mm AS category_name_my,
  wc.name_en AS category_name_en,
  NULL::bigint AS admin_area_id,
  NULL::text AS admin_area_name_my,
  NULL::text AS admin_area_name_en,
  '{}'::jsonb AS admin_hierarchy,
  NULL::text AS address_text,
  NULL::jsonb AS address_parts,
  geometrytype(w.geom) AS geometry_type,
  search.safe_centroid(w.geom) AS centroid,
  search.safe_bbox(w.geom) AS bbox,
  search.safe_centroid(w.geom) IS NOT NULL AS has_geometry,
  search.safe_centroid(w.geom) IS NOT NULL AS supports_plus_code,
  concat_ws(' ', w.name, nm.all_names, wc.name_en, wc.name_mm, wc.code, w.class_code) AS searchable_text,
  0::numeric AS importance_score,
  0::numeric AS popularity_score,
  0::numeric AS confidence_score,
  0::numeric AS boundary_confidence_score,
  COALESCE(w.is_verified, false) AS is_verified,
  true AS is_public,
  COALESCE(w.is_active, false) AS is_active,
  w.updated_at AS source_updated_at,
  COALESCE(nm.names_json, '[]'::jsonb) AS names
FROM core.core_water_polygons w
LEFT JOIN ref.ref_water_classes wc ON wc.id = w.water_class_id
LEFT JOIN LATERAL (
  SELECT
    (SELECT x.name FROM core.core_water_polygon_names x
      WHERE x.water_polygon_id = w.id
        AND (x.language_code = 'my' OR upper(trim(coalesce(x.script_code, ''))) = 'MYMR')
      ORDER BY CASE WHEN x.name_type = 'official' AND x.is_primary THEN 1
                    WHEN x.is_primary THEN 2
                    WHEN x.name_type = 'official' THEN 3 ELSE 4 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_my,
    (SELECT x.name FROM core.core_water_polygon_names x
      WHERE x.water_polygon_id = w.id
        AND (x.language_code = 'en' OR upper(trim(coalesce(x.script_code, ''))) = 'LATN')
      ORDER BY CASE WHEN x.name_type = 'official' AND x.is_primary THEN 1
                    WHEN x.is_primary THEN 2
                    WHEN x.name_type = 'official' THEN 3 ELSE 4 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_en,
    (SELECT jsonb_agg(jsonb_build_object(
              'name', x.name, 'language_code', x.language_code,
              'script_code', x.script_code, 'name_type', x.name_type,
              'is_primary', x.is_primary, 'search_weight', coalesce(x.search_weight, 0))
              ORDER BY x.is_primary DESC, x.name)
      FROM core.core_water_polygon_names x WHERE x.water_polygon_id = w.id) AS names_json,
    (SELECT string_agg(DISTINCT x.name, ' ')
      FROM core.core_water_polygon_names x WHERE x.water_polygon_id = w.id) AS all_names
) nm ON true
WHERE w.deleted_at IS NULL
  AND w.is_active = true
  AND w.geom IS NOT NULL
  AND NOT st_isempty(w.geom)
  AND (
    nullif(btrim(w.name), '') IS NOT NULL
    OR EXISTS (SELECT 1 FROM core.core_water_polygon_names x WHERE x.water_polygon_id = w.id)
  );

COMMENT ON VIEW search.v_search_water_lines_source IS
  'Search source for water lines; category from ref.ref_water_classes via water_class_id.';
COMMENT ON VIEW search.v_search_water_polygons_source IS
  'Search source for water polygons; category from ref.ref_water_classes via water_class_id.';

-- ---------------------------------------------------------------------------
-- 7) Assertions + anomaly summary notice
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  b record;
  after_lines bigint;
  after_polygons bigint;
  after_line_names bigint;
  after_poly_names bigint;
  null_class_lines bigint;
  null_class_polys bigint;
  orphan_lines bigint;
  orphan_polys bigint;
  anomaly_total bigint;
  anomaly_other bigint;
BEGIN
  SELECT * INTO b FROM _m156_before;
  SELECT count(*) INTO after_lines FROM core.core_water_lines;
  SELECT count(*) INTO after_polygons FROM core.core_water_polygons;
  SELECT count(*) INTO after_line_names FROM core.core_water_line_names;
  SELECT count(*) INTO after_poly_names FROM core.core_water_polygon_names;

  IF b.water_lines IS DISTINCT FROM after_lines THEN
    RAISE EXCEPTION '156: water_lines count changed % → %', b.water_lines, after_lines;
  END IF;
  IF b.water_polygons IS DISTINCT FROM after_polygons THEN
    RAISE EXCEPTION '156: water_polygons count changed % → %', b.water_polygons, after_polygons;
  END IF;
  IF b.water_line_names IS DISTINCT FROM after_line_names THEN
    RAISE EXCEPTION '156: water_line_names count changed';
  END IF;
  IF b.water_polygon_names IS DISTINCT FROM after_poly_names THEN
    RAISE EXCEPTION '156: water_polygon_names count changed';
  END IF;

  SELECT count(*) INTO null_class_lines FROM core.core_water_lines WHERE water_class_id IS NULL;
  SELECT count(*) INTO null_class_polys FROM core.core_water_polygons WHERE water_class_id IS NULL;
  IF null_class_lines > 0 OR null_class_polys > 0 THEN
    RAISE EXCEPTION '156: null water_class_id lines=% polygons=%', null_class_lines, null_class_polys;
  END IF;

  SELECT count(*) INTO orphan_lines
  FROM core.core_water_lines w
  LEFT JOIN ref.ref_water_classes c ON c.id = w.water_class_id
  WHERE c.id IS NULL;
  SELECT count(*) INTO orphan_polys
  FROM core.core_water_polygons w
  LEFT JOIN ref.ref_water_classes c ON c.id = w.water_class_id
  WHERE c.id IS NULL;
  IF orphan_lines > 0 OR orphan_polys > 0 THEN
    RAISE EXCEPTION '156: orphan water_class_id lines=% polygons=%', orphan_lines, orphan_polys;
  END IF;

  SELECT count(*) INTO anomaly_total FROM system.migration_156_water_class_anomalies;
  SELECT count(*) INTO anomaly_other
  FROM system.migration_156_water_class_anomalies WHERE resolved_code = 'other';

  RAISE NOTICE '156 anomaly rows=% (resolved_other=%). See system.migration_156_water_class_anomalies',
    anomaly_total, anomaly_other;
END $$;

COMMIT;
