-- =============================================================================
-- Supabase migration 157: core.core_coastlines (Myanmar coastline storage)
-- =============================================================================
--
-- Scope:
--   * Create ONLY core.core_coastlines for processed/versioned coastline
--     MultiLineString geometry (land/sea boundary).
--   * Buildings-style source lineage (registry + snapshot + region_code).
--   * Replacement semantics: one active coastline per region scope.
--   * Tile export view tiles.tiles_coastlines_v (no production tile rebuild).
--
-- Does NOT:
--   * import coastline data
--   * create ref_coastline_classes / names / ocean / landmask tables
--   * treat every OSM coastline way as an application entity
--   * rebuild PMTiles
-- =============================================================================

BEGIN;

SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '5min';

-- ---------------------------------------------------------------------------
-- 1) Table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.core_coastlines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),
  geom geometry(MultiLineString, 4326) NOT NULL,
  region_code text NULL,
  source_registry_id bigint NULL,
  source_snapshot_id bigint NULL,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT core_coastlines_public_id_key UNIQUE (public_id),
  CONSTRAINT core_coastlines_geom_srid_chk CHECK (ST_SRID(geom) = 4326),
  CONSTRAINT core_coastlines_geom_not_empty_chk CHECK (NOT ST_IsEmpty(geom)),
  CONSTRAINT core_coastlines_source_registry_id_fkey
    FOREIGN KEY (source_registry_id) REFERENCES system.system_source_registry (id),
  CONSTRAINT core_coastlines_source_snapshot_id_fkey
    FOREIGN KEY (source_snapshot_id) REFERENCES system.system_source_snapshots (id)
);

COMMENT ON TABLE core.core_coastlines IS
  'Processed/versioned Myanmar coastline MultiLineString (land/sea boundary). '
  'Not an OSM way dump. Derived land/ocean masks belong in tile processing, not Core entity tables.';

COMMENT ON COLUMN core.core_coastlines.geom IS
  'Authoritative coastline geometry as MultiLineString 4326.';
COMMENT ON COLUMN core.core_coastlines.region_code IS
  'Scope key for active replacement. NULL means national Myanmar coastline.';
COMMENT ON COLUMN core.core_coastlines.source_registry_id IS
  'FK → system.system_source_registry (e.g. osm_myanmar or natural_earth).';
COMMENT ON COLUMN core.core_coastlines.source_snapshot_id IS
  'FK → system.system_source_snapshots for the coastline build version.';
COMMENT ON COLUMN core.core_coastlines.source_refs IS
  'Opaque lineage JSON (loader, checksum notes, etc). Keep OSM tags here if needed.';
COMMENT ON COLUMN core.core_coastlines.is_active IS
  'Only active rows are exported to tiles. Replacement deactivates prior active rows for the same region scope.';

-- ---------------------------------------------------------------------------
-- 2) Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS core_coastlines_geom_gix
  ON core.core_coastlines USING GIST (geom);

CREATE INDEX IF NOT EXISTS core_coastlines_is_active_idx
  ON core.core_coastlines (is_active)
  WHERE is_active IS TRUE;

CREATE INDEX IF NOT EXISTS core_coastlines_source_snapshot_id_idx
  ON core.core_coastlines (source_snapshot_id)
  WHERE source_snapshot_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_coastlines_source_registry_id_idx
  ON core.core_coastlines (source_registry_id)
  WHERE source_registry_id IS NOT NULL;

-- One active coastline dataset per region scope (NULL region_code = national).
CREATE UNIQUE INDEX IF NOT EXISTS core_coastlines_one_active_per_region_uidx
  ON core.core_coastlines ((COALESCE(lower(btrim(region_code)), 'national')))
  WHERE is_active IS TRUE;

-- ---------------------------------------------------------------------------
-- 3) Replacement helper (no data import)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.replace_active_coastline(
  p_geom geometry,
  p_region_code text DEFAULT NULL,
  p_source_registry_id bigint DEFAULT NULL,
  p_source_snapshot_id bigint DEFAULT NULL,
  p_source_refs jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  coastline_id bigint,
  coastline_public_id uuid,
  deactivated_count bigint
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_scope text := COALESCE(lower(nullif(btrim(p_region_code), '')), 'national');
  v_region text := nullif(btrim(p_region_code), '');
  v_geom geometry(MultiLineString, 4326);
  v_deactivated bigint := 0;
  v_id bigint;
  v_public_id uuid;
BEGIN
  IF p_geom IS NULL OR ST_IsEmpty(p_geom) THEN
    RAISE EXCEPTION 'replace_active_coastline: geom is required and must be non-empty';
  END IF;

  -- Normalize to MultiLineString 4326.
  v_geom := ST_Multi(
    ST_CollectionExtract(
      CASE
        WHEN ST_SRID(p_geom) = 0 THEN ST_SetSRID(p_geom, 4326)
        WHEN ST_SRID(p_geom) = 4326 THEN p_geom
        ELSE ST_Transform(p_geom, 4326)
      END,
      2
    )
  )::geometry(MultiLineString, 4326);

  IF v_geom IS NULL OR ST_IsEmpty(v_geom) THEN
    RAISE EXCEPTION 'replace_active_coastline: geom must contain linework (got %)', GeometryType(p_geom);
  END IF;

  IF p_source_snapshot_id IS NOT NULL AND p_source_registry_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1
      FROM system.system_source_snapshots s
      WHERE s.id = p_source_snapshot_id
        AND s.source_registry_id = p_source_registry_id
    ) THEN
      RAISE EXCEPTION
        'replace_active_coastline: source_snapshot_id=% does not belong to source_registry_id=%',
        p_source_snapshot_id, p_source_registry_id;
    END IF;
  END IF;

  UPDATE core.core_coastlines AS c
  SET
    is_active = false,
    updated_at = now()
  WHERE c.is_active IS TRUE
    AND COALESCE(lower(btrim(c.region_code)), 'national') = v_scope;

  GET DIAGNOSTICS v_deactivated = ROW_COUNT;

  INSERT INTO core.core_coastlines (
    geom,
    region_code,
    source_registry_id,
    source_snapshot_id,
    source_refs,
    is_active
  )
  VALUES (
    v_geom,
    v_region,
    p_source_registry_id,
    p_source_snapshot_id,
    COALESCE(p_source_refs, '{}'::jsonb),
    true
  )
  RETURNING id, public_id INTO v_id, v_public_id;

  coastline_id := v_id;
  coastline_public_id := v_public_id;
  deactivated_count := v_deactivated;
  RETURN NEXT;
END;
$$;

COMMENT ON FUNCTION core.replace_active_coastline(geometry, text, bigint, bigint, jsonb) IS
  'Deactivate the prior active coastline for the same region scope, then insert a new active row. '
  'NULL region_code = national. Does not delete history.';

-- ---------------------------------------------------------------------------
-- 4) Tile export view (plumbing only — no tile rebuild)
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS tiles.tiles_coastlines_v;
CREATE VIEW tiles.tiles_coastlines_v AS
SELECT
  c.id,
  c.public_id,
  c.region_code,
  c.source_snapshot_id,
  c.geom
FROM core.core_coastlines AS c
WHERE c.is_active IS TRUE
  AND c.geom IS NOT NULL
  AND NOT ST_IsEmpty(c.geom);

COMMENT ON VIEW tiles.tiles_coastlines_v IS
  'Coastline MVT export from core.core_coastlines. Source-layer name tiles_coastlines_v. '
  'Overview PMTiles may still use Natural Earth until a Core-backed rebuild is scheduled.';

REVOKE ALL ON TABLE tiles.tiles_coastlines_v FROM PUBLIC;

COMMIT;
