-- =============================================================================
-- Supabase migration 160: protected-area overlay (schema only)
-- =============================================================================
--
-- Protected areas are a legal/management overlay — NOT land cover and NOT
-- ordinary parks. They may overlap forest, wetland, grassland, water, etc.
--
-- Creates:
--   ref.ref_protected_area_classes
--   core.core_protected_areas
--   core.core_protected_area_names
--   import_review.protected_area_candidates
--   tiles.tiles_protected_areas_v
--   search.v_search_protected_areas_source  (named active only)
--
-- Does NOT:
--   import national protected-area OSM data
--   migrate existing nature_reserve / park rows out of core_land_areas
--   rebuild PMTiles / wire search rebuild defaults
--   create separate national_park / nature_reserve / forest_reserve tables
-- =============================================================================

BEGIN;

SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '5min';

-- ---------------------------------------------------------------------------
-- 0) Baseline: land areas must remain untouched
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE _m160_before ON COMMIT DROP AS
SELECT
  (SELECT count(*)::bigint FROM core.core_land_areas) AS land_areas,
  (SELECT count(*)::bigint FROM core.core_land_area_names) AS land_area_names;

-- ---------------------------------------------------------------------------
-- 1) Reference taxonomy (seed by CODE)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref.ref_protected_area_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name_en text NOT NULL,
  name_mm text NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_public boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_protected_area_classes_code_key UNIQUE (code),
  CONSTRAINT ref_protected_area_classes_code_chk CHECK (btrim(code) <> ''),
  CONSTRAINT ref_protected_area_classes_name_en_chk CHECK (btrim(name_en) <> '')
);

COMMENT ON TABLE ref.ref_protected_area_classes IS
  'CoreMap protected-area overlay classes. OSM protect_class/designation remain raw source attributes.';

INSERT INTO ref.ref_protected_area_classes AS c (
  code, name_en, name_mm, sort_order, is_public, is_active
)
VALUES
  ('national_park', 'National Park', 'အမျိုးသားဥယျာဉ်', 10, true, true),
  ('nature_reserve', 'Nature Reserve', 'သဘာဝထိန်းသိမ်းရေးနယ်မြေ', 20, true, true),
  ('wildlife_protected_area', 'Wildlife Protected Area', 'တောရိုင်းတိရစ္ဆာန်ကာကွယ်ရေးနယ်မြေ', 30, true, true),
  ('forest_reserve', 'Forest Reserve', 'သစ်တောကြိုးဝိုင်း', 40, true, true),
  ('marine_protected_area', 'Marine Protected Area', 'ပင်လယ်ကာကွယ်ရေးနယ်မြေ', 50, true, true),
  ('other', 'Other Protected Area', 'အခြားကာကွယ်ရေးနယ်မြေ', 90, true, true)
ON CONFLICT (code) DO UPDATE
SET
  name_en = EXCLUDED.name_en,
  name_mm = COALESCE(EXCLUDED.name_mm, c.name_mm),
  sort_order = EXCLUDED.sort_order,
  is_public = EXCLUDED.is_public,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- ---------------------------------------------------------------------------
-- 2) Core geometry table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.core_protected_areas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  protected_area_class_id bigint NOT NULL,
  admin_area_id bigint NULL,

  geom geometry(MultiPolygon, 4326) NOT NULL,
  centroid geometry(Point, 4326) NULL,
  area_m2 numeric NULL,

  external_id text NULL,

  source_registry_id bigint NULL,
  source_snapshot_id bigint NULL,
  source_feature_type text NULL,
  source_feature_id bigint NULL,
  region_code text NULL,

  source_tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
  normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,

  confidence_score numeric NULL,

  is_verified boolean NOT NULL DEFAULT false,
  verification_status text NOT NULL DEFAULT 'unverified',
  verified_at timestamptz NULL,
  verified_by bigint NULL,
  verification_note text NULL,

  manual_override boolean NOT NULL DEFAULT false,

  is_active boolean NOT NULL DEFAULT true,
  deleted_at timestamptz NULL,

  created_by bigint NULL,
  updated_by bigint NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT core_protected_areas_public_id_key UNIQUE (public_id),
  CONSTRAINT core_protected_areas_protected_area_class_id_fkey
    FOREIGN KEY (protected_area_class_id) REFERENCES ref.ref_protected_area_classes (id),
  CONSTRAINT core_protected_areas_admin_area_id_fkey
    FOREIGN KEY (admin_area_id) REFERENCES core.core_admin_areas (id),
  CONSTRAINT core_protected_areas_source_registry_id_fkey
    FOREIGN KEY (source_registry_id) REFERENCES system.system_source_registry (id),
  CONSTRAINT core_protected_areas_source_snapshot_id_fkey
    FOREIGN KEY (source_snapshot_id) REFERENCES system.system_source_snapshots (id),
  CONSTRAINT core_protected_areas_geom_srid_chk CHECK (ST_SRID(geom) = 4326),
  CONSTRAINT core_protected_areas_geom_not_empty_chk CHECK (NOT ST_IsEmpty(geom)),
  CONSTRAINT core_protected_areas_centroid_srid_chk
    CHECK (centroid IS NULL OR ST_SRID(centroid) = 4326),
  CONSTRAINT core_protected_areas_external_id_chk
    CHECK (external_id IS NULL OR btrim(external_id) <> ''),
  CONSTRAINT core_protected_areas_confidence_score_chk
    CHECK (
      confidence_score IS NULL
      OR (confidence_score >= 0 AND confidence_score <= 100)
    ),
  CONSTRAINT core_protected_areas_source_feature_type_chk
    CHECK (
      source_feature_type IS NULL
      OR source_feature_type IN ('way', 'relation')
    ),
  CONSTRAINT core_protected_areas_verification_status_chk
    CHECK (
      verification_status = ANY (
        ARRAY[
          'unverified'::text,
          'verified'::text,
          'needs_fix'::text,
          'questionable'::text,
          'rejected_after_core_review'::text
        ]
      )
    )
);

COMMENT ON TABLE core.core_protected_areas IS
  'Protected-area overlay polygons (national park, nature reserve, forest reserve, etc.). '
  'Not land cover. Classification via protected_area_class_id → ref.ref_protected_area_classes.';

COMMENT ON COLUMN core.core_protected_areas.protected_area_class_id IS
  'Authoritative class FK → ref.ref_protected_area_classes.id.';
COMMENT ON COLUMN core.core_protected_areas.source_tags IS
  'Original OSM/source tags (protect_class, designation, protection_title, boundary, leisure, …).';
COMMENT ON COLUMN core.core_protected_areas.source_feature_type IS
  'OSM source type when known: way | relation.';
COMMENT ON COLUMN core.core_protected_areas.verification_status IS
  'Same convention as core.core_land_areas: unverified|verified|needs_fix|questionable|rejected_after_core_review.';

CREATE UNIQUE INDEX IF NOT EXISTS core_protected_areas_source_identity_uidx
  ON core.core_protected_areas (source_registry_id, source_feature_type, source_feature_id)
  WHERE source_registry_id IS NOT NULL
    AND source_feature_type IS NOT NULL
    AND source_feature_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_protected_areas_geom_gix
  ON core.core_protected_areas USING GIST (geom);

CREATE INDEX IF NOT EXISTS core_protected_areas_centroid_gix
  ON core.core_protected_areas USING GIST (centroid)
  WHERE centroid IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_protected_areas_protected_area_class_id_idx
  ON core.core_protected_areas (protected_area_class_id);

CREATE INDEX IF NOT EXISTS core_protected_areas_admin_area_id_idx
  ON core.core_protected_areas (admin_area_id)
  WHERE admin_area_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_protected_areas_source_registry_id_idx
  ON core.core_protected_areas (source_registry_id)
  WHERE source_registry_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_protected_areas_source_snapshot_id_idx
  ON core.core_protected_areas (source_snapshot_id)
  WHERE source_snapshot_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_protected_areas_region_code_idx
  ON core.core_protected_areas (region_code)
  WHERE region_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_protected_areas_is_active_deleted_at_idx
  ON core.core_protected_areas (is_active, deleted_at);

CREATE INDEX IF NOT EXISTS core_protected_areas_verification_status_idx
  ON core.core_protected_areas (verification_status);

-- ---------------------------------------------------------------------------
-- 3) Names (same pattern as core.core_land_area_names)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.core_protected_area_names (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protected_area_id bigint NOT NULL,
  name text NOT NULL,
  language_code text NOT NULL,
  script_code text NULL,
  name_type text NOT NULL DEFAULT 'official',
  is_primary boolean NOT NULL DEFAULT false,
  search_weight integer NOT NULL DEFAULT 50,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT core_protected_area_names_protected_area_id_fkey
    FOREIGN KEY (protected_area_id) REFERENCES core.core_protected_areas (id) ON DELETE CASCADE,
  CONSTRAINT core_protected_area_names_name_chk CHECK (btrim(name) <> ''),
  CONSTRAINT core_protected_area_names_language_code_chk
    CHECK (language_code = ANY (ARRAY['my'::text, 'en'::text, 'und'::text])),
  CONSTRAINT core_protected_area_names_script_code_chk
    CHECK (script_code IS NULL OR btrim(script_code) <> ''),
  CONSTRAINT core_protected_area_names_name_type_chk
    CHECK (
      name_type = ANY (
        ARRAY[
          'official'::text,
          'alternate'::text,
          'short'::text,
          'local'::text,
          'old'::text,
          'imported'::text,
          'generated'::text
        ]
      )
      AND btrim(name_type) <> ''
    ),
  CONSTRAINT core_protected_area_names_search_weight_chk
    CHECK (search_weight >= 0 AND search_weight <= 100)
);

COMMENT ON TABLE core.core_protected_area_names IS
  'Localized names for core.core_protected_areas. Language codes: my | en | und.';

CREATE INDEX IF NOT EXISTS core_protected_area_names_protected_area_id_idx
  ON core.core_protected_area_names (protected_area_id);

CREATE INDEX IF NOT EXISTS core_protected_area_names_language_code_idx
  ON core.core_protected_area_names (language_code);

CREATE INDEX IF NOT EXISTS core_protected_area_names_lower_name_idx
  ON core.core_protected_area_names (lower(name));

CREATE UNIQUE INDEX IF NOT EXISTS core_protected_area_names_one_primary_per_lang_type_uidx
  ON core.core_protected_area_names (protected_area_id, language_code, name_type)
  WHERE is_primary IS TRUE;

-- ---------------------------------------------------------------------------
-- 4) Import Review candidates (ambiguous / conflict path only)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS import_review.protected_area_candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),
  review_batch_id bigint NOT NULL
    REFERENCES import_review.review_batches (id) ON DELETE CASCADE,
  source_snapshot_version text NOT NULL,
  source_snapshot_id_local bigint NULL,
  local_staging_id bigint NOT NULL,
  entity_family text NOT NULL DEFAULT 'protected_areas',
  external_id text NULL,
  canonical_name text NULL,
  class_code text NULL,
  protected_area_class_id bigint NULL
    REFERENCES ref.ref_protected_area_classes (id),
  admin_area_id bigint NULL
    REFERENCES core.core_admin_areas (id),
  confidence_score numeric NULL,
  match_status text NULL,
  auto_action text NULL,
  review_status text NOT NULL DEFAULT 'pending',
  review_decision text NULL,
  review_note text NULL,
  reviewed_by bigint NULL,
  reviewed_at timestamptz NULL,
  assigned_to bigint NULL,
  locked_by bigint NULL,
  locked_at timestamptz NULL,
  lock_expires_at timestamptz NULL,
  normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
  review_overrides_archive jsonb NOT NULL DEFAULT '{}'::jsonb,
  matched_core_id bigint NULL,
  matched_core_table text NULL,
  matched_core_data jsonb NULL,
  f1_comparison jsonb NULL,
  f2_comparison jsonb NULL,
  validation_warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  promotion_status text NOT NULL DEFAULT 'not_ready',
  promoted_core_id bigint NULL,
  promoted_at timestamptz NULL,
  promoted_by bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  name text NULL,
  name_mm text NULL,
  name_en text NULL,
  geom geometry(Geometry, 4326),
  centroid geometry(Point, 4326),

  CONSTRAINT irr_pa_confidence_chk
    CHECK (
      confidence_score IS NULL
      OR (confidence_score >= 0 AND confidence_score <= 100)
    ),
  CONSTRAINT irr_pa_review_status_chk
    CHECK (
      review_status = ANY (
        ARRAY[
          'pending'::text,
          'approved'::text,
          'rejected'::text,
          'needs_review'::text,
          'ignored'::text,
          'merged'::text,
          'promoted'::text,
          'promotion_failed'::text
        ]
      )
    ),
  CONSTRAINT irr_pa_review_decision_chk
    CHECK (
      review_decision IS NULL
      OR review_decision = ANY (
        ARRAY[
          'approved'::text,
          'rejected'::text,
          'needs_more_review'::text,
          'ignored'::text,
          'merged'::text,
          'pending'::text,
          'keep_existing'::text,
          'replace_existing'::text,
          'merge_fields'::text,
          'insert_separate'::text,
          'ignore_import'::text,
          'mark_duplicate'::text,
          'confirm_soft_delete'::text
        ]
      )
    ),
  CONSTRAINT irr_pa_promotion_status_chk
    CHECK (
      promotion_status = ANY (
        ARRAY[
          'not_ready'::text,
          'ready'::text,
          'batched'::text,
          'promoting'::text,
          'promoted'::text,
          'failed'::text,
          'skipped'::text,
          'not_applied'::text,
          'applying'::text,
          'applied'::text
        ]
      )
    ),
  CONSTRAINT irr_pa_uniq_batch_lsid UNIQUE (review_batch_id, local_staging_id),
  CONSTRAINT irr_pa_uniq_snap_family_lsid
    UNIQUE (source_snapshot_version, entity_family, local_staging_id)
);

COMMENT ON TABLE import_review.protected_area_candidates IS
  'Import-review workspace for ambiguous/conflicting/invalid protected-area candidates. '
  'Clear OSM records should go direct-Core; do not dump all national protected areas here.';

COMMENT ON COLUMN import_review.protected_area_candidates.entity_family IS
  'Stable slug: protected_areas';

COMMENT ON COLUMN import_review.protected_area_candidates.protected_area_class_id IS
  'Resolved FK → ref.ref_protected_area_classes when known.';

DO $$
BEGIN
  IF to_regclass('app_auth.auth_users') IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'irr_pa_reviewed_by_fkey'
        AND conrelid = 'import_review.protected_area_candidates'::regclass
    ) THEN
      ALTER TABLE import_review.protected_area_candidates
        ADD CONSTRAINT irr_pa_reviewed_by_fkey
        FOREIGN KEY (reviewed_by) REFERENCES app_auth.auth_users (id);
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'irr_pa_assigned_to_fkey'
        AND conrelid = 'import_review.protected_area_candidates'::regclass
    ) THEN
      ALTER TABLE import_review.protected_area_candidates
        ADD CONSTRAINT irr_pa_assigned_to_fkey
        FOREIGN KEY (assigned_to) REFERENCES app_auth.auth_users (id);
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'irr_pa_locked_by_fkey'
        AND conrelid = 'import_review.protected_area_candidates'::regclass
    ) THEN
      ALTER TABLE import_review.protected_area_candidates
        ADD CONSTRAINT irr_pa_locked_by_fkey
        FOREIGN KEY (locked_by) REFERENCES app_auth.auth_users (id);
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'irr_pa_promoted_by_fkey'
        AND conrelid = 'import_review.protected_area_candidates'::regclass
    ) THEN
      ALTER TABLE import_review.protected_area_candidates
        ADD CONSTRAINT irr_pa_promoted_by_fkey
        FOREIGN KEY (promoted_by) REFERENCES app_auth.auth_users (id);
    END IF;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS irr_pa_rbid_idx
  ON import_review.protected_area_candidates (review_batch_id);
CREATE INDEX IF NOT EXISTS irr_pa_ssv_idx
  ON import_review.protected_area_candidates (source_snapshot_version);
CREATE INDEX IF NOT EXISTS irr_pa_lsid_idx
  ON import_review.protected_area_candidates (local_staging_id);
CREATE INDEX IF NOT EXISTS irr_pa_class_id_idx
  ON import_review.protected_area_candidates (protected_area_class_id)
  WHERE protected_area_class_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS irr_pa_rst_idx
  ON import_review.protected_area_candidates (review_status);
CREATE INDEX IF NOT EXISTS irr_pa_pstat_idx
  ON import_review.protected_area_candidates (promotion_status);
CREATE INDEX IF NOT EXISTS irr_pa_geom_gist_idx
  ON import_review.protected_area_candidates USING GIST (geom)
  WHERE geom IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5) Tile view (classification from ref FK; no PMTiles rebuild)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW tiles.tiles_protected_areas_v AS
SELECT
  p.id,
  p.public_id,
  pc.name_en AS protected_area_class,
  pc.code AS protected_area_class_code,
  COALESCE(nm.name_en, nm.name_my, nm.name_und) AS name,
  p.geom
FROM core.core_protected_areas AS p
INNER JOIN ref.ref_protected_area_classes AS pc
  ON pc.id = p.protected_area_class_id
LEFT JOIN LATERAL (
  SELECT
    (SELECT x.name FROM core.core_protected_area_names x
      WHERE x.protected_area_id = p.id
        AND x.language_code = 'en'
      ORDER BY CASE WHEN x.is_primary THEN 0 ELSE 1 END, x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_en,
    (SELECT x.name FROM core.core_protected_area_names x
      WHERE x.protected_area_id = p.id
        AND x.language_code = 'my'
      ORDER BY CASE WHEN x.is_primary THEN 0 ELSE 1 END, x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_my,
    (SELECT x.name FROM core.core_protected_area_names x
      WHERE x.protected_area_id = p.id
        AND x.language_code = 'und'
      ORDER BY CASE WHEN x.is_primary THEN 0 ELSE 1 END, x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_und
) nm ON true
WHERE p.is_active IS TRUE
  AND p.deleted_at IS NULL
  AND p.geom IS NOT NULL
  AND NOT ST_IsEmpty(p.geom);

COMMENT ON VIEW tiles.tiles_protected_areas_v IS
  'Protected-area overlay for MVT. Class from ref.ref_protected_area_classes via protected_area_class_id. '
  'Not wired into production PMTiles build yet.';

REVOKE ALL ON TABLE tiles.tiles_protected_areas_v FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- 6) Search source — named active rows only (not wired into rebuild defaults)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW search.v_search_protected_areas_source AS
SELECT
  'protected_area'::text AS entity_type,
  p.id AS entity_id,
  p.public_id::text AS public_id,
  COALESCE(nm.name_en, nm.name_my, nm.name_und, pc.name_en) AS display_name,
  pc.name_en AS subtitle,
  COALESCE(nm.name_my, nm.name_und) AS primary_name_my,
  COALESCE(nm.name_en, nm.name_und) AS primary_name_en,
  COALESCE(nm.name_und, nm.name_en, nm.name_my) AS primary_name_und,
  pc.code AS code,
  p.external_id,
  pc.code AS category_code,
  pc.name_mm AS category_name_my,
  pc.name_en AS category_name_en,
  p.admin_area_id,
  ctx.adm_my AS admin_area_name_my,
  ctx.adm_en AS admin_area_name_en,
  ctx.hierarchy AS admin_hierarchy,
  NULL::text AS address_text,
  NULL::jsonb AS address_parts,
  geometrytype(p.geom) AS geometry_type,
  COALESCE(p.centroid, search.safe_centroid(p.geom)) AS centroid,
  search.safe_bbox(p.geom) AS bbox,
  (COALESCE(p.centroid, search.safe_centroid(p.geom)) IS NOT NULL) AS has_geometry,
  (COALESCE(p.centroid, search.safe_centroid(p.geom)) IS NOT NULL) AS supports_plus_code,
  concat_ws(
    ' ',
    nm.all_names, pc.name_en, pc.name_mm, pc.code,
    ctx.adm_en, ctx.adm_my, search.hierarchy_text(ctx.hierarchy)
  ) AS searchable_text,
  0::numeric AS importance_score,
  0::numeric AS popularity_score,
  COALESCE(p.confidence_score, 0) AS confidence_score,
  0::numeric AS boundary_confidence_score,
  COALESCE(p.is_verified, false) AS is_verified,
  true AS is_public,
  COALESCE(p.is_active, false) AS is_active,
  p.updated_at AS source_updated_at,
  COALESCE(nm.names_json, '[]'::jsonb) AS names
FROM core.core_protected_areas AS p
INNER JOIN ref.ref_protected_area_classes AS pc
  ON pc.id = p.protected_area_class_id
LEFT JOIN LATERAL (
  SELECT
    search.admin_area_name(p.admin_area_id, 'my') AS adm_my,
    search.admin_area_name(p.admin_area_id, 'en') AS adm_en,
    search.admin_area_hierarchy(p.admin_area_id) AS hierarchy
) ctx ON true
LEFT JOIN LATERAL (
  SELECT
    (SELECT x.name FROM core.core_protected_area_names x
      WHERE x.protected_area_id = p.id
        AND (x.language_code = 'my' OR upper(trim(coalesce(x.script_code, ''))) = 'MYMR')
      ORDER BY CASE WHEN x.name_type = 'official' AND x.is_primary THEN 1
                    WHEN x.is_primary THEN 2
                    WHEN x.name_type = 'official' THEN 3 ELSE 4 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_my,
    (SELECT x.name FROM core.core_protected_area_names x
      WHERE x.protected_area_id = p.id
        AND (x.language_code = 'en' OR upper(trim(coalesce(x.script_code, ''))) = 'LATN')
      ORDER BY CASE WHEN x.name_type = 'official' AND x.is_primary THEN 1
                    WHEN x.is_primary THEN 2
                    WHEN x.name_type = 'official' THEN 3 ELSE 4 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_en,
    (SELECT x.name FROM core.core_protected_area_names x
      WHERE x.protected_area_id = p.id AND x.language_code = 'und'
      ORDER BY CASE WHEN x.is_primary THEN 1 ELSE 2 END,
               x.search_weight DESC NULLS LAST, x.name
      LIMIT 1) AS name_und,
    (SELECT jsonb_agg(jsonb_build_object(
              'name', x.name, 'language_code', x.language_code,
              'script_code', x.script_code, 'name_type', x.name_type,
              'is_primary', x.is_primary, 'search_weight', coalesce(x.search_weight, 0))
              ORDER BY x.is_primary DESC, x.name)
        FROM core.core_protected_area_names x
        WHERE x.protected_area_id = p.id) AS names_json,
    (SELECT string_agg(DISTINCT x.name, ' ')
        FROM core.core_protected_area_names x
        WHERE x.protected_area_id = p.id) AS all_names
) nm ON true
WHERE p.deleted_at IS NULL
  AND p.is_active IS TRUE
  AND p.geom IS NOT NULL
  AND NOT ST_IsEmpty(p.geom)
  AND EXISTS (
    SELECT 1
    FROM core.core_protected_area_names x
    WHERE x.protected_area_id = p.id
      AND nullif(btrim(x.name), '') IS NOT NULL
  );

COMMENT ON VIEW search.v_search_protected_areas_source IS
  'Search source for named active protected areas only (entity_type=protected_area). '
  'Not added to default search rebuild list in this migration.';

-- ---------------------------------------------------------------------------
-- 7) Assertions
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  before_land bigint;
  before_names bigint;
  after_land bigint;
  after_names bigint;
  class_count bigint;
  dup_code bigint;
  core_rows bigint;
  name_rows bigint;
  ir_rows bigint;
BEGIN
  SELECT land_areas, land_area_names INTO before_land, before_names FROM _m160_before;
  SELECT count(*) INTO after_land FROM core.core_land_areas;
  SELECT count(*) INTO after_names FROM core.core_land_area_names;

  IF after_land IS DISTINCT FROM before_land THEN
    RAISE EXCEPTION '160: core_land_areas count changed % → %', before_land, after_land;
  END IF;
  IF after_names IS DISTINCT FROM before_names THEN
    RAISE EXCEPTION '160: core_land_area_names count changed % → %', before_names, after_names;
  END IF;

  SELECT count(*) INTO class_count FROM ref.ref_protected_area_classes WHERE is_active;
  IF class_count < 6 THEN
    RAISE EXCEPTION '160: expected >=6 active protected area classes, got %', class_count;
  END IF;

  SELECT count(*) INTO dup_code
  FROM (
    SELECT lower(btrim(code)) FROM ref.ref_protected_area_classes GROUP BY 1 HAVING count(*) > 1
  ) d;
  IF dup_code <> 0 THEN
    RAISE EXCEPTION '160: duplicate protected area class codes = %', dup_code;
  END IF;

  IF to_regclass('core.core_protected_areas') IS NULL
     OR to_regclass('core.core_protected_area_names') IS NULL
     OR to_regclass('ref.ref_protected_area_classes') IS NULL
     OR to_regclass('import_review.protected_area_candidates') IS NULL
     OR to_regclass('tiles.tiles_protected_areas_v') IS NULL
     OR to_regclass('search.v_search_protected_areas_source') IS NULL THEN
    RAISE EXCEPTION '160: required objects missing';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ref.ref_protected_area_classes
    WHERE code IN (
      'national_park', 'nature_reserve', 'wildlife_protected_area',
      'forest_reserve', 'marine_protected_area', 'other'
    )
    HAVING count(*) = 6
  ) THEN
    RAISE EXCEPTION '160: required class codes missing';
  END IF;

  SELECT count(*) INTO core_rows FROM core.core_protected_areas;
  SELECT count(*) INTO name_rows FROM core.core_protected_area_names;
  SELECT count(*) INTO ir_rows FROM import_review.protected_area_candidates;
  IF core_rows <> 0 OR name_rows <> 0 OR ir_rows <> 0 THEN
    RAISE EXCEPTION '160: expected empty protected-area tables (no import yet); got core=% names=% ir=%',
      core_rows, name_rows, ir_rows;
  END IF;

  IF pg_get_viewdef('tiles.tiles_protected_areas_v'::regclass, true)
       NOT ILIKE '%ref.ref_protected_area_classes%' THEN
    RAISE EXCEPTION '160: tiles view does not join ref.ref_protected_area_classes';
  END IF;

  RAISE NOTICE '160 ok: land_areas=% classes=% (schema only, zero protected rows)',
    after_land, class_count;
END $$;

COMMIT;
