-- =============================================================================
-- Supabase migration 192: canonical settlement schema (empty tables only)
-- =============================================================================
--
-- Creates:
--   ref.ref_settlement_types  (city, town, village, local_area)
--   core.core_settlements     (point required; footprint optional)
--
-- Does NOT:
--   import OSM / pipeline data
--   move or delete core.core_places rows
--   change core.core_admin_areas
--   add search views, tile views, review tables, or version history
--
-- Apply: numbered supabase migration. Do not apply from chat/MCP.
-- =============================================================================

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '2min';

-- ---------------------------------------------------------------------------
-- 1) Canonical settlement types
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref.ref_settlement_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_settlement_types_code_key UNIQUE (code),
  CONSTRAINT ref_settlement_types_code_chk CHECK (btrim(code) <> ''),
  CONSTRAINT ref_settlement_types_name_chk CHECK (btrim(name) <> '')
);

COMMENT ON TABLE ref.ref_settlement_types IS
  'Canonical CoreMap settlement types. OSM hamlet/quarter/suburb/neighbourhood/locality stay source metadata, not extra type rows.';

COMMENT ON COLUMN ref.ref_settlement_types.code IS
  'Stable slug: city | town | village | local_area.';

INSERT INTO ref.ref_settlement_types (code, name, sort_order)
VALUES
  ('city', 'City', 10),
  ('town', 'Town', 20),
  ('village', 'Village', 30),
  ('local_area', 'Local area', 40)
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order;

-- ---------------------------------------------------------------------------
-- 2) Core settlements
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.core_settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  settlement_type_id bigint NOT NULL,
  canonical_name text NOT NULL,
  name_mm text NULL,
  name_en text NULL,

  point_geom geometry(Point, 4326) NOT NULL,
  footprint_geom geometry(MultiPolygon, 4326) NULL,

  township_id bigint NULL,
  population integer NULL,
  importance_score numeric NULL,

  external_id text NULL,
  source_type_id bigint NULL,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,

  is_public boolean NOT NULL DEFAULT true,
  is_verified boolean NOT NULL DEFAULT false,
  verification_status text NOT NULL DEFAULT 'unverified',
  verified_at timestamptz NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL,

  CONSTRAINT core_settlements_public_id_key UNIQUE (public_id),
  CONSTRAINT core_settlements_settlement_type_id_fkey
    FOREIGN KEY (settlement_type_id) REFERENCES ref.ref_settlement_types (id),
  CONSTRAINT core_settlements_township_id_fkey
    FOREIGN KEY (township_id) REFERENCES core.core_admin_areas (id),
  CONSTRAINT core_settlements_source_type_id_fkey
    FOREIGN KEY (source_type_id) REFERENCES ref.ref_source_types (id),
  CONSTRAINT core_settlements_canonical_name_chk
    CHECK (btrim(canonical_name) <> ''),
  CONSTRAINT core_settlements_name_mm_chk
    CHECK (name_mm IS NULL OR btrim(name_mm) <> ''),
  CONSTRAINT core_settlements_name_en_chk
    CHECK (name_en IS NULL OR btrim(name_en) <> ''),
  CONSTRAINT core_settlements_external_id_chk
    CHECK (external_id IS NULL OR btrim(external_id) <> ''),
  CONSTRAINT core_settlements_point_geom_srid_chk
    CHECK (ST_SRID(point_geom) = 4326),
  CONSTRAINT core_settlements_point_geom_not_empty_chk
    CHECK (NOT ST_IsEmpty(point_geom)),
  CONSTRAINT core_settlements_footprint_geom_srid_chk
    CHECK (footprint_geom IS NULL OR ST_SRID(footprint_geom) = 4326),
  CONSTRAINT core_settlements_footprint_geom_not_empty_chk
    CHECK (footprint_geom IS NULL OR NOT ST_IsEmpty(footprint_geom)),
  CONSTRAINT core_settlements_population_chk
    CHECK (population IS NULL OR population >= 0),
  CONSTRAINT core_settlements_importance_score_chk
    CHECK (
      importance_score IS NULL
      OR (importance_score >= 0 AND importance_score <= 100)
    ),
  CONSTRAINT core_settlements_verification_status_chk
    CHECK (
      verification_status = ANY (
        ARRAY[
          'unverified'::text,
          'verified'::text,
          'needs_fix'::text,
          'questionable'::text,
          'rejected_after_core_review'::text
        ]
      )
    )
);

COMMENT ON TABLE core.core_settlements IS
  'Canonical settlements (city, town, village, local_area). V1 requires point_geom; footprint_geom is optional for later field-observed polygons on the same row.';

COMMENT ON COLUMN core.core_settlements.public_id IS
  'Stable public UUID. Same convention as core.core_places and core.core_admin_areas.';
COMMENT ON COLUMN core.core_settlements.settlement_type_id IS
  'FK → ref.ref_settlement_types. Canonical types only.';
COMMENT ON COLUMN core.core_settlements.canonical_name IS
  'Primary display/search name. Not unique.';
COMMENT ON COLUMN core.core_settlements.name_mm IS
  'Optional Myanmar name stored on the row. Aliases stay out of this table.';
COMMENT ON COLUMN core.core_settlements.name_en IS
  'Optional English name stored on the row.';
COMMENT ON COLUMN core.core_settlements.point_geom IS
  'Required settlement point, SRID 4326. V1 geometry.';
COMMENT ON COLUMN core.core_settlements.footprint_geom IS
  'Optional MultiPolygon 4326. Null in V1. Later field polygons update this column; they do not create a new row.';
COMMENT ON COLUMN core.core_settlements.township_id IS
  'Optional FK to core.core_admin_areas. Must be an admin_level code township when set. Does not rewrite township rows.';
COMMENT ON COLUMN core.core_settlements.population IS
  'Optional non-negative population. Not a ranking score.';
COMMENT ON COLUMN core.core_settlements.importance_score IS
  'Optional 0-100 importance. Null until a later ranking pass.';
COMMENT ON COLUMN core.core_settlements.external_id IS
  'Optional source identity (for example OSM). Indexed, not unique.';
COMMENT ON COLUMN core.core_settlements.source_type_id IS
  'Optional FK → ref.ref_source_types. Same source architecture as other core tables.';
COMMENT ON COLUMN core.core_settlements.source_refs IS
  'Opaque source lineage JSON. OSM place=* extras (hamlet, quarter, suburb, neighbourhood, locality) belong here, not in ref types.';
COMMENT ON COLUMN core.core_settlements.is_public IS
  'Public map visibility. Same meaning as core.core_places.is_public.';
COMMENT ON COLUMN core.core_settlements.is_verified IS
  'Derived compatibility flag. True only when verification_status = verified.';
COMMENT ON COLUMN core.core_settlements.verification_status IS
  'Authoritative verification state. Same codes as core.core_places.';
COMMENT ON COLUMN core.core_settlements.deleted_at IS
  'Soft delete. Same convention as other core entity tables.';

CREATE INDEX IF NOT EXISTS core_settlements_point_geom_gix
  ON core.core_settlements USING GIST (point_geom);

CREATE INDEX IF NOT EXISTS core_settlements_footprint_geom_gix
  ON core.core_settlements USING GIST (footprint_geom)
  WHERE footprint_geom IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_settlements_settlement_type_id_idx
  ON core.core_settlements (settlement_type_id);

CREATE INDEX IF NOT EXISTS core_settlements_township_id_idx
  ON core.core_settlements (township_id)
  WHERE township_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_settlements_external_id_idx
  ON core.core_settlements (external_id)
  WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS core_settlements_source_type_id_idx
  ON core.core_settlements (source_type_id)
  WHERE source_type_id IS NOT NULL;

-- Township rows only. Does not change admin data.
CREATE OR REPLACE FUNCTION core.core_settlements_require_township_admin_area()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, core, ref
AS $$
BEGIN
  IF NEW.township_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM core.core_admin_areas AS aa
    INNER JOIN ref.ref_admin_levels AS al ON al.id = aa.admin_level_id
    WHERE aa.id = NEW.township_id
      AND lower(btrim(al.code)) = 'township'
  ) THEN
    RAISE EXCEPTION
      'core.core_settlements.township_id=% is not a township-level core.core_admin_areas row',
      NEW.township_id
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION core.core_settlements_require_township_admin_area() IS
  'BEFORE INSERT/UPDATE: township_id must point at admin_level code township, or be null.';

DROP TRIGGER IF EXISTS trg_core_settlements_require_township_admin_area
  ON core.core_settlements;

CREATE TRIGGER trg_core_settlements_require_township_admin_area
BEFORE INSERT OR UPDATE OF township_id
ON core.core_settlements
FOR EACH ROW
EXECUTE FUNCTION core.core_settlements_require_township_admin_area();

-- Keep is_verified aligned with verification_status (project convention).
DROP TRIGGER IF EXISTS trg_sync_is_verified_from_verification_status
  ON core.core_settlements;

CREATE TRIGGER trg_sync_is_verified_from_verification_status
BEFORE INSERT OR UPDATE OF verification_status, is_verified
ON core.core_settlements
FOR EACH ROW
EXECUTE FUNCTION core.sync_is_verified_from_verification_status();

REVOKE ALL ON TABLE ref.ref_settlement_types FROM PUBLIC;
REVOKE ALL ON TABLE core.core_settlements FROM PUBLIC;
REVOKE ALL ON FUNCTION core.core_settlements_require_township_admin_area() FROM PUBLIC;

DO $$
DECLARE
  role_name text;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON TABLE ref.ref_settlement_types FROM %I', role_name);
      EXECUTE format('REVOKE ALL ON TABLE core.core_settlements FROM %I', role_name);
      EXECUTE format(
        'REVOKE ALL ON FUNCTION core.core_settlements_require_township_admin_area() FROM %I',
        role_name
      );
    END IF;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 3) Schema assertions (no data import)
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  type_count integer;
  extra_types integer;
BEGIN
  SELECT count(*) INTO type_count
  FROM ref.ref_settlement_types
  WHERE code IN ('city', 'town', 'village', 'local_area');

  IF type_count <> 4 THEN
    RAISE EXCEPTION '192: expected 4 canonical settlement types, got %', type_count;
  END IF;

  SELECT count(*) INTO extra_types
  FROM ref.ref_settlement_types
  WHERE code IN ('hamlet', 'quarter', 'suburb', 'neighbourhood', 'neighborhood', 'locality');

  IF extra_types <> 0 THEN
    RAISE EXCEPTION '192: non-canonical settlement types were inserted';
  END IF;

  IF to_regclass('core.core_places') IS NULL THEN
    RAISE EXCEPTION '192: core.core_places is missing; refused to continue';
  END IF;

  IF to_regclass('core.core_settlements') IS NULL
     OR to_regclass('ref.ref_settlement_types') IS NULL THEN
    RAISE EXCEPTION '192: required settlement tables missing';
  END IF;

  IF (SELECT count(*) FROM core.core_settlements) <> 0 THEN
    RAISE EXCEPTION '192: core.core_settlements must be empty after schema-only migrate';
  END IF;
END $$;

COMMIT;
