create table if not exists ref.ref_admin_levels (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    rank integer not null,
    created_at timestamptz not null default now(),
    constraint ref_admin_levels_pkey primary key (id),
    constraint ref_admin_levels_code_key unique (code),
    constraint ref_admin_levels_name_key unique (name),
    constraint ref_admin_levels_rank_key unique (rank)
);

create table if not exists ref.ref_poi_categories (
    id bigint generated by default as identity,
    parent_id bigint null,
    code text not null,
    name text not null,
    sort_order integer not null,
    is_searchable boolean not null default true,
    is_public boolean not null default true,
    created_at timestamptz not null default now(),
    constraint ref_poi_categories_pkey primary key (id),
    constraint ref_poi_categories_parent_id_fkey
        foreign key (parent_id) references ref.ref_poi_categories(id),
    constraint ref_poi_categories_code_key unique (code),
    constraint ref_poi_categories_name_key unique (name)
);

create table if not exists ref.ref_source_types (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    constraint ref_source_types_pkey primary key (id),
    constraint ref_source_types_code_key unique (code),
    constraint ref_source_types_name_key unique (name)
);

create table if not exists ref.ref_publish_statuses (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    created_at timestamptz not null default now(),
    constraint ref_publish_statuses_pkey primary key (id),
    constraint ref_publish_statuses_code_key unique (code),
    constraint ref_publish_statuses_name_key unique (name)
);

create table if not exists ref.ref_validation_task_types (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    created_at timestamptz not null default now(),
    constraint ref_validation_task_types_pkey primary key (id),
    constraint ref_validation_task_types_code_key unique (code),
    constraint ref_validation_task_types_name_key unique (name)
);

create table if not exists ref.ref_validation_statuses (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    created_at timestamptz not null default now(),
    constraint ref_validation_statuses_pkey primary key (id),
    constraint ref_validation_statuses_code_key unique (code),
    constraint ref_validation_statuses_name_key unique (name)
);

create table if not exists ref.ref_report_types (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    created_at timestamptz not null default now(),
    constraint ref_report_types_pkey primary key (id),
    constraint ref_report_types_code_key unique (code),
    constraint ref_report_types_name_key unique (name)
);

create table if not exists ref.ref_report_statuses (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    created_at timestamptz not null default now(),
    constraint ref_report_statuses_pkey primary key (id),
    constraint ref_report_statuses_code_key unique (code),
    constraint ref_report_statuses_name_key unique (name)
);

create table if not exists ref.ref_address_component_types (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    rank integer not null,
    constraint ref_address_component_types_pkey primary key (id),
    constraint ref_address_component_types_code_key unique (code),
    constraint ref_address_component_types_name_key unique (name),
    constraint ref_address_component_types_rank_key unique (rank)
);

create table if not exists ref.ref_place_classes (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    constraint ref_place_classes_pkey primary key (id),
    constraint ref_place_classes_code_key unique (code),
    constraint ref_place_classes_name_key unique (name)
);

create table if not exists ref.ref_road_classes (
    id bigint generated by default as identity,
    code text not null,
    name text not null,
    constraint ref_road_classes_pkey primary key (id),
    constraint ref_road_classes_code_key unique (code),
    constraint ref_road_classes_name_key unique (name)
);
