-- system schema operational workflow tables

-- registered external data sources
create table if not exists system.system_source_registry (
    id bigint generated by default as identity,
    source_code text not null,
    source_name text not null,
    source_uri text null,
    source_type_id bigint not null,
    is_active boolean not null default true,
    config jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint system_source_registry_pkey primary key (id),
    constraint system_source_registry_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint system_source_registry_source_code_key unique (source_code),
    constraint system_source_registry_source_code_chk
        check (btrim(source_code) <> ''),
    constraint system_source_registry_source_name_chk
        check (btrim(source_name) <> '')
);

-- import runs for a registered source
create table if not exists system.system_import_batches (
    id bigint generated by default as identity,
    source_registry_id bigint not null,
    batch_name text not null,
    trigger_type text not null,
    status text not null,
    started_at timestamptz not null,
    finished_at timestamptz null,
    note text null,
    constraint system_import_batches_pkey primary key (id),
    constraint system_import_batches_source_registry_id_fkey
        foreign key (source_registry_id) references system.system_source_registry(id),
    constraint system_import_batches_batch_name_chk
        check (btrim(batch_name) <> ''),
    constraint system_import_batches_trigger_type_chk
        check (btrim(trigger_type) <> ''),
    constraint system_import_batches_status_chk
        check (btrim(status) <> ''),
    constraint system_import_batches_finished_at_chk
        check (finished_at is null or finished_at >= started_at)
);

-- captured source dataset versions within an import batch
create table if not exists system.system_source_snapshots (
    id bigint generated by default as identity,
    source_registry_id bigint not null,
    import_batch_id bigint not null,
    snapshot_ref text not null,
    snapshot_version text null,
    region_code text null,
    checksum text null,
    captured_at timestamptz not null,
    created_at timestamptz not null default now(),
    constraint system_source_snapshots_pkey primary key (id),
    constraint system_source_snapshots_source_registry_id_fkey
        foreign key (source_registry_id) references system.system_source_registry(id),
    constraint system_source_snapshots_import_batch_id_fkey
        foreign key (import_batch_id) references system.system_import_batches(id),
    constraint system_source_snapshots_source_registry_id_snapshot_ref_key
        unique (source_registry_id, snapshot_ref),
    constraint system_source_snapshots_snapshot_ref_chk
        check (btrim(snapshot_ref) <> ''),
    constraint system_source_snapshots_snapshot_version_chk
        check (snapshot_version is null or btrim(snapshot_version) <> ''),
    constraint system_source_snapshots_region_code_chk
        check (region_code is null or btrim(region_code) <> ''),
    constraint system_source_snapshots_checksum_chk
        check (checksum is null or btrim(checksum) <> '')
);

-- comparisons between source snapshots
create table if not exists system.system_diff_runs (
    id bigint generated by default as identity,
    previous_snapshot_id bigint null,
    current_snapshot_id bigint not null,
    entity_family text not null,
    status text not null,
    started_at timestamptz not null,
    finished_at timestamptz null,
    summary jsonb not null default '{}'::jsonb,
    constraint system_diff_runs_pkey primary key (id),
    constraint system_diff_runs_previous_snapshot_id_fkey
        foreign key (previous_snapshot_id) references system.system_source_snapshots(id),
    constraint system_diff_runs_current_snapshot_id_fkey
        foreign key (current_snapshot_id) references system.system_source_snapshots(id),
    constraint system_diff_runs_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_diff_runs_status_chk
        check (btrim(status) <> ''),
    constraint system_diff_runs_snapshot_pair_chk
        check (previous_snapshot_id is null or previous_snapshot_id <> current_snapshot_id),
    constraint system_diff_runs_finished_at_chk
        check (finished_at is null or finished_at >= started_at)
);

-- individual diff outcomes to review or apply
create table if not exists system.system_diff_items (
    id bigint generated by default as identity,
    diff_run_id bigint not null,
    entity_family text not null,
    diff_type text not null,
    external_id text null,
    local_entity_id bigint null,
    before_data jsonb null,
    after_data jsonb null,
    confidence_score numeric(5,4) null,
    auto_action text null,
    review_status text not null,
    created_at timestamptz not null default now(),
    constraint system_diff_items_pkey primary key (id),
    constraint system_diff_items_diff_run_id_fkey
        foreign key (diff_run_id) references system.system_diff_runs(id),
    constraint system_diff_items_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_diff_items_diff_type_chk
        check (btrim(diff_type) <> ''),
    constraint system_diff_items_external_id_chk
        check (external_id is null or btrim(external_id) <> ''),
    constraint system_diff_items_auto_action_chk
        check (auto_action is null or btrim(auto_action) <> ''),
    constraint system_diff_items_review_status_chk
        check (btrim(review_status) <> ''),
    constraint system_diff_items_confidence_score_chk
        check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1)),
    constraint system_diff_items_payload_presence_chk
        check (before_data is not null or after_data is not null)
);

-- conflicts raised from diff processing
create table if not exists system.system_conflict_queue (
    id bigint generated by default as identity,
    diff_item_id bigint not null,
    conflict_type text not null,
    resolution_status text not null,
    assigned_to bigint null,
    resolution_note text null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz null,
    constraint system_conflict_queue_pkey primary key (id),
    constraint system_conflict_queue_diff_item_id_fkey
        foreign key (diff_item_id) references system.system_diff_items(id),
    constraint system_conflict_queue_conflict_type_chk
        check (btrim(conflict_type) <> ''),
    constraint system_conflict_queue_resolution_status_chk
        check (btrim(resolution_status) <> ''),
    constraint system_conflict_queue_resolved_at_chk
        check (resolved_at is null or resolved_at >= created_at)
);

-- generic human review tasks
create table if not exists system.system_review_tasks (
    id bigint generated by default as identity,
    task_type_id bigint not null,
    status_id bigint not null,
    entity_family text not null,
    entity_id bigint not null,
    assigned_to bigint null,
    priority integer not null,
    note text null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz null,
    constraint system_review_tasks_pkey primary key (id),
    constraint system_review_tasks_task_type_id_fkey
        foreign key (task_type_id) references ref.ref_validation_task_types(id),
    constraint system_review_tasks_status_id_fkey
        foreign key (status_id) references ref.ref_validation_statuses(id),
    constraint system_review_tasks_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_review_tasks_priority_chk
        check (priority >= 0),
    constraint system_review_tasks_resolved_at_chk
        check (resolved_at is null or resolved_at >= created_at)
);

-- immutable audit log for review actions
create table if not exists system.system_review_logs (
    id bigint generated by default as identity,
    entity_family text not null,
    entity_id bigint not null,
    reviewer_user_id bigint null,
    action_type text not null,
    before_snapshot jsonb null,
    after_snapshot jsonb null,
    reason text null,
    created_at timestamptz not null default now(),
    constraint system_review_logs_pkey primary key (id),
    constraint system_review_logs_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_review_logs_action_type_chk
        check (btrim(action_type) <> ''),
    constraint system_review_logs_snapshot_presence_chk
        check (before_snapshot is not null or after_snapshot is not null or reason is not null)
);

-- publishing actions for approved changes
create table if not exists system.system_publish_batches (
    id bigint generated by default as identity,
    batch_name text not null,
    created_by bigint null,
    approved_by bigint null,
    status text not null,
    created_at timestamptz not null default now(),
    published_at timestamptz null,
    note text null,
    constraint system_publish_batches_pkey primary key (id),
    constraint system_publish_batches_batch_name_chk
        check (btrim(batch_name) <> ''),
    constraint system_publish_batches_status_chk
        check (btrim(status) <> ''),
    constraint system_publish_batches_published_at_chk
        check (published_at is null or published_at >= created_at)
);

-- publish decisions for individual entities
create table if not exists system.system_publish_items (
    id bigint generated by default as identity,
    publish_batch_id bigint not null,
    entity_family text not null,
    entity_id bigint not null,
    version_id bigint null,
    publish_action text not null,
    publish_status text not null,
    created_at timestamptz not null default now(),
    constraint system_publish_items_pkey primary key (id),
    constraint system_publish_items_publish_batch_id_fkey
        foreign key (publish_batch_id) references system.system_publish_batches(id),
    constraint system_publish_items_entity_family_chk
        check (btrim(entity_family) <> ''),
    constraint system_publish_items_publish_action_chk
        check (btrim(publish_action) <> ''),
    constraint system_publish_items_publish_status_chk
        check (btrim(publish_status) <> ''),
    constraint system_publish_items_publish_batch_id_entity_family_entity_id_publish_action_key
        unique (publish_batch_id, entity_family, entity_id, publish_action)
);

-- supporting indexes for common workflow access patterns
create index if not exists system_source_registry_source_type_id_idx
    on system.system_source_registry (source_type_id);

create index if not exists system_import_batches_source_registry_id_idx
    on system.system_import_batches (source_registry_id);

create index if not exists system_import_batches_status_idx
    on system.system_import_batches (status);

create index if not exists system_source_snapshots_import_batch_id_idx
    on system.system_source_snapshots (import_batch_id);

create index if not exists system_diff_runs_previous_snapshot_id_idx
    on system.system_diff_runs (previous_snapshot_id);

create index if not exists system_diff_runs_current_snapshot_id_idx
    on system.system_diff_runs (current_snapshot_id);

create index if not exists system_diff_runs_status_idx
    on system.system_diff_runs (status);

create index if not exists system_diff_items_diff_run_id_idx
    on system.system_diff_items (diff_run_id);

create index if not exists system_diff_items_review_status_idx
    on system.system_diff_items (review_status);

create index if not exists system_diff_items_entity_family_external_id_idx
    on system.system_diff_items (entity_family, external_id);

create index if not exists system_conflict_queue_diff_item_id_idx
    on system.system_conflict_queue (diff_item_id);

create index if not exists system_conflict_queue_resolution_status_idx
    on system.system_conflict_queue (resolution_status);

create index if not exists system_review_tasks_status_id_idx
    on system.system_review_tasks (status_id);

create index if not exists system_review_tasks_task_type_id_idx
    on system.system_review_tasks (task_type_id);

create index if not exists system_review_tasks_assigned_to_idx
    on system.system_review_tasks (assigned_to);

create index if not exists system_review_tasks_entity_family_entity_id_idx
    on system.system_review_tasks (entity_family, entity_id);

create index if not exists system_review_logs_entity_family_entity_id_idx
    on system.system_review_logs (entity_family, entity_id);

create index if not exists system_publish_batches_status_idx
    on system.system_publish_batches (status);

create index if not exists system_publish_items_entity_family_entity_id_idx
    on system.system_publish_items (entity_family, entity_id);
