-- raw schema OSM ingestion tables

-- untouched imported OSM point features
create table if not exists raw.raw_osm_points (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    osm_feature_type text not null,
    osm_id text not null,
    geom geometry(Point, 4326) not null,
    tags jsonb not null default '{}'::jsonb,
    raw_payload jsonb not null default '{}'::jsonb,
    ingested_at timestamptz not null default now(),
    constraint raw_osm_points_pkey primary key (id),
    constraint raw_osm_points_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint raw_osm_points_source_snapshot_id_osm_feature_type_osm_id_key
        unique (source_snapshot_id, osm_feature_type, osm_id),
    constraint raw_osm_points_osm_feature_type_chk
        check (btrim(osm_feature_type) <> ''),
    constraint raw_osm_points_osm_id_chk
        check (btrim(osm_id) <> '')
);

-- untouched imported OSM linear features
create table if not exists raw.raw_osm_lines (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    osm_feature_type text not null,
    osm_id text not null,
    geom geometry(LineString, 4326) not null,
    tags jsonb not null default '{}'::jsonb,
    raw_payload jsonb not null default '{}'::jsonb,
    ingested_at timestamptz not null default now(),
    constraint raw_osm_lines_pkey primary key (id),
    constraint raw_osm_lines_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint raw_osm_lines_source_snapshot_id_osm_feature_type_osm_id_key
        unique (source_snapshot_id, osm_feature_type, osm_id),
    constraint raw_osm_lines_osm_feature_type_chk
        check (btrim(osm_feature_type) <> ''),
    constraint raw_osm_lines_osm_id_chk
        check (btrim(osm_id) <> '')
);

-- untouched imported OSM polygonal features
create table if not exists raw.raw_osm_polygons (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    osm_feature_type text not null,
    osm_id text not null,
    geom geometry(MultiPolygon, 4326) not null,
    tags jsonb not null default '{}'::jsonb,
    raw_payload jsonb not null default '{}'::jsonb,
    ingested_at timestamptz not null default now(),
    constraint raw_osm_polygons_pkey primary key (id),
    constraint raw_osm_polygons_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint raw_osm_polygons_source_snapshot_id_osm_feature_type_osm_id_key
        unique (source_snapshot_id, osm_feature_type, osm_id),
    constraint raw_osm_polygons_osm_feature_type_chk
        check (btrim(osm_feature_type) <> ''),
    constraint raw_osm_polygons_osm_id_chk
        check (btrim(osm_id) <> '')
);

-- lineage and point feature access indexes
create index if not exists raw_osm_points_source_snapshot_id_idx
    on raw.raw_osm_points (source_snapshot_id);

create index if not exists raw_osm_points_osm_id_idx
    on raw.raw_osm_points (osm_id);

create index if not exists raw_osm_points_geom_gix
    on raw.raw_osm_points using gist (geom);

create index if not exists raw_osm_points_tags_gin_idx
    on raw.raw_osm_points using gin (tags);

-- lineage and line feature access indexes
create index if not exists raw_osm_lines_source_snapshot_id_idx
    on raw.raw_osm_lines (source_snapshot_id);

create index if not exists raw_osm_lines_osm_id_idx
    on raw.raw_osm_lines (osm_id);

create index if not exists raw_osm_lines_geom_gix
    on raw.raw_osm_lines using gist (geom);

create index if not exists raw_osm_lines_tags_gin_idx
    on raw.raw_osm_lines using gin (tags);

-- lineage and polygon feature access indexes
create index if not exists raw_osm_polygons_source_snapshot_id_idx
    on raw.raw_osm_polygons (source_snapshot_id);

create index if not exists raw_osm_polygons_osm_id_idx
    on raw.raw_osm_polygons (osm_id);

create index if not exists raw_osm_polygons_geom_gix
    on raw.raw_osm_polygons using gist (geom);

create index if not exists raw_osm_polygons_tags_gin_idx
    on raw.raw_osm_polygons using gin (tags);
