-- staging schema normalized candidate tables

-- administrative area candidates are created first because other staging tables may reference them
create table if not exists staging.staging_admin_area_candidates (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    external_id text not null,
    canonical_name text not null,
    admin_level_id bigint not null,
    parent_candidate_id bigint null,
    geom geometry(MultiPolygon, 4326) not null,
    centroid geometry(Point, 4326) null,
    confidence_score numeric(5,4) null,
    match_status text not null,
    matched_core_admin_area_id bigint null,
    normalized_data jsonb not null default '{}'::jsonb,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint staging_admin_area_candidates_pkey primary key (id),
    constraint staging_admin_area_candidates_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint staging_admin_area_candidates_admin_level_id_fkey
        foreign key (admin_level_id) references ref.ref_admin_levels(id),
    constraint staging_admin_area_candidates_parent_candidate_id_fkey
        foreign key (parent_candidate_id) references staging.staging_admin_area_candidates(id),
    constraint staging_admin_area_candidates_external_id_chk
        check (btrim(external_id) <> ''),
    constraint staging_admin_area_candidates_canonical_name_chk
        check (btrim(canonical_name) <> ''),
    constraint staging_admin_area_candidates_match_status_chk
        check (btrim(match_status) <> ''),
    constraint staging_admin_area_candidates_confidence_score_chk
        check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1)),
    constraint staging_admin_area_candidates_parent_self_ref_chk
        check (parent_candidate_id is null or parent_candidate_id <> id)
);

-- normalized place candidates for review and matching
create table if not exists staging.staging_place_candidates (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    source_entity_type text not null,
    external_id text not null,
    canonical_name text not null,
    place_class_id bigint not null,
    poi_category_id bigint null,
    admin_area_candidate_id bigint null,
    point_geom geometry(Point, 4326) not null,
    confidence_score numeric(5,4) null,
    match_status text not null,
    matched_core_place_id bigint null,
    normalized_data jsonb not null default '{}'::jsonb,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint staging_place_candidates_pkey primary key (id),
    constraint staging_place_candidates_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint staging_place_candidates_place_class_id_fkey
        foreign key (place_class_id) references ref.ref_place_classes(id),
    constraint staging_place_candidates_poi_category_id_fkey
        foreign key (poi_category_id) references ref.ref_poi_categories(id),
    constraint staging_place_candidates_admin_area_candidate_id_fkey
        foreign key (admin_area_candidate_id) references staging.staging_admin_area_candidates(id),
    constraint staging_place_candidates_source_entity_type_chk
        check (btrim(source_entity_type) <> ''),
    constraint staging_place_candidates_external_id_chk
        check (btrim(external_id) <> ''),
    constraint staging_place_candidates_canonical_name_chk
        check (btrim(canonical_name) <> ''),
    constraint staging_place_candidates_match_status_chk
        check (btrim(match_status) <> ''),
    constraint staging_place_candidates_confidence_score_chk
        check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1))
);

-- alternate and localized names for place candidates
create table if not exists staging.staging_place_name_candidates (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    place_candidate_id bigint not null,
    name text not null,
    language_code text null,
    script_code text null,
    name_type text not null,
    is_primary boolean not null default false,
    search_weight numeric(6,3) null,
    constraint staging_place_name_candidates_pkey primary key (id),
    constraint staging_place_name_candidates_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint staging_place_name_candidates_place_candidate_id_fkey
        foreign key (place_candidate_id) references staging.staging_place_candidates(id),
    constraint staging_place_name_candidates_name_chk
        check (btrim(name) <> ''),
    constraint staging_place_name_candidates_language_code_chk
        check (language_code is null or btrim(language_code) <> ''),
    constraint staging_place_name_candidates_script_code_chk
        check (script_code is null or btrim(script_code) <> ''),
    constraint staging_place_name_candidates_name_type_chk
        check (btrim(name_type) <> ''),
    constraint staging_place_name_candidates_search_weight_chk
        check (search_weight is null or search_weight >= 0)
);

-- normalized road candidates for cleaning and matching
create table if not exists staging.staging_road_candidates (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    external_id text not null,
    canonical_name text not null,
    road_class_id bigint null,
    geom geometry(LineString, 4326) not null,
    is_oneway boolean null,
    length_m numeric null,
    confidence_score numeric(5,4) null,
    match_status text not null,
    matched_core_edge_id bigint null,
    normalized_data jsonb not null default '{}'::jsonb,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint staging_road_candidates_pkey primary key (id),
    constraint staging_road_candidates_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint staging_road_candidates_road_class_id_fkey
        foreign key (road_class_id) references ref.ref_road_classes(id),
    constraint staging_road_candidates_external_id_chk
        check (btrim(external_id) <> ''),
    constraint staging_road_candidates_canonical_name_chk
        check (btrim(canonical_name) <> ''),
    constraint staging_road_candidates_match_status_chk
        check (btrim(match_status) <> ''),
    constraint staging_road_candidates_length_m_chk
        check (length_m is null or length_m >= 0),
    constraint staging_road_candidates_confidence_score_chk
        check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1))
);

-- normalized bus stop candidates for review and matching
create table if not exists staging.staging_bus_stop_candidates (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    external_id text not null,
    canonical_name text not null,
    point_geom geometry(Point, 4326) not null,
    admin_area_candidate_id bigint null,
    confidence_score numeric(5,4) null,
    match_status text not null,
    matched_core_bus_stop_id bigint null,
    normalized_data jsonb not null default '{}'::jsonb,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint staging_bus_stop_candidates_pkey primary key (id),
    constraint staging_bus_stop_candidates_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint staging_bus_stop_candidates_admin_area_candidate_id_fkey
        foreign key (admin_area_candidate_id) references staging.staging_admin_area_candidates(id),
    constraint staging_bus_stop_candidates_external_id_chk
        check (btrim(external_id) <> ''),
    constraint staging_bus_stop_candidates_canonical_name_chk
        check (btrim(canonical_name) <> ''),
    constraint staging_bus_stop_candidates_match_status_chk
        check (btrim(match_status) <> ''),
    constraint staging_bus_stop_candidates_confidence_score_chk
        check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1))
);

-- normalized bus route candidates for review and publish preparation
create table if not exists staging.staging_bus_route_candidates (
    id bigint generated by default as identity,
    source_snapshot_id bigint not null,
    external_id text not null,
    route_code text not null,
    public_name text not null,
    geom geometry(LineString, 4326) not null,
    confidence_score numeric(5,4) null,
    match_status text not null,
    matched_core_bus_route_id bigint null,
    normalized_data jsonb not null default '{}'::jsonb,
    source_refs jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint staging_bus_route_candidates_pkey primary key (id),
    constraint staging_bus_route_candidates_source_snapshot_id_fkey
        foreign key (source_snapshot_id) references system.system_source_snapshots(id),
    constraint staging_bus_route_candidates_external_id_chk
        check (btrim(external_id) <> ''),
    constraint staging_bus_route_candidates_route_code_chk
        check (btrim(route_code) <> ''),
    constraint staging_bus_route_candidates_public_name_chk
        check (btrim(public_name) <> ''),
    constraint staging_bus_route_candidates_match_status_chk
        check (btrim(match_status) <> ''),
    constraint staging_bus_route_candidates_confidence_score_chk
        check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1))
);

-- spatial and workflow indexes for administrative area candidates
create index if not exists staging_admin_area_candidates_source_snapshot_id_idx
    on staging.staging_admin_area_candidates (source_snapshot_id);

create index if not exists staging_admin_area_candidates_admin_level_id_idx
    on staging.staging_admin_area_candidates (admin_level_id);

create index if not exists staging_admin_area_candidates_parent_candidate_id_idx
    on staging.staging_admin_area_candidates (parent_candidate_id);

create index if not exists staging_admin_area_candidates_match_status_idx
    on staging.staging_admin_area_candidates (match_status);

create index if not exists staging_admin_area_candidates_geom_gix
    on staging.staging_admin_area_candidates using gist (geom);

create index if not exists staging_admin_area_candidates_centroid_gix
    on staging.staging_admin_area_candidates using gist (centroid);

-- spatial and workflow indexes for place candidates
create index if not exists staging_place_candidates_source_snapshot_id_idx
    on staging.staging_place_candidates (source_snapshot_id);

create index if not exists staging_place_candidates_place_class_id_idx
    on staging.staging_place_candidates (place_class_id);

create index if not exists staging_place_candidates_poi_category_id_idx
    on staging.staging_place_candidates (poi_category_id);

create index if not exists staging_place_candidates_admin_area_candidate_id_idx
    on staging.staging_place_candidates (admin_area_candidate_id);

create index if not exists staging_place_candidates_match_status_idx
    on staging.staging_place_candidates (match_status);

create index if not exists staging_place_candidates_point_geom_gix
    on staging.staging_place_candidates using gist (point_geom);

-- indexes for place name candidates
create index if not exists staging_place_name_candidates_source_snapshot_id_idx
    on staging.staging_place_name_candidates (source_snapshot_id);

create index if not exists staging_place_name_candidates_place_candidate_id_idx
    on staging.staging_place_name_candidates (place_candidate_id);

create index if not exists staging_place_name_candidates_language_code_idx
    on staging.staging_place_name_candidates (language_code);

-- spatial and workflow indexes for road candidates
create index if not exists staging_road_candidates_source_snapshot_id_idx
    on staging.staging_road_candidates (source_snapshot_id);

create index if not exists staging_road_candidates_road_class_id_idx
    on staging.staging_road_candidates (road_class_id);

create index if not exists staging_road_candidates_match_status_idx
    on staging.staging_road_candidates (match_status);

create index if not exists staging_road_candidates_geom_gix
    on staging.staging_road_candidates using gist (geom);

-- spatial and workflow indexes for bus stop candidates
create index if not exists staging_bus_stop_candidates_source_snapshot_id_idx
    on staging.staging_bus_stop_candidates (source_snapshot_id);

create index if not exists staging_bus_stop_candidates_admin_area_candidate_id_idx
    on staging.staging_bus_stop_candidates (admin_area_candidate_id);

create index if not exists staging_bus_stop_candidates_match_status_idx
    on staging.staging_bus_stop_candidates (match_status);

create index if not exists staging_bus_stop_candidates_point_geom_gix
    on staging.staging_bus_stop_candidates using gist (point_geom);

-- spatial and workflow indexes for bus route candidates
create index if not exists staging_bus_route_candidates_source_snapshot_id_idx
    on staging.staging_bus_route_candidates (source_snapshot_id);

create index if not exists staging_bus_route_candidates_match_status_idx
    on staging.staging_bus_route_candidates (match_status);

create index if not exists staging_bus_route_candidates_route_code_idx
    on staging.staging_bus_route_candidates (route_code);

create index if not exists staging_bus_route_candidates_geom_gix
    on staging.staging_bus_route_candidates using gist (geom);
