create extension if not exists pgcrypto;

create table if not exists core.core_admin_areas (
    id bigint generated by default as identity,
    public_id uuid not null default gen_random_uuid(),
    parent_id bigint null,
    admin_level_id bigint not null,
    canonical_name text not null,
    slug text not null,
    geom geometry(MultiPolygon, 4326) not null,
    centroid geometry(Point, 4326) not null,
    source_type_id bigint not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint core_admin_areas_pkey primary key (id),
    constraint core_admin_areas_parent_id_fkey
        foreign key (parent_id) references core.core_admin_areas(id),
    constraint core_admin_areas_admin_level_id_fkey
        foreign key (admin_level_id) references ref.ref_admin_levels(id),
    constraint core_admin_areas_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_admin_areas_public_id_key unique (public_id),
    constraint core_admin_areas_slug_key unique (slug),
    constraint core_admin_areas_canonical_name_chk
        check (btrim(canonical_name) <> ''),
    constraint core_admin_areas_slug_chk
        check (btrim(slug) <> ''),
    constraint core_admin_areas_parent_id_chk
        check (parent_id is null or parent_id <> id)
);

create table if not exists core.core_admin_area_names (
    id bigint generated by default as identity,
    admin_area_id bigint not null,
    name text not null,
    language_code text null,
    script_code text null,
    name_type text not null,
    is_primary boolean not null default false,
    search_weight integer not null default 0,
    constraint core_admin_area_names_pkey primary key (id),
    constraint core_admin_area_names_admin_area_id_fkey
        foreign key (admin_area_id) references core.core_admin_areas(id),
    constraint core_admin_area_names_name_chk
        check (btrim(name) <> ''),
    constraint core_admin_area_names_language_code_chk
        check (language_code is null or btrim(language_code) <> ''),
    constraint core_admin_area_names_script_code_chk
        check (script_code is null or btrim(script_code) <> ''),
    constraint core_admin_area_names_name_type_chk
        check (btrim(name_type) <> ''),
    constraint core_admin_area_names_search_weight_chk
        check (search_weight >= 0)
);

create table if not exists core.core_places (
    id bigint generated by default as identity,
    public_id uuid not null default gen_random_uuid(),
    primary_name text not null,
    secondary_name text null,
    name_local text null,
    display_name text not null,
    category_id bigint not null,
    admin_area_id bigint null,
    point_geom geometry(Point, 4326) not null,
    entry_geom geometry(Point, 4326) null,
    footprint_geom geometry(MultiPolygon, 4326) null,
    lat double precision not null,
    lng double precision not null,
    plus_code text null,
    importance_score numeric not null default 0,
    popularity_score numeric not null default 0,
    confidence_score numeric not null default 0,
    is_public boolean not null default true,
    is_verified boolean not null default false,
    source_type_id bigint not null,
    publish_status_id bigint null,
    current_version_id bigint null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null,
    constraint core_places_pkey primary key (id),
    constraint core_places_category_id_fkey
        foreign key (category_id) references ref.ref_poi_categories(id),
    constraint core_places_admin_area_id_fkey
        foreign key (admin_area_id) references core.core_admin_areas(id),
    constraint core_places_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_places_publish_status_id_fkey
        foreign key (publish_status_id) references ref.ref_publish_statuses(id),
    constraint core_places_public_id_key unique (public_id),
    constraint core_places_primary_name_chk
        check (btrim(primary_name) <> ''),
    constraint core_places_secondary_name_chk
        check (secondary_name is null or btrim(secondary_name) <> ''),
    constraint core_places_name_local_chk
        check (name_local is null or btrim(name_local) <> ''),
    constraint core_places_display_name_chk
        check (btrim(display_name) <> ''),
    constraint core_places_plus_code_chk
        check (plus_code is null or btrim(plus_code) <> ''),
    constraint core_places_lat_chk
        check (lat >= -90 and lat <= 90),
    constraint core_places_lng_chk
        check (lng >= -180 and lng <= 180),
    constraint core_places_importance_score_chk
        check (importance_score >= 0),
    constraint core_places_popularity_score_chk
        check (popularity_score >= 0),
    constraint core_places_confidence_score_chk
        check (confidence_score >= 0)
);

create table if not exists core.core_place_names (
    id bigint generated by default as identity,
    place_id bigint not null,
    name text not null,
    language_code text null,
    script_code text null,
    name_type text not null,
    is_primary boolean not null default false,
    search_weight integer not null default 0,
    constraint core_place_names_pkey primary key (id),
    constraint core_place_names_place_id_fkey
        foreign key (place_id) references core.core_places(id),
    constraint core_place_names_name_chk
        check (btrim(name) <> ''),
    constraint core_place_names_language_code_chk
        check (language_code is null or btrim(language_code) <> ''),
    constraint core_place_names_script_code_chk
        check (script_code is null or btrim(script_code) <> ''),
    constraint core_place_names_name_type_chk
        check (btrim(name_type) <> ''),
    constraint core_place_names_search_weight_chk
        check (search_weight >= 0)
);

create table if not exists core.core_place_contacts (
    id bigint generated by default as identity,
    place_id bigint not null,
    phone text null,
    website text null,
    facebook_url text null,
    opening_hours text null,
    email text null,
    constraint core_place_contacts_pkey primary key (id),
    constraint core_place_contacts_place_id_fkey
        foreign key (place_id) references core.core_places(id),
    constraint core_place_contacts_place_id_key unique (place_id),
    constraint core_place_contacts_phone_chk
        check (phone is null or btrim(phone) <> ''),
    constraint core_place_contacts_website_chk
        check (website is null or btrim(website) <> ''),
    constraint core_place_contacts_facebook_url_chk
        check (facebook_url is null or btrim(facebook_url) <> ''),
    constraint core_place_contacts_opening_hours_chk
        check (opening_hours is null or btrim(opening_hours) <> ''),
    constraint core_place_contacts_email_chk
        check (email is null or btrim(email) <> '')
);

create table if not exists core.core_place_sources (
    id bigint generated by default as identity,
    place_id bigint not null,
    source_type_id bigint not null,
    external_id text null,
    source_name text not null,
    source_url text null,
    source_priority integer not null default 0,
    captured_at timestamptz null,
    raw_payload jsonb null,
    constraint core_place_sources_pkey primary key (id),
    constraint core_place_sources_place_id_fkey
        foreign key (place_id) references core.core_places(id),
    constraint core_place_sources_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_place_sources_external_id_chk
        check (external_id is null or btrim(external_id) <> ''),
    constraint core_place_sources_source_name_chk
        check (btrim(source_name) <> ''),
    constraint core_place_sources_source_url_chk
        check (source_url is null or btrim(source_url) <> ''),
    constraint core_place_sources_source_priority_chk
        check (source_priority >= 0)
);

create table if not exists core.core_place_versions (
    id bigint generated by default as identity,
    place_id bigint not null,
    version_no integer not null,
    snapshot_data jsonb not null,
    publish_status_id bigint null,
    created_by bigint null,
    created_at timestamptz not null default now(),
    published_at timestamptz null,
    approved_by bigint null,
    constraint core_place_versions_pkey primary key (id),
    constraint core_place_versions_place_id_fkey
        foreign key (place_id) references core.core_places(id),
    constraint core_place_versions_publish_status_id_fkey
        foreign key (publish_status_id) references ref.ref_publish_statuses(id),
    constraint core_place_versions_place_id_version_no_key unique (place_id, version_no),
    constraint core_place_versions_version_no_chk
        check (version_no > 0),
    constraint core_place_versions_published_at_chk
        check (published_at is null or published_at >= created_at)
);

alter table core.core_places
    add constraint core_places_current_version_id_fkey
        foreign key (current_version_id) references core.core_place_versions(id);

create table if not exists core.core_streets (
    id bigint generated by default as identity,
    public_id uuid not null default gen_random_uuid(),
    canonical_name text not null,
    geom geometry(LineString, 4326) not null,
    admin_area_id bigint null,
    source_type_id bigint not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint core_streets_pkey primary key (id),
    constraint core_streets_admin_area_id_fkey
        foreign key (admin_area_id) references core.core_admin_areas(id),
    constraint core_streets_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_streets_public_id_key unique (public_id),
    constraint core_streets_canonical_name_chk
        check (btrim(canonical_name) <> '')
);

create table if not exists core.core_street_names (
    id bigint generated by default as identity,
    street_id bigint not null,
    name text not null,
    language_code text null,
    script_code text null,
    name_type text not null,
    is_primary boolean not null default false,
    constraint core_street_names_pkey primary key (id),
    constraint core_street_names_street_id_fkey
        foreign key (street_id) references core.core_streets(id),
    constraint core_street_names_name_chk
        check (btrim(name) <> ''),
    constraint core_street_names_language_code_chk
        check (language_code is null or btrim(language_code) <> ''),
    constraint core_street_names_script_code_chk
        check (script_code is null or btrim(script_code) <> ''),
    constraint core_street_names_name_type_chk
        check (btrim(name_type) <> '')
);

create table if not exists core.core_addresses (
    id bigint generated by default as identity,
    public_id uuid not null default gen_random_uuid(),
    full_address text not null,
    house_number text null,
    unit_number text null,
    street_id bigint null,
    admin_area_id bigint null,
    point_geom geometry(Point, 4326) null,
    entrance_geom geometry(Point, 4326) null,
    postal_code text null,
    source_type_id bigint not null,
    is_public boolean not null default true,
    is_verified boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint core_addresses_pkey primary key (id),
    constraint core_addresses_street_id_fkey
        foreign key (street_id) references core.core_streets(id),
    constraint core_addresses_admin_area_id_fkey
        foreign key (admin_area_id) references core.core_admin_areas(id),
    constraint core_addresses_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_addresses_public_id_key unique (public_id),
    constraint core_addresses_full_address_chk
        check (btrim(full_address) <> ''),
    constraint core_addresses_house_number_chk
        check (house_number is null or btrim(house_number) <> ''),
    constraint core_addresses_unit_number_chk
        check (unit_number is null or btrim(unit_number) <> ''),
    constraint core_addresses_postal_code_chk
        check (postal_code is null or btrim(postal_code) <> '')
);

create table if not exists core.core_address_components (
    id bigint generated by default as identity,
    address_id bigint not null,
    component_type_id bigint not null,
    component_value text not null,
    sort_order integer not null,
    constraint core_address_components_pkey primary key (id),
    constraint core_address_components_address_id_fkey
        foreign key (address_id) references core.core_addresses(id),
    constraint core_address_components_component_type_id_fkey
        foreign key (component_type_id) references ref.ref_address_component_types(id),
    constraint core_address_components_component_value_chk
        check (btrim(component_value) <> ''),
    constraint core_address_components_sort_order_chk
        check (sort_order >= 0)
);

create table if not exists core.core_place_addresses (
    place_id bigint not null,
    address_id bigint not null,
    relation_type text not null,
    is_primary boolean not null default false,
    constraint core_place_addresses_pkey primary key (place_id, address_id),
    constraint core_place_addresses_place_id_fkey
        foreign key (place_id) references core.core_places(id),
    constraint core_place_addresses_address_id_fkey
        foreign key (address_id) references core.core_addresses(id),
    constraint core_place_addresses_relation_type_chk
        check (btrim(relation_type) <> '')
);

create table if not exists core.core_bus_routes (
    id bigint generated by default as identity,
    route_code text not null,
    public_name text not null,
    operator_name text null,
    route_type text null,
    directionality text null,
    is_active boolean not null default true,
    source_type_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint core_bus_routes_pkey primary key (id),
    constraint core_bus_routes_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_bus_routes_route_code_key unique (route_code),
    constraint core_bus_routes_route_code_chk
        check (btrim(route_code) <> ''),
    constraint core_bus_routes_public_name_chk
        check (btrim(public_name) <> ''),
    constraint core_bus_routes_operator_name_chk
        check (operator_name is null or btrim(operator_name) <> ''),
    constraint core_bus_routes_route_type_chk
        check (route_type is null or btrim(route_type) <> ''),
    constraint core_bus_routes_directionality_chk
        check (directionality is null or btrim(directionality) <> '')
);

create table if not exists core.core_bus_route_names (
    id bigint generated by default as identity,
    route_id bigint not null,
    name text not null,
    language_code text null,
    name_type text not null,
    is_primary boolean not null default false,
    constraint core_bus_route_names_pkey primary key (id),
    constraint core_bus_route_names_route_id_fkey
        foreign key (route_id) references core.core_bus_routes(id),
    constraint core_bus_route_names_name_chk
        check (btrim(name) <> ''),
    constraint core_bus_route_names_language_code_chk
        check (language_code is null or btrim(language_code) <> ''),
    constraint core_bus_route_names_name_type_chk
        check (btrim(name_type) <> '')
);

create table if not exists core.core_bus_route_variants (
    id bigint generated by default as identity,
    route_id bigint not null,
    variant_code text not null,
    direction_name text null,
    origin_name text null,
    destination_name text null,
    geom geometry(LineString, 4326) not null,
    distance_m numeric null,
    is_active boolean not null default true,
    constraint core_bus_route_variants_pkey primary key (id),
    constraint core_bus_route_variants_route_id_fkey
        foreign key (route_id) references core.core_bus_routes(id),
    constraint core_bus_route_variants_variant_code_chk
        check (btrim(variant_code) <> ''),
    constraint core_bus_route_variants_direction_name_chk
        check (direction_name is null or btrim(direction_name) <> ''),
    constraint core_bus_route_variants_origin_name_chk
        check (origin_name is null or btrim(origin_name) <> ''),
    constraint core_bus_route_variants_destination_name_chk
        check (destination_name is null or btrim(destination_name) <> ''),
    constraint core_bus_route_variants_distance_m_chk
        check (distance_m is null or distance_m >= 0)
);

create table if not exists core.core_bus_stops (
    id bigint generated by default as identity,
    public_id uuid not null default gen_random_uuid(),
    name text not null,
    name_local text null,
    stop_code text null,
    geom geometry(Point, 4326) not null,
    admin_area_id bigint null,
    source_type_id bigint not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint core_bus_stops_pkey primary key (id),
    constraint core_bus_stops_admin_area_id_fkey
        foreign key (admin_area_id) references core.core_admin_areas(id),
    constraint core_bus_stops_source_type_id_fkey
        foreign key (source_type_id) references ref.ref_source_types(id),
    constraint core_bus_stops_public_id_key unique (public_id),
    constraint core_bus_stops_name_chk
        check (btrim(name) <> ''),
    constraint core_bus_stops_name_local_chk
        check (name_local is null or btrim(name_local) <> ''),
    constraint core_bus_stops_stop_code_chk
        check (stop_code is null or btrim(stop_code) <> '')
);

create table if not exists core.core_bus_stop_names (
    id bigint generated by default as identity,
    stop_id bigint not null,
    name text not null,
    language_code text null,
    name_type text not null,
    is_primary boolean not null default false,
    constraint core_bus_stop_names_pkey primary key (id),
    constraint core_bus_stop_names_stop_id_fkey
        foreign key (stop_id) references core.core_bus_stops(id),
    constraint core_bus_stop_names_name_chk
        check (btrim(name) <> ''),
    constraint core_bus_stop_names_language_code_chk
        check (language_code is null or btrim(language_code) <> ''),
    constraint core_bus_stop_names_name_type_chk
        check (btrim(name_type) <> '')
);

create table if not exists core.core_bus_route_stops (
    route_variant_id bigint not null,
    stop_id bigint not null,
    stop_sequence integer not null,
    distance_from_start_m numeric null,
    is_timing_point boolean not null default false,
    constraint core_bus_route_stops_pkey primary key (route_variant_id, stop_id, stop_sequence),
    constraint core_bus_route_stops_route_variant_id_fkey
        foreign key (route_variant_id) references core.core_bus_route_variants(id),
    constraint core_bus_route_stops_stop_id_fkey
        foreign key (stop_id) references core.core_bus_stops(id),
    constraint core_bus_route_stops_stop_sequence_chk
        check (stop_sequence > 0),
    constraint core_bus_route_stops_distance_from_start_m_chk
        check (distance_from_start_m is null or distance_from_start_m >= 0)
);

create index if not exists core_admin_areas_parent_id_idx
    on core.core_admin_areas (parent_id);

create index if not exists core_admin_areas_admin_level_id_idx
    on core.core_admin_areas (admin_level_id);

create index if not exists core_admin_areas_source_type_id_idx
    on core.core_admin_areas (source_type_id);

create index if not exists core_admin_areas_geom_gix
    on core.core_admin_areas using gist (geom);

create index if not exists core_admin_areas_centroid_gix
    on core.core_admin_areas using gist (centroid);

create index if not exists core_admin_area_names_admin_area_id_idx
    on core.core_admin_area_names (admin_area_id);

create index if not exists core_places_category_id_idx
    on core.core_places (category_id);

create index if not exists core_places_admin_area_id_idx
    on core.core_places (admin_area_id);

create index if not exists core_places_source_type_id_idx
    on core.core_places (source_type_id);

create index if not exists core_places_publish_status_id_idx
    on core.core_places (publish_status_id);

create index if not exists core_places_current_version_id_idx
    on core.core_places (current_version_id);

create index if not exists core_places_point_geom_gix
    on core.core_places using gist (point_geom);

create index if not exists core_places_entry_geom_gix
    on core.core_places using gist (entry_geom);

create index if not exists core_places_footprint_geom_gix
    on core.core_places using gist (footprint_geom);

create index if not exists core_place_names_place_id_idx
    on core.core_place_names (place_id);

create index if not exists core_place_sources_place_id_idx
    on core.core_place_sources (place_id);

create index if not exists core_place_sources_source_type_id_idx
    on core.core_place_sources (source_type_id);

create index if not exists core_place_versions_publish_status_id_idx
    on core.core_place_versions (publish_status_id);

create index if not exists core_streets_admin_area_id_idx
    on core.core_streets (admin_area_id);

create index if not exists core_streets_source_type_id_idx
    on core.core_streets (source_type_id);

create index if not exists core_streets_geom_gix
    on core.core_streets using gist (geom);

create index if not exists core_street_names_street_id_idx
    on core.core_street_names (street_id);

create index if not exists core_addresses_street_id_idx
    on core.core_addresses (street_id);

create index if not exists core_addresses_admin_area_id_idx
    on core.core_addresses (admin_area_id);

create index if not exists core_addresses_source_type_id_idx
    on core.core_addresses (source_type_id);

create index if not exists core_addresses_point_geom_gix
    on core.core_addresses using gist (point_geom);

create index if not exists core_addresses_entrance_geom_gix
    on core.core_addresses using gist (entrance_geom);

create index if not exists core_address_components_address_id_idx
    on core.core_address_components (address_id);

create index if not exists core_address_components_component_type_id_idx
    on core.core_address_components (component_type_id);

create index if not exists core_place_addresses_address_id_idx
    on core.core_place_addresses (address_id);

create index if not exists core_bus_routes_source_type_id_idx
    on core.core_bus_routes (source_type_id);

create index if not exists core_bus_route_names_route_id_idx
    on core.core_bus_route_names (route_id);

create index if not exists core_bus_route_variants_route_id_idx
    on core.core_bus_route_variants (route_id);

create index if not exists core_bus_route_variants_geom_gix
    on core.core_bus_route_variants using gist (geom);

create index if not exists core_bus_stops_admin_area_id_idx
    on core.core_bus_stops (admin_area_id);

create index if not exists core_bus_stops_source_type_id_idx
    on core.core_bus_stops (source_type_id);

create index if not exists core_bus_stops_geom_gix
    on core.core_bus_stops using gist (geom);

create index if not exists core_bus_stop_names_stop_id_idx
    on core.core_bus_stop_names (stop_id);

create index if not exists core_bus_route_stops_stop_id_idx
    on core.core_bus_route_stops (stop_id);
