-- Local-only bootstrap for import_work + identity helpers (no Supabase API roles).
-- Used by contract tests against geo_core. Does not touch production.

\set ON_ERROR_STOP on

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS import_work;

CREATE TABLE IF NOT EXISTS import_work.import_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code text NOT NULL,
    entity_family text NOT NULL,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    status text NOT NULL DEFAULT 'draft',
    expected_row_count bigint NULL,
    loaded_row_count bigint NULL,
    validation_status text NOT NULL DEFAULT 'not_started',
    validation_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    loaded_at timestamptz NULL,
    cleaned_at timestamptz NULL,
    CONSTRAINT import_batches_batch_code_key UNIQUE (batch_code),
    CONSTRAINT import_batches_batch_code_nonempty_chk CHECK (btrim(batch_code) <> ''),
    CONSTRAINT import_batches_snapshot_version_nonempty_chk CHECK (btrim(source_snapshot_version) <> ''),
    CONSTRAINT import_batches_entity_family_chk CHECK (entity_family IN ('places')),
    CONSTRAINT import_batches_status_chk CHECK (
        status IN ('draft', 'loading', 'loaded', 'validated', 'applied', 'failed', 'cleaned')
    ),
    CONSTRAINT import_batches_validation_status_chk CHECK (
        validation_status IN ('not_started', 'passed', 'failed', 'skipped')
    )
);

CREATE TABLE IF NOT EXISTS import_work.place_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id bigint NOT NULL
        REFERENCES import_work.import_batches (id) ON DELETE CASCADE,
    source_snapshot_id bigint NULL,
    source_snapshot_version text NOT NULL,
    external_id text NOT NULL,
    classification text NOT NULL,
    target_core_id bigint NULL,
    primary_name text NULL,
    display_name text NULL,
    category_id bigint NULL,
    admin_area_id bigint NULL,
    point_geom geometry(Point, 4326) NULL,
    lat double precision NULL,
    lng double precision NULL,
    plus_code text NULL,
    importance_score numeric NULL,
    popularity_score numeric NULL,
    confidence_score numeric NULL,
    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_hash text NULL,
    validation_status text NOT NULL DEFAULT 'pending',
    validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT place_rows_external_id_nonempty_chk CHECK (btrim(external_id) <> ''),
    CONSTRAINT place_rows_batch_external_uid UNIQUE (import_batch_id, external_id)
);

CREATE INDEX IF NOT EXISTS place_rows_batch_id_idx ON import_work.place_rows (import_batch_id);
CREATE INDEX IF NOT EXISTS place_rows_classification_idx ON import_work.place_rows (classification);
CREATE INDEX IF NOT EXISTS place_rows_point_geom_gix ON import_work.place_rows USING GIST (point_geom)
    WHERE point_geom IS NOT NULL;

COMMIT;
