package com.coremapmm.fieldsurveyor.ui.settings

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

val LocalFieldLanguage = staticCompositionLocalOf { FieldLanguage.MYANMAR }

@Composable
fun tr(english: String): String = translateFieldText(english, LocalFieldLanguage.current)

fun translateFieldText(text: String, language: FieldLanguage): String {
    if (language == FieldLanguage.ENGLISH || text.isBlank()) return text
    MYANMAR_TEXT[text]?.let { return it }
    return when {
        text.startsWith("Connected to ") -> "ချိတ်ဆက်ထားသည် — ${text.removePrefix("Connected to ")}"
        text.startsWith("Cannot reach CoreMap ") -> "CoreMap ဆာဗာသို့ ချိတ်ဆက်၍မရပါ။ ${text.substringAfter(" at ", "")}"
        text.endsWith(" variants available") -> "အသုံးပြုနိုင်သော လမ်းကြောင်းခွဲ ${text.substringBefore(' ')} ခု"
        text.endsWith(" route variants") -> "လမ်းကြောင်းခွဲ ${text.substringBefore(' ')} ခု"
        text.startsWith("Roles · ") -> "တာဝန်များ · ${text.removePrefix("Roles · ")}"
        text.startsWith("Stop: ") -> "မှတ်တိုင် — ${text.removePrefix("Stop: ")}"
        text.startsWith("Media: ") -> "မီဒီယာ — ${text.removePrefix("Media: ")}"
        text.startsWith("When: ") -> "အချိန် — ${text.removePrefix("When: ")}"
        text.startsWith("Location: ") -> "တည်နေရာ — ${text.removePrefix("Location: ")}"
        text.endsWith(" media file(s)") -> "မီဒီယာဖိုင် ${text.substringBefore(' ')} ခု"
        text.startsWith("GPS ") -> text
        text.startsWith("#") -> text.replace(" m", " မီတာ")
        text.startsWith("Review recording · ") ->
            "အသံဖိုင် စစ်ဆေးရန် · ${text.removePrefix("Review recording · ").replace("s", " စက္ကန့်")}"
        text.startsWith("Voice · ") ->
            "အသံ · ${text.removePrefix("Voice · ").replace("s", " စက္ကန့်")}"
        text.startsWith("Cache is current") -> "လမ်းကြောင်းဒေတာ နောက်ဆုံးအခြေအနေဖြစ်သည် ${text.substringAfter("current", "")}"
        text.startsWith("Downloaded snapshot ") -> "လမ်းကြောင်းဒေတာ ရယူပြီး — ${text.removePrefix("Downloaded snapshot ")}"
        text.startsWith("Refresh failed") -> "ဒေတာပြန်လည်ရယူမှု မအောင်မြင်ပါ။ ${text.substringAfter('.', "")}"
        text.startsWith("Downloaded snapshot") -> "လမ်းကြောင်းဒေတာ ရယူပြီး"
        else -> text
    }
}

private val MYANMAR_TEXT = mapOf(
    "CoreMap Field" to "CoreMap ကွင်းဆင်း",
    "Reliable field capture for Myanmar transport data." to "မြန်မာ့သယ်ယူပို့ဆောင်ရေးဒေတာကို ယုံကြည်စိတ်ချစွာ ကွင်းဆင်းကောက်ယူပါ။",
    "Surveyor sign in" to "စစ်တမ်းကောက်ယူသူ အကောင့်ဝင်ရန်",
    "Your session is encrypted with Android Keystore." to "သင့်အကောင့်အချက်အလက်ကို ဖုန်းတွင် လုံခြုံစွာ သိမ်းထားသည်။",
    "Email" to "အီးမေးလ်",
    "Password" to "စကားဝှက်",
    "Sign in" to "အကောင့်ဝင်မည်",
    "Signing in…" to "အကောင့်ဝင်နေသည်…",
    "Login failed" to "အကောင့်ဝင်၍ မရပါ",
    "Emulator address detected. A physical phone needs the Mac LAN address in local.properties." to "Emulator လိပ်စာဖြစ်နေသည်။ ဖုန်းအစစ်တွင် Mac LAN လိပ်စာ သတ်မှတ်ရန်လိုသည်။",
    "Setup / Sync" to "စတင်ပြင်ဆင်ခြင်း / ဒေတာရယူခြင်း",
    "Prepare routes and the offline map before field work." to "ကွင်းဆင်းမလုပ်မီ လမ်းကြောင်းနှင့် အော့ဖ်လိုင်းမြေပုံကို ပြင်ဆင်ပါ။",
    "Checking snapshot…" to "လမ်းကြောင်းဒေတာ စစ်ဆေးနေသည်…",
    "route variants" to "လမ်းကြောင်းခွဲများ",
    "stops" to "မှတ်တိုင်",
    "snapshot" to "ဒေတာဗားရှင်း",
    "Syncing routes" to "လမ်းကြောင်းများ ရယူနေသည်",
    "Routes ready" to "လမ်းကြောင်းများ အသင့်ဖြစ်ပြီ",
    "Routes needed" to "လမ်းကြောင်းများ လိုအပ်သည်",
    "Syncing…" to "ရယူနေသည်…",
    "Sync routes" to "လမ်းကြောင်းများ ရယူမည်",
    "Downloading Yangon streets map…" to "ရန်ကုန်လမ်းမြေပုံ ရယူနေသည်…",
    "Yangon streets map is on this device." to "ရန်ကုန်လမ်းမြေပုံကို ဖုန်းတွင် သိမ်းထားပြီးဖြစ်သည်။",
    "Yangon download finished but the file is incomplete." to "ရန်ကုန်မြေပုံဖိုင် ရယူမှု မပြည့်စုံပါ။",
    "Street zoom needs the Yangon map (~730 MB). Use Wi-Fi." to "လမ်းအဆင့်ချဲ့ကြည့်ရန် ရန်ကုန်မြေပုံ (~730 MB) လိုသည်။ Wi-Fi သုံးပါ။",
    "Downloading map" to "မြေပုံ ရယူနေသည်",
    "Offline map ready" to "အော့ဖ်လိုင်းမြေပုံ အသင့်ဖြစ်ပြီ",
    "Map needed" to "မြေပုံ လိုအပ်သည်",
    "Downloading map…" to "မြေပုံ ရယူနေသည်…",
    "Verify offline map" to "အော့ဖ်လိုင်းမြေပုံ စစ်ဆေးမည်",
    "Download Yangon map" to "ရန်ကုန်မြေပုံ ရယူမည်",
    "Continue to route selection" to "လမ်းကြောင်းရွေးရန် ဆက်သွားမည်",
    "Choose a route" to "လမ်းကြောင်းရွေးပါ",
    "Search the offline YBS snapshot. No signal is required." to "သိမ်းထားသော YBS ဒေတာတွင် ရှာပါ။ အင်တာနက်မလိုပါ။",
    "Search route code" to "လမ်းကြောင်းနံပါတ် ရှာရန်",
    "No local snapshot yet." to "ဖုန်းထဲတွင် လမ်းကြောင်းဒေတာ မရှိသေးပါ။",
    "Open Setup / Sync" to "စတင်ပြင်ဆင်ခြင်း ဖွင့်မည်",
    "Routes" to "လမ်းကြောင်းများ",
    "Survey" to "စစ်တမ်း",
    "Settings" to "ဆက်တင်များ",
    "Account, captured work, and offline data." to "အကောင့်၊ ကောက်ယူထားသည့်ဒေတာနှင့် အော့ဖ်လိုင်းဒေတာ။",
    "Profile" to "ကိုယ်ရေးအချက်အလက်",
    "Signed-in surveyor account" to "လက်ရှိအသုံးပြုနေသော စစ်တမ်းအကောင့်",
    "Outbox" to "ပို့ရန်စာရင်း",
    "Captured, synced, and waiting reports" to "ကောက်ယူပြီး၊ ပို့ပြီးနှင့် စောင့်ဆိုင်းနေသော အစီရင်ခံစာများ",
    "Infra" to "ဒေတာနှင့် မြေပုံ",
    "Yangon PMTiles and YBS snapshot sync" to "ရန်ကုန်မြေပုံနှင့် YBS ဒေတာရယူခြင်း",
    "Language" to "ဘာသာစကား",
    "Myanmar" to "မြန်မာ",
    "English" to "အင်္ဂလိပ်",
    "Appearance" to "အပြင်အဆင်",
    "Language and appearance" to "ဘာသာစကားနှင့် အပြင်အဆင်",
    "Light" to "အလင်း",
    "Dark" to "အမှောင်",
    "Back" to "နောက်သို့",
    "Not signed in." to "အကောင့်မဝင်ထားပါ။",
    "Active session" to "အကောင့် အသုံးပြုနေသည်",
    "Connection" to "ချိတ်ဆက်မှု",
    "Logging out removes credentials only. Waiting reports and offline maps remain safely on this device." to "အကောင့်ထွက်လျှင် အကောင့်အချက်အလက်သာ ဖယ်ရှားမည်။ စောင့်ဆိုင်းနေသော အစီရင်ခံစာနှင့် မြေပုံများကို ဖုန်းတွင် ဆက်လက်သိမ်းထားမည်။",
    "Log out" to "အကောင့်ထွက်မည်",
    "Reports upload safely in the background when a network is available." to "အင်တာနက်ရသည့်အခါ အစီရင်ခံစာများကို နောက်ကွယ်မှ လုံခြုံစွာ ပို့မည်။",
    "captured" to "ကောက်ယူပြီး",
    "synced" to "ပို့ပြီး",
    "waiting" to "စောင့်ဆိုင်း",
    "No reports yet." to "အစီရင်ခံစာ မရှိသေးပါ။",
    "Report detail" to "အစီရင်ခံစာ အသေးစိတ်",
    "Review evidence and sync status before upload." to "မပို့မီ အထောက်အထားနှင့် အခြေအနေကို စစ်ဆေးပါ။",
    "Note" to "မှတ်ချက်",
    "Saved. Upload will use this note." to "သိမ်းပြီးပါပြီ။ ပို့သည့်အခါ ဤမှတ်ချက်ကို သုံးမည်။",
    "Save changes" to "ပြင်ဆင်ချက် သိမ်းမည်",
    "Cancel report" to "အစီရင်ခံစာ ပယ်ဖျက်မည်",
    "No note." to "မှတ်ချက် မရှိပါ။",
    "Already uploaded. Edit or cancel on the dashboard if needed." to "ပို့ပြီးဖြစ်သည်။ လိုအပ်ပါက Dashboard တွင် ပြင်ဆင်ပါ။",
    "Cancel this report?" to "ဤအစီရင်ခံစာကို ပယ်ဖျက်မလား။",
    "It will be deleted on this phone and will not upload." to "ဤဖုန်းမှ ဖျက်ပြီး ပို့တော့မည်မဟုတ်ပါ။",
    "Delete" to "ဖျက်မည်",
    "Keep" to "ဆက်ထားမည်",
    "Waiting" to "စောင့်ဆိုင်း",
    "Queued" to "ပို့ရန်တန်းစီထားသည်",
    "Uploading" to "ပို့နေသည်",
    "Synced" to "ပို့ပြီး",
    "Retry later" to "နောက်မှ ပြန်ပို့မည်",
    "Needs fix" to "ပြင်ဆင်ရန်လိုသည်",
    "Select a D0/D1 variant" to "D0/D1 လမ်းကြောင်းခွဲ ရွေးပါ",
    "Active" to "လုပ်နေ",
    "Paused" to "ရပ်ထား",
    "Start" to "စမည်",
    "Stop" to "ရပ်မည်",
    "Report" to "အစီရင်ခံမည်",
    "Current location" to "လက်ရှိတည်နေရာ",
    "Show location and selected stop" to "လက်ရှိတည်နေရာနှင့် ရွေးထားသောမှတ်တိုင်ကို ပြမည်",
    "Show whole route" to "လမ်းကြောင်းတစ်ခုလုံးကို ပြမည်",
    "Reset north" to "မြောက်ဘက်သို့ ပြန်တည့်မည်",
    "Route stops" to "လမ်းကြောင်းမှတ်တိုင်များ",
    "Previous" to "ယခင်",
    "Current" to "လက်ရှိ",
    "Next" to "နောက်",
    "Nearest stops" to "အနီးဆုံးမှတ်တိုင်များ",
    "Report issue" to "ပြဿနာ အစီရင်ခံရန်",
    "Report details" to "အစီရင်ခံစာ အသေးစိတ်",
    "Evidence (optional)" to "မီဒီယာ (မထည့်လည်းရသည်)",
    "Choose a stop and report action first." to "မှတ်တိုင်နှင့် အစီရင်ခံမည့်အမျိုးအစားကို အရင်ရွေးပါ။",
    "Discard draft media?" to "မပို့ရသေးသော မီဒီယာကို ဖယ်မလား။",
    "Changing stops removes the unsent photo or recording." to "မှတ်တိုင်ပြောင်းလျှင် မပို့ရသေးသော ဓာတ်ပုံ သို့မဟုတ် အသံကို ဖယ်ရှားမည်။",
    "Discard" to "ဖယ်ရှားမည်",
    "Keep editing" to "ဆက်ပြင်မည်",
    "MOVED" to "နေရာရွှေ့",
    "MISSING" to "မတွေ့ရှိ",
    "DATA" to "ဒေတာမှား",
    "ROUTE" to "လမ်းမှား",
    "OTHER" to "အခြား",
    "Start the survey first." to "စစ်တမ်းကို အရင်စတင်ပါ။",
    "Select a stop first." to "မှတ်တိုင်ကို အရင်ရွေးပါ။",
    "Evidence" to "အထောက်အထား",
    "Select a stop before adding media." to "မီဒီယာမထည့်မီ မှတ်တိုင်ရွေးပါ။",
    "Take photo" to "ဓာတ်ပုံရိုက်မည်",
    "Add photo" to "ဓာတ်ပုံထည့်မည်",
    "Photo" to "ဓာတ်ပုံ",
    "Photo ready" to "ဓာတ်ပုံ အသင့်ဖြစ်ပြီ",
    "Remove" to "ဖယ်ရှားမည်",
    "Voice note" to "အသံမှတ်စု",
    "Retake" to "ပြန်ရိုက်မည်",
    "Use" to "အသုံးပြုမည်",
    "Pause" to "ခေတ္တရပ်မည်",
    "Play" to "နားထောင်မည်",
    "Tap the correct stop position on the map." to "မှန်ကန်သော မှတ်တိုင်နေရာကို မြေပုံပေါ်တွင် နှိပ်ပါ။",
    "New position selected." to "နေရာအသစ် ရွေးပြီးပါပြီ။",
    "What is wrong?" to "ဘာမှားနေသလဲ။",
    "Path" to "လမ်းကြောင်း",
    "Gap" to "ပြတ်နေရာ",
    "Other" to "အခြား",
    "Describe the issue" to "ပြဿနာကို ရေးပါ",
    "Save report" to "အစီရင်ခံစာ သိမ်းမည်",
    "Cancel" to "ပယ်ဖျက်မည်",
    "Note (optional)" to "မှတ်ချက် (မဖြည့်လည်းရသည်)",
    "Recording…" to "အသံဖမ်းနေသည်…",
    "Hold for voice" to "ဖိထားပြီး အသံဖမ်းပါ",
    "Camera permission is needed for photos." to "ဓာတ်ပုံအတွက် ကင်မရာခွင့်ပြုချက် လိုသည်။",
    "Microphone permission is needed for voice." to "အသံဖမ်းရန် မိုက်ခရိုဖုန်းခွင့်ပြုချက် လိုသည်။",
    "Hold longer to record." to "အသံဖမ်းရန် အနည်းငယ်ကြာအောင် ဖိထားပါ။",
    "Select a D0/D1 variant first." to "D0/D1 လမ်းကြောင်းခွဲကို အရင်ရွေးပါ။",
    "Turn on GPS to start survey." to "စစ်တမ်းစတင်ရန် GPS ဖွင့်ပါ။",
    "Survey ended. Start again to save reports." to "စစ်တမ်းရပ်ပြီးပါပြီ။ အစီရင်ခံစာသိမ်းရန် ပြန်စတင်ပါ။",
    "Turn on GPS." to "GPS ဖွင့်ပါ။",
    "No local snapshot. Sync first." to "ဖုန်းထဲတွင် လမ်းကြောင်းဒေတာမရှိပါ။ အရင်ရယူပါ။",
    "Need a GPS fix" to "GPS တည်နေရာ လိုအပ်သည်",
    "This report already has a voice clip." to "ဤအစီရင်ခံစာတွင် အသံဖိုင်ရှိပြီးဖြစ်သည်။",
    "This media is already uploading and cannot be removed here." to "ဤမီဒီယာကို ပို့နေပြီဖြစ်၍ ဤနေရာတွင် ဖယ်ရှား၍မရပါ။",
    "Start Survey first. That keeps GPS on and the screen awake." to "GPS နှင့် မျက်နှာပြင် ဆက်အလုပ်လုပ်ရန် စစ်တမ်းကို အရင်စတင်ပါ။",
    "Select the stop that moved." to "နေရာရွှေ့သွားသော မှတ်တိုင်ကို ရွေးပါ။",
    "Tap the map where the stop really is." to "မှတ်တိုင်အမှန်တကယ်ရှိသော နေရာကို မြေပုံပေါ်တွင် နှိပ်ပါ။",
    "Select the missing stop." to "ပျောက်ဆုံးနေသော မှတ်တိုင်ကို ရွေးပါ။",
    "Select the stop with wrong data." to "ဒေတာမှားနေသော မှတ်တိုင်ကို ရွေးပါ။",
    "Write what is wrong." to "မှားနေသောအချက်ကို ရေးပါ။",
    "Choose a route issue." to "လမ်းကြောင်းပြဿနာကို ရွေးပါ။",
    "Write a short note." to "မှတ်ချက်တိုတစ်ခု ရေးပါ။",
    "Media removed" to "မီဒီယာ ဖယ်ရှားပြီးပါပြီ",
    "✓ Captured" to "✓ ကောက်ယူပြီး",
    "Tap to focus · pinch to zoom" to "ဆုံချက်ချိန်ရန် နှိပ်ပါ · ချဲ့ရန် လက်နှစ်ချောင်းသုံးပါ",
    "Review photo" to "ဓာတ်ပုံ စစ်ဆေးရန်",
    "Close" to "ပိတ်မည်",
    "Capturing…" to "ဓာတ်ပုံရိုက်နေသည်…",
    "Take photo" to "ဓာတ်ပုံရိုက်မည်",
    "Use photo" to "ဓာတ်ပုံ အသုံးပြုမည်",
    "Attached report photo" to "အစီရင်ခံစာတွဲ ဓာတ်ပုံ",
    "Captured photo preview" to "ရိုက်ထားသော ဓာတ်ပုံ အကြိုကြည့်ရှုမှု",
    "Camera could not start" to "ကင်မရာ ဖွင့်၍မရပါ",
    "Camera failed" to "ဓာတ်ပုံရိုက်၍ မရပါ",
    "Could not start recording" to "အသံဖမ်းခြင်း စတင်၍မရပါ",
    "Could not save voice" to "အသံဖိုင် သိမ်း၍မရပါ",
    "Preparing local PMTiles…" to "အော့ဖ်လိုင်းမြေပုံ ပြင်ဆင်နေသည်…",
    "Offline Yangon streets · pan/zoom enabled" to "ရန်ကုန်လမ်းမြေပုံ · ရွှေ့/ချဲ့ ကြည့်နိုင်သည်",
    "Offline overview only · download Yangon on Setup for streets" to "အကြမ်းဖျင်းမြေပုံသာရှိသည် · လမ်းများအတွက် ရန်ကုန်မြေပုံ ရယူပါ",
)
