import {
    IMPORT_REVIEW_COMMON_TABLE_COLUMNS,
    IMPORT_REVIEW_DEFAULT_ID_COLUMNS,
    IMPORT_REVIEW_DEFAULT_SORT,
    IMPORT_REVIEW_STANDARD_FILTER_FIELDS,
} from "../constants";
import { createImportReviewEntityConfig } from "../createEntityConfig";

export const addressesImportReviewEntityConfig = createImportReviewEntityConfig({
    slug: "addresses",
    apiFamily: "addresses",
    label: "Address",
    pluralLabel: "Addresses",
    geometryType: "point",
    mapLayerType: "point",
    mapEntityType: "generic",
    riskLevel: "low",
    tableColumns: [
        ...IMPORT_REVIEW_DEFAULT_ID_COLUMNS,
        { key: "full_address", label: "Full address", source: "normalized" },
        { key: "house_number", label: "House #", source: "normalized" },
        { key: "street_name", label: "Street", source: "normalized" },
        { key: "township", label: "Township", source: "normalized" },
        { key: "city", label: "City", source: "normalized" },
        ...IMPORT_REVIEW_COMMON_TABLE_COLUMNS,
    ],
    searchableFields: [
        "full_address",
        "house_number",
        "street_name",
        "quarter",
        "township",
        "city",
        "postcode",
        "plus_code",
        "external_id",
    ],
    filterFields: IMPORT_REVIEW_STANDARD_FILTER_FIELDS,
    overrideEditableFields: [
        "full_address",
        "house_number",
        "street_name",
        "quarter",
        "township",
        "city",
        "postcode",
        "plus_code",
    ],
    refDropdownFields: [],
    defaultSort: IMPORT_REVIEW_DEFAULT_SORT,
    supportsBulkActions: true,
    supportsMapPreview: true,
    supportsVertexPreview: false,
    supportsGeometryEditLater: false,
    supportsPromotion: false,
    supportsOverrideEditor: true,
});
