import {
    IMPORT_REVIEW_COMMON_TABLE_COLUMNS,
    IMPORT_REVIEW_DEFAULT_ID_COLUMNS,
    IMPORT_REVIEW_DEFAULT_SORT,
    IMPORT_REVIEW_STANDARD_FILTER_FIELDS,
} from "../constants";
import { createImportReviewEntityConfig } from "../createEntityConfig";

export const addressesImportReviewEntityConfig = createImportReviewEntityConfig({
    slug: "addresses",
    apiFamily: "addresses",
    label: "Address",
    pluralLabel: "Addresses",
    geometryType: "point",
    mapLayerType: "point",
    mapEntityType: "generic",
    riskLevel: "low",
    tableColumns: [...IMPORT_REVIEW_DEFAULT_ID_COLUMNS, ...IMPORT_REVIEW_COMMON_TABLE_COLUMNS],
    searchableFields: [
        "full_address",
        "house_number",
        "street",
        "locality",
        "city",
        "postcode",
        "external_id",
    ],
    filterFields: IMPORT_REVIEW_STANDARD_FILTER_FIELDS,
    overrideEditableFields: [],
    refDropdownFields: [],
    defaultSort: IMPORT_REVIEW_DEFAULT_SORT,
    supportsBulkActions: true,
    supportsMapPreview: true,
    supportsVertexPreview: false,
    supportsGeometryEditLater: false,
    supportsPromotion: true,
    supportsOverrideEditor: false,
    detailTitleField: "display_full_address",
    detailSubtitleField: "external_id",
});
