import {
    IMPORT_REVIEW_COMMON_TABLE_COLUMNS,
    IMPORT_REVIEW_DEFAULT_ID_COLUMNS,
    IMPORT_REVIEW_DEFAULT_SORT,
    IMPORT_REVIEW_STANDARD_FILTER_FIELDS,
} from "../constants";
/** @deprecated UI hidden — use /dashboard/import-transport. Config retained for legacy API/tests. */
import { createImportReviewEntityConfig } from "../createEntityConfig";

export const busRouteVariantsImportReviewEntityConfig = createImportReviewEntityConfig({
    slug: "bus-route-variants",
    apiFamily: "bus_route_variants",
    label: "Bus route variant",
    pluralLabel: "Bus route variants",
    geometryType: "line",
    mapLayerType: "line",
    mapEntityType: "generic",
    riskLevel: "medium",
    tableColumns: [
        ...IMPORT_REVIEW_DEFAULT_ID_COLUMNS,
        { key: "route_id", label: "Route ID", source: "row", mono: true },
        { key: "route_code", label: "Route code", source: "row", mono: true },
        { key: "variant_code", label: "Variant code", source: "row", mono: true },
        { key: "direction_name", label: "Direction", source: "row" },
        { key: "origin_name", label: "Origin", source: "row" },
        { key: "destination_name", label: "Destination", source: "row" },
        { key: "distance_m", label: "Distance (m)", source: "row" },
        ...IMPORT_REVIEW_COMMON_TABLE_COLUMNS,
    ],
    searchableFields: ["route_code", "variant_code", "direction_name", "origin_name", "destination_name", "external_id"],
    filterFields: IMPORT_REVIEW_STANDARD_FILTER_FIELDS,
    overrideEditableFields: [
        "route_id",
        "route_code",
        "variant_code",
        "direction_name",
        "origin_name",
        "destination_name",
        "distance_m",
        "geom",
    ],
    refDropdownFields: [],
    defaultSort: IMPORT_REVIEW_DEFAULT_SORT,
    supportsBulkActions: true,
    supportsMapPreview: true,
    supportsVertexPreview: false,
    supportsGeometryEditLater: false,
    supportsPromotion: true,
    supportsOverrideEditor: true,
});
