package com.coremapmm.app.core.fake

import com.coremapmm.app.core.model.PlaceUiModel

object FakePlaces {
  val discoverPlaces: List<PlaceUiModel> = listOf(
    PlaceUiModel(
      id = "place-shwedagon-pagoda",
      name = "Shwedagon Pagoda",
      category = "Landmark",
      township = "Dagon",
      region = "Yangon Region",
      distanceText = "2.4 km",
      verified = true,
      ratingText = "4.8",
      address = "Shwedagon Pagoda Road, Dagon Township, Yangon",
      plusCode = "6Q5M+2Q Yangon",
      phoneText = "01-123-456",
      photoUrls = listOf(
        "https://cdn.coremap.mm/placeholder/shwedagon-1.jpg",
        "https://cdn.coremap.mm/placeholder/shwedagon-2.jpg",
      ),
      isSaved = true,
    ),
    PlaceUiModel(
      id = "place-kyauktan-market",
      name = "Kyauktan Market",
      category = "Market",
      township = "Kyauktan",
      region = "Yangon Region",
      distanceText = "18 km",
      verified = true,
      ratingText = "4.2",
      address = "Main Road, Kyauktan Township",
      plusCode = "6Q2F+8W Kyauktan",
      phoneText = "Not available",
      photoUrls = listOf(
        "https://cdn.coremap.mm/placeholder/kyauktan-market-1.jpg",
      ),
      isSaved = false,
    ),
    PlaceUiModel(
      id = "place-thanlyin-bridge",
      name = "Thanlyin Bridge",
      category = "Bridge",
      township = "Thanlyin",
      region = "Yangon Region",
      distanceText = "12 km",
      verified = true,
      ratingText = "4.5",
      address = "Thanlyin Bridge Road, Thanlyin Township",
      plusCode = "6Q3P+5R Thanlyin",
      phoneText = "Not available",
      photoUrls = emptyList(),
      isSaved = false,
    ),
    PlaceUiModel(
      id = "place-yangon-general-hospital",
      name = "Yangon General Hospital",
      category = "Hospital",
      township = "Lanmadaw",
      region = "Yangon Region",
      distanceText = "3.1 km",
      verified = true,
      ratingText = "4.0",
      address = "Bogyoke Aung San Road, Lanmadaw Township, Yangon",
      plusCode = "6Q5J+7X Yangon",
      phoneText = "01-384-794",
      photoUrls = listOf(
        "https://cdn.coremap.mm/placeholder/ygh-1.jpg",
      ),
      isSaved = true,
    ),
    PlaceUiModel(
      id = "place-kyauktan-riverside-tea-shop",
      name = "Kyauktan Riverside Tea Shop",
      category = "Restaurant",
      township = "Kyauktan",
      region = "Yangon Region",
      distanceText = "1.2 km",
      verified = true,
      ratingText = "4.3",
      address = "Riverside Road, Kyauktan Township",
      plusCode = "6Q2G+9C Kyauktan",
      phoneText = "Not available",
      photoUrls = emptyList(),
      isSaved = false,
    ),
    PlaceUiModel(
      id = "place-kyauktan-main-bus-stop",
      name = "Kyauktan Main Bus Stop",
      category = "Bus stop",
      township = "Kyauktan",
      region = "Yangon Region",
      distanceText = "850 m",
      verified = true,
      ratingText = "4.1",
      address = "Main Road, Kyauktan Township",
      plusCode = "6Q2F+JV Kyauktan",
      phoneText = "Not available",
      photoUrls = emptyList(),
      isSaved = false,
    ),
  )

  val savedPlaces: List<PlaceUiModel> = discoverPlaces.filter { it.isSaved }

    val countryHotspots: List<PlaceUiModel> = listOf(
        discoverPlaces[0], // Shwedagon
        PlaceUiModel(
            id = "place-bagan-temples",
            name = "Bagan Temples",
            category = "Landmark",
            township = "Bagan",
            region = "Mandalay Region",
            distanceText = "—",
            verified = true,
            ratingText = "4.9",
            address = "Bagan Archaeological Zone",
            plusCode = "—",
            phoneText = "Not available",
            photoUrls = emptyList(),
            isSaved = false,
        ),
        PlaceUiModel(
            id = "place-inle-lake",
            name = "Inle Lake",
            category = "Nature",
            township = "Nyaung Shwe",
            region = "Shan State",
            distanceText = "—",
            verified = true,
            ratingText = "4.7",
            address = "Inle Lake, Nyaung Shwe Township",
            plusCode = "—",
            phoneText = "Not available",
            photoUrls = emptyList(),
            isSaved = true,
        ),
        PlaceUiModel(
            id = "place-u-bein-bridge",
            name = "U Bein Bridge",
            category = "Bridge",
            township = "Amarapura",
            region = "Mandalay Region",
            distanceText = "—",
            verified = true,
            ratingText = "4.6",
            address = "Amarapura Township, Mandalay",
            plusCode = "—",
            phoneText = "Not available",
            photoUrls = emptyList(),
            isSaved = false,
        ),
    PlaceUiModel(
      id = "place-golden-rock",
      name = "Golden Rock",
      category = "Landmark",
      township = "Kyaiktiyo",
      region = "Mon State",
      distanceText = "—",
      verified = true,
      ratingText = "4.8",
      address = "Kyaiktiyo Township, Mon State",
      plusCode = "—",
      phoneText = "Not available",
      photoUrls = emptyList(),
      isSaved = false,
    ),
    PlaceUiModel(
      id = "place-ngapali-beach",
      name = "Ngapali Beach",
      category = "Beach",
      township = "Thandwe",
      region = "Rakhine State",
      distanceText = "—",
      verified = true,
      ratingText = "4.5",
      address = "Ngapali, Thandwe Township",
      plusCode = "—",
      phoneText = "Not available",
      photoUrls = emptyList(),
      isSaved = false,
    ),
    )

  fun byId(placeId: String): PlaceUiModel? =
    (discoverPlaces + countryHotspots).distinctBy { it.id }.find { it.id == placeId }
}
