name: Generate MapLibre Glyphs

on:
  workflow_dispatch:

jobs:
  generate-glyphs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build PBF glyphs
        uses: linz/action-build-pbf-glyphs@v1
        with:
          source: glyph-source/
          target: glyph-output/

      - name: Check Myanmar glyph range
        run: |
          ls "glyph-output/Noto Sans Myanmar Regular"
          test -f "glyph-output/Noto Sans Myanmar Regular/4096-4351.pbf"

      - name: Upload glyph artifact
        uses: actions/upload-artifact@v4
        with:
          name: maplibre-glyphs
          path: glyph-output