-- =============================================================================
-- Local system tracking upgrade (non-destructive)
-- =============================================================================
--
-- Source baseline:
--   infrastructure/database/snapshots/local/local_system_schema_baseline_2026_05_15.sql
--
-- Purpose:
--   Harden the existing local system schema for long-term import tracking,
--   snapshots, diffs, review logs, review tasks, conflict handling, and publishing.
--
-- Safety rules:
--   - Does not DROP, TRUNCATE, rename, or recreate existing system tables.
--   - Preserves all rows in system.system_* tables.
--   - Uses CREATE ... IF NOT EXISTS, ALTER TABLE ... ADD COLUMN IF NOT EXISTS,
--     CREATE INDEX IF NOT EXISTS, and guarded DO blocks.
--   - Constraints with closed status vocabularies are added only when existing
--     rows already satisfy them; otherwise they are skipped with NOTICE.
--   - Numeric IDs are not synchronized across environments. Use stable keys:
--     source_code, snapshot_version, checksum, region_code.
--
-- Manual decision only:
--   If you ever want to rename tables from system.system_* to system.*, do not
--   do it automatically. That would require an explicit migration plan and
--   manual approval because local data already exists.
--
-- -----------------------------------------------------------------------------
-- Preflight checks to run manually before applying
-- -----------------------------------------------------------------------------
--
-- 1) Inventory system tables:
-- select table_schema, table_name
-- from information_schema.tables
-- where table_schema = 'system'
-- order by table_name;
--
-- 2) Duplicate source codes (must return no rows before unique source_code):
-- select source_code, count(*)
-- from system.system_source_registry
-- group by source_code
-- having count(*) > 1;
--
-- 3) Duplicate non-null snapshot versions (must return no rows before unique snapshot_version):
-- select snapshot_version, count(*)
-- from system.system_source_snapshots
-- where snapshot_version is not null
-- group by snapshot_version
-- having count(*) > 1;
--
-- 4) Snapshot versions that are null (allowed by current local schema, but weak as stable keys):
-- select id, source_registry_id, snapshot_ref, region_code, checksum
-- from system.system_source_snapshots
-- where snapshot_version is null;
--
-- 5) Status / type values that would prevent stricter checks:
-- select 'import_batches.status' as field, status as value, count(*)
-- from system.system_import_batches
-- group by status
-- union all
-- select 'diff_runs.status', status, count(*)
-- from system.system_diff_runs
-- group by status
-- union all
-- select 'diff_items.diff_type', diff_type, count(*)
-- from system.system_diff_items
-- group by diff_type
-- union all
-- select 'diff_items.review_status', review_status, count(*)
-- from system.system_diff_items
-- group by review_status
-- union all
-- select 'publish_batches.status', status, count(*)
-- from system.system_publish_batches
-- group by status
-- union all
-- select 'publish_items.publish_status', publish_status, count(*)
-- from system.system_publish_items
-- group by publish_status
-- union all
-- select 'publish_items.publish_action', publish_action, count(*)
-- from system.system_publish_items
-- group by publish_action
-- union all
-- select 'conflict_queue.resolution_status', resolution_status, count(*)
-- from system.system_conflict_queue
-- group by resolution_status;
--
-- 6) Long-running import batches:
-- select id, batch_name, source_registry_id, started_at, note
-- from system.system_import_batches
-- where status = 'running'
-- order by started_at;
--
-- =============================================================================

create schema if not exists system;

-- -----------------------------------------------------------------------------
-- Table shape safety net
-- -----------------------------------------------------------------------------
-- These CREATE TABLE statements are intentionally conservative. On the current
-- local DB they should all be skipped because the baseline tables already exist.

create table if not exists system.system_source_registry (
    id bigint generated by default as identity primary key,
    source_code text not null,
    source_name text not null,
    source_uri text null,
    source_type_id bigint not null,
    is_active boolean not null default true,
    config jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists system.system_import_batches (
    id bigint generated by default as identity primary key,
    source_registry_id bigint not null,
    batch_name text not null,
    trigger_type text not null,
    status text not null,
    started_at timestamptz not null,
    finished_at timestamptz null,
    note text null
);

create table if not exists system.system_source_snapshots (
    id bigint generated by default as identity primary key,
    source_registry_id bigint not null,
    import_batch_id bigint not null,
    snapshot_ref text not null,
    snapshot_version text null,
    region_code text null,
    checksum text null,
    captured_at timestamptz not null,
    created_at timestamptz not null default now()
);

create table if not exists system.system_diff_runs (
    id bigint generated by default as identity primary key,
    previous_snapshot_id bigint null,
    current_snapshot_id bigint not null,
    entity_family text not null,
    status text not null,
    started_at timestamptz not null,
    finished_at timestamptz null,
    summary jsonb not null default '{}'::jsonb
);

create table if not exists system.system_diff_items (
    id bigint generated by default as identity primary key,
    diff_run_id bigint not null,
    entity_family text not null,
    diff_type text not null,
    external_id text null,
    local_entity_id bigint null,
    before_data jsonb null,
    after_data jsonb null,
    confidence_score numeric(6,2) null,
    auto_action text null,
    review_status text not null,
    created_at timestamptz not null default now()
);

create table if not exists system.system_conflict_queue (
    id bigint generated by default as identity primary key,
    diff_item_id bigint not null,
    conflict_type text not null,
    resolution_status text not null,
    assigned_to bigint null,
    resolution_note text null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz null
);

create table if not exists system.system_review_tasks (
    id bigint generated by default as identity primary key,
    task_type_id bigint not null,
    status_id bigint not null,
    entity_family text not null,
    entity_id bigint not null,
    assigned_to bigint null,
    priority integer not null,
    note text null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz null
);

create table if not exists system.system_review_logs (
    id bigint generated by default as identity primary key,
    entity_family text not null,
    entity_id bigint not null,
    reviewer_user_id bigint null,
    action_type text not null,
    before_snapshot jsonb null,
    after_snapshot jsonb null,
    reason text null,
    created_at timestamptz not null default now()
);

create table if not exists system.system_publish_batches (
    id bigint generated by default as identity primary key,
    batch_name text not null,
    created_by bigint null,
    approved_by bigint null,
    status text not null,
    created_at timestamptz not null default now(),
    published_at timestamptz null,
    note text null
);

create table if not exists system.system_publish_items (
    id bigint generated by default as identity primary key,
    publish_batch_id bigint not null,
    entity_family text not null,
    entity_id bigint not null,
    version_id bigint null,
    publish_action text not null,
    publish_status text not null,
    created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Column/default safety net
-- -----------------------------------------------------------------------------

alter table system.system_source_registry
    add column if not exists config jsonb not null default '{}'::jsonb,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

alter table system.system_import_batches
    add column if not exists trigger_type text not null default 'manual',
    add column if not exists status text not null default 'running',
    add column if not exists started_at timestamptz not null default now(),
    add column if not exists finished_at timestamptz null,
    add column if not exists note text null;

alter table system.system_source_snapshots
    add column if not exists snapshot_version text null,
    add column if not exists region_code text null,
    add column if not exists checksum text null,
    add column if not exists captured_at timestamptz not null default now(),
    add column if not exists created_at timestamptz not null default now();

alter table system.system_diff_runs
    add column if not exists status text not null default 'running',
    add column if not exists started_at timestamptz not null default now(),
    add column if not exists finished_at timestamptz null,
    add column if not exists summary jsonb not null default '{}'::jsonb;

alter table system.system_diff_items
    add column if not exists before_data jsonb null,
    add column if not exists after_data jsonb null,
    add column if not exists confidence_score numeric(6,2) null,
    add column if not exists auto_action text null,
    add column if not exists review_status text not null default 'pending',
    add column if not exists created_at timestamptz not null default now();

alter table system.system_review_logs
    add column if not exists reviewer_user_id bigint null,
    add column if not exists before_snapshot jsonb null,
    add column if not exists after_snapshot jsonb null,
    add column if not exists reason text null,
    add column if not exists created_at timestamptz not null default now();

-- -----------------------------------------------------------------------------
-- Unique constraints
-- -----------------------------------------------------------------------------

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'system_source_registry_source_code_key'
          and conrelid = 'system.system_source_registry'::regclass
    ) then
        if not exists (
            select 1
            from system.system_source_registry
            group by source_code
            having count(*) > 1
        ) then
            alter table system.system_source_registry
                add constraint system_source_registry_source_code_key unique (source_code);
        else
            raise notice 'Skipped system_source_registry_source_code_key: duplicate source_code values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'system_source_snapshots_snapshot_version_key'
          and conrelid = 'system.system_source_snapshots'::regclass
    ) then
        if not exists (
            select 1
            from system.system_source_snapshots
            where snapshot_version is not null
            group by snapshot_version
            having count(*) > 1
        ) then
            alter table system.system_source_snapshots
                add constraint system_source_snapshots_snapshot_version_key unique (snapshot_version);
        else
            raise notice 'Skipped system_source_snapshots_snapshot_version_key: duplicate non-null snapshot_version values exist.';
        end if;
    end if;
end $$;

-- -----------------------------------------------------------------------------
-- Reasonable status/value checks, added only when existing data is compatible
-- -----------------------------------------------------------------------------

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_import_batches_status_allowed_chk'
          and conrelid = 'system.system_import_batches'::regclass
    ) then
        if not exists (
            select 1 from system.system_import_batches
            where status not in ('running', 'completed', 'failed', 'cancelled')
        ) then
            alter table system.system_import_batches
                add constraint system_import_batches_status_allowed_chk
                check (status in ('running', 'completed', 'failed', 'cancelled'));
        else
            raise notice 'Skipped system_import_batches_status_allowed_chk: unsupported status values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_runs_status_allowed_chk'
          and conrelid = 'system.system_diff_runs'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_runs
            where status not in ('running', 'completed', 'failed', 'cancelled')
        ) then
            alter table system.system_diff_runs
                add constraint system_diff_runs_status_allowed_chk
                check (status in ('running', 'completed', 'failed', 'cancelled'));
        else
            raise notice 'Skipped system_diff_runs_status_allowed_chk: unsupported status values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_items_diff_type_allowed_chk'
          and conrelid = 'system.system_diff_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_items
            where diff_type not in ('new', 'changed', 'deleted_candidate', 'unchanged', 'conflict')
        ) then
            alter table system.system_diff_items
                add constraint system_diff_items_diff_type_allowed_chk
                check (diff_type in ('new', 'changed', 'deleted_candidate', 'unchanged', 'conflict'));
        else
            raise notice 'Skipped system_diff_items_diff_type_allowed_chk: unsupported diff_type values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_diff_items_review_status_allowed_chk'
          and conrelid = 'system.system_diff_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_diff_items
            where review_status not in ('pending', 'approved', 'rejected', 'ignored', 'auto_applied')
        ) then
            alter table system.system_diff_items
                add constraint system_diff_items_review_status_allowed_chk
                check (review_status in ('pending', 'approved', 'rejected', 'ignored', 'auto_applied'));
        else
            raise notice 'Skipped system_diff_items_review_status_allowed_chk: unsupported review_status values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_publish_batches_status_allowed_chk'
          and conrelid = 'system.system_publish_batches'::regclass
    ) then
        if not exists (
            select 1 from system.system_publish_batches
            where status not in ('draft', 'pending', 'approved', 'published', 'failed', 'cancelled')
        ) then
            alter table system.system_publish_batches
                add constraint system_publish_batches_status_allowed_chk
                check (status in ('draft', 'pending', 'approved', 'published', 'failed', 'cancelled'));
        else
            raise notice 'Skipped system_publish_batches_status_allowed_chk: unsupported status values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_publish_items_publish_status_allowed_chk'
          and conrelid = 'system.system_publish_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_publish_items
            where publish_status not in ('pending', 'approved', 'published', 'failed', 'cancelled', 'rejected')
        ) then
            alter table system.system_publish_items
                add constraint system_publish_items_publish_status_allowed_chk
                check (publish_status in ('pending', 'approved', 'published', 'failed', 'cancelled', 'rejected'));
        else
            raise notice 'Skipped system_publish_items_publish_status_allowed_chk: unsupported publish_status values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_publish_items_publish_action_allowed_chk'
          and conrelid = 'system.system_publish_items'::regclass
    ) then
        if not exists (
            select 1 from system.system_publish_items
            where publish_action not in ('insert', 'update', 'upsert', 'delete', 'noop')
        ) then
            alter table system.system_publish_items
                add constraint system_publish_items_publish_action_allowed_chk
                check (publish_action in ('insert', 'update', 'upsert', 'delete', 'noop'));
        else
            raise notice 'Skipped system_publish_items_publish_action_allowed_chk: unsupported publish_action values exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'system_conflict_queue_resolution_status_allowed_chk'
          and conrelid = 'system.system_conflict_queue'::regclass
    ) then
        if not exists (
            select 1 from system.system_conflict_queue
            where resolution_status not in ('open', 'assigned', 'resolved', 'ignored', 'cancelled')
        ) then
            alter table system.system_conflict_queue
                add constraint system_conflict_queue_resolution_status_allowed_chk
                check (resolution_status in ('open', 'assigned', 'resolved', 'ignored', 'cancelled'));
        else
            raise notice 'Skipped system_conflict_queue_resolution_status_allowed_chk: unsupported resolution_status values exist.';
        end if;
    end if;
end $$;

-- -----------------------------------------------------------------------------
-- Indexes for long-term tracking and review queries
-- -----------------------------------------------------------------------------

create index if not exists system_source_registry_source_type_id_idx
    on system.system_source_registry (source_type_id);

create index if not exists system_import_batches_source_registry_id_idx
    on system.system_import_batches (source_registry_id);

create index if not exists system_import_batches_status_idx
    on system.system_import_batches (status);

create index if not exists system_source_snapshots_source_registry_id_idx
    on system.system_source_snapshots (source_registry_id);

create index if not exists system_source_snapshots_import_batch_id_idx
    on system.system_source_snapshots (import_batch_id);

create index if not exists system_source_snapshots_snapshot_version_idx
    on system.system_source_snapshots (snapshot_version);

create index if not exists system_source_snapshots_region_code_idx
    on system.system_source_snapshots (region_code);

create index if not exists system_source_snapshots_checksum_idx
    on system.system_source_snapshots (checksum);

create index if not exists system_diff_runs_previous_snapshot_id_idx
    on system.system_diff_runs (previous_snapshot_id);

create index if not exists system_diff_runs_current_snapshot_id_idx
    on system.system_diff_runs (current_snapshot_id);

create index if not exists system_diff_runs_entity_family_idx
    on system.system_diff_runs (entity_family);

create index if not exists system_diff_runs_status_idx
    on system.system_diff_runs (status);

create index if not exists system_diff_items_diff_run_id_idx
    on system.system_diff_items (diff_run_id);

create index if not exists system_diff_items_entity_family_diff_type_idx
    on system.system_diff_items (entity_family, diff_type);

create index if not exists system_diff_items_entity_family_external_id_idx
    on system.system_diff_items (entity_family, external_id);

create index if not exists system_diff_items_external_id_idx
    on system.system_diff_items (external_id);

create index if not exists system_diff_items_review_status_idx
    on system.system_diff_items (review_status);

create index if not exists system_review_logs_entity_family_entity_id_idx
    on system.system_review_logs (entity_family, entity_id);

create index if not exists system_review_tasks_task_type_id_idx
    on system.system_review_tasks (task_type_id);

create index if not exists system_review_tasks_status_id_idx
    on system.system_review_tasks (status_id);

create index if not exists system_review_tasks_assigned_to_idx
    on system.system_review_tasks (assigned_to);

create index if not exists system_review_tasks_entity_family_entity_id_idx
    on system.system_review_tasks (entity_family, entity_id);

create index if not exists system_conflict_queue_diff_item_id_idx
    on system.system_conflict_queue (diff_item_id);

create index if not exists system_conflict_queue_resolution_status_idx
    on system.system_conflict_queue (resolution_status);

create index if not exists system_publish_batches_status_idx
    on system.system_publish_batches (status);

create index if not exists system_publish_items_entity_family_entity_id_idx
    on system.system_publish_items (entity_family, entity_id);

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------

comment on schema system is
    'Operational metadata for import lineage, source snapshots, diffs, review workflow, and publishing.';

comment on table system.system_source_registry is
    'Registered external and internal data sources used for lineage, imports, and provenance.';
comment on column system.system_source_registry.source_code is
    'Stable source key. Use this across local and Supabase instead of numeric ids.';
comment on column system.system_source_registry.config is
    'Source-specific configuration and metadata as JSONB.';

comment on table system.system_import_batches is
    'One import run for a registered source.';
comment on column system.system_import_batches.source_registry_id is
    'Source registry row that produced this import batch.';
comment on column system.system_import_batches.status is
    'Import lifecycle status. Existing rows are preserved; stricter check is added only when compatible.';

comment on table system.system_source_snapshots is
    'Captured version of a source dataset, tied to an import batch and stable version/checksum metadata.';
comment on column system.system_source_snapshots.snapshot_version is
    'Stable snapshot key for comparing local and Supabase. Numeric ids may differ by database.';
comment on column system.system_source_snapshots.checksum is
    'Checksum for the captured source data when available.';
comment on column system.system_source_snapshots.region_code is
    'Stable region identifier for the snapshot scope.';

comment on table system.system_diff_runs is
    'Comparison run between source snapshots for a single entity family.';
comment on table system.system_diff_items is
    'Per-entity result generated by a diff run.';
comment on table system.system_conflict_queue is
    'Queue of conflicts detected from diff items that require resolution.';
comment on table system.system_review_tasks is
    'Human or automated review tasks for entities requiring validation.';
comment on table system.system_review_logs is
    'Append-oriented audit trail of review or promotion actions.';
comment on table system.system_publish_batches is
    'Group of approved changes prepared for publishing into production-ready core data.';
comment on table system.system_publish_items is
    'Per-entity publish decision within a publish batch.';

-- -----------------------------------------------------------------------------
-- Verification SELECTs to run after applying
-- -----------------------------------------------------------------------------
--
-- 1) Constraints now present:
-- select conrelid::regclass as table_name, conname, contype
-- from pg_constraint
-- where connamespace = 'system'::regnamespace
--   and conname in (
--     'system_source_registry_source_code_key',
--     'system_source_snapshots_snapshot_version_key',
--     'system_import_batches_status_allowed_chk',
--     'system_diff_runs_status_allowed_chk',
--     'system_diff_items_diff_type_allowed_chk',
--     'system_diff_items_review_status_allowed_chk'
--   )
-- order by table_name::text, conname;
--
-- 2) Indexes now present:
-- select schemaname, tablename, indexname
-- from pg_indexes
-- where schemaname = 'system'
--   and indexname in (
--     'system_diff_items_diff_run_id_idx',
--     'system_diff_items_entity_family_diff_type_idx',
--     'system_diff_items_external_id_idx',
--     'system_review_logs_entity_family_entity_id_idx',
--     'system_source_snapshots_snapshot_version_idx'
--   )
-- order by tablename, indexname;
--
-- 3) Row counts preserved:
-- select 'system_source_registry' as table_name, count(*) from system.system_source_registry
-- union all select 'system_import_batches', count(*) from system.system_import_batches
-- union all select 'system_source_snapshots', count(*) from system.system_source_snapshots
-- union all select 'system_diff_runs', count(*) from system.system_diff_runs
-- union all select 'system_diff_items', count(*) from system.system_diff_items
-- union all select 'system_review_tasks', count(*) from system.system_review_tasks
-- union all select 'system_review_logs', count(*) from system.system_review_logs
-- union all select 'system_publish_batches', count(*) from system.system_publish_batches
-- union all select 'system_publish_items', count(*) from system.system_publish_items
-- union all select 'system_conflict_queue', count(*) from system.system_conflict_queue
-- order by table_name;
--
-- 4) Stable lineage keys:
-- select sr.source_code, ss.snapshot_version, ss.region_code, ss.checksum
-- from system.system_source_snapshots ss
-- join system.system_source_registry sr on sr.id = ss.source_registry_id
-- order by ss.id;
