-- =============================================================================
-- Local-only: system import boundaries (non-destructive)
-- =============================================================================
--
-- Purpose:
--   Store canonical region boundary geometry for local OSM imports so pipelines
--   can dedupe by stable keys (boundary_ref, checksum, boundary_code +
--   boundary_version) and link snapshots via boundary_id.
--
-- Scope:
--   Local PostgreSQL only. Does not modify Supabase migrations or schemas.
--
-- Safety rules:
--   - Does not DROP tables or truncate data.
--   - Uses CREATE TABLE IF NOT EXISTS; ALTER TABLE ... ADD COLUMN IF NOT EXISTS.
--   - FK from system.system_source_snapshots.boundary_id is nullable for legacy rows.
--
-- Prerequisites:
--   - PostGIS extension (geometry types). Expected on local geo_core baseline.
--
-- =============================================================================

create schema if not exists system;

-- -----------------------------------------------------------------------------
-- New table: system.system_import_boundaries
-- -----------------------------------------------------------------------------

create table if not exists system.system_import_boundaries (
    id bigint generated by default as identity primary key,
    boundary_code text not null,
    boundary_name text not null,
    region_code text not null,
    boundary_ref text not null,
    boundary_version text,
    checksum text,
    source_file_path text,
    geom geometry(MultiPolygon, 4326) not null,
    bbox geometry(Polygon, 4326),
    area_m2 numeric,
    metadata jsonb not null default '{}'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint system_import_boundaries_boundary_code_chk
        check (btrim(boundary_code) <> ''),
    constraint system_import_boundaries_boundary_name_chk
        check (btrim(boundary_name) <> ''),
    constraint system_import_boundaries_region_code_chk
        check (btrim(region_code) <> ''),
    constraint system_import_boundaries_boundary_ref_chk
        check (btrim(boundary_ref) <> ''),
    constraint system_import_boundaries_checksum_chk
        check ((checksum is null) or (btrim(checksum) <> '')),
    constraint system_import_boundaries_area_m2_chk
        check ((area_m2 is null) or (area_m2 >= 0))
);

comment on table system.system_import_boundaries is
    'Registered region boundaries used by local import pipelines (GeoJSON path, checksum dedupe). '
    'Optional FK from system.system_source_snapshots.boundary_id.';

comment on column system.system_import_boundaries.boundary_code is
    'Stable logical boundary identifier (e.g. kyauktan_extract_v2).';

comment on column system.system_import_boundaries.boundary_name is
    'Human-readable label for operators and logs.';

comment on column system.system_import_boundaries.region_code is
    'Stable scope code aligned with snapshots (e.g. MM-KYAUKTAN).';

comment on column system.system_import_boundaries.boundary_ref is
    'Stable reference label for dedupe (often basename or logical ref of source file).';

comment on column system.system_import_boundaries.boundary_version is
    'Optional version segment; uniqueness with boundary_code enforced when non-null.';

comment on column system.system_import_boundaries.checksum is
    'Digest of boundary payload when known; paired with boundary_ref for dedupe when non-null.';

comment on column system.system_import_boundaries.source_file_path is
    'Original path or URI string supplied by the pipeline (not trusted identity alone).';

comment on column system.system_import_boundaries.geom is
    'Boundary footprint in EPSG:4326 as MultiPolygon.';

comment on column system.system_import_boundaries.bbox is
    'Optional envelope polygon in EPSG:4326 for fast bbox queries.';

comment on column system.system_import_boundaries.area_m2 is
    'Optional geodesic or projected area in square meters for QA metrics.';

comment on column system.system_import_boundaries.metadata is
    'Pipeline-specific JSON (CRS notes, importer version, warnings).';

comment on column system.system_import_boundaries.is_active is
    'Soft-disable superseded boundaries without deleting lineage rows.';

-- -----------------------------------------------------------------------------
-- Indexes: lookups + spatial + partial uniques for dedupe
-- -----------------------------------------------------------------------------

create index if not exists system_import_boundaries_boundary_code_idx
    on system.system_import_boundaries (boundary_code);

create index if not exists system_import_boundaries_region_code_idx
    on system.system_import_boundaries (region_code);

create index if not exists system_import_boundaries_boundary_ref_idx
    on system.system_import_boundaries (boundary_ref);

create index if not exists system_import_boundaries_checksum_idx
    on system.system_import_boundaries (checksum);

create index if not exists system_import_boundaries_is_active_idx
    on system.system_import_boundaries (is_active);

create index if not exists system_import_boundaries_geom_gix
    on system.system_import_boundaries using gist (geom);

create index if not exists system_import_boundaries_bbox_gix
    on system.system_import_boundaries using gist (bbox);

-- Partial unique: allows multiple rows with NULL boundary_version outside this constraint.
create unique index if not exists system_import_boundaries_boundary_code_version_uq_idx
    on system.system_import_boundaries (boundary_code, boundary_version)
    where boundary_version is not null;

-- Partial unique: reuse same boundary file/PBF-linked checksum when non-null.
create unique index if not exists system_import_boundaries_boundary_ref_checksum_uq_idx
    on system.system_import_boundaries (boundary_ref, checksum)
    where checksum is not null;

-- -----------------------------------------------------------------------------
-- Link snapshots to optional boundary row
-- -----------------------------------------------------------------------------

alter table system.system_source_snapshots
    add column if not exists boundary_id bigint null;

comment on column system.system_source_snapshots.boundary_id is
    'Optional FK to system.system_import_boundaries for the clip footprint used with this snapshot.';

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'system_source_snapshots_boundary_id_fkey'
          and conrelid = 'system.system_source_snapshots'::regclass
    ) then
        alter table system.system_source_snapshots
            add constraint system_source_snapshots_boundary_id_fkey
            foreign key (boundary_id)
            references system.system_import_boundaries (id)
            on delete restrict;
    end if;
end $$;

create index if not exists system_source_snapshots_boundary_id_idx
    on system.system_source_snapshots (boundary_id);

-- =============================================================================
-- Validation (run manually after applying migration)
-- =============================================================================
--
-- select
--     table_schema,
--     table_name
-- from information_schema.tables
-- where table_schema = 'system'
--   and table_name = 'system_import_boundaries';
--
-- select column_name, data_type, is_nullable
-- from information_schema.columns
-- where table_schema = 'system'
--   and table_name = 'system_import_boundaries'
-- order by ordinal_position;
--
-- select column_name, data_type, is_nullable
-- from information_schema.columns
-- where table_schema = 'system'
--   and table_name = 'system_source_snapshots'
--   and column_name = 'boundary_id';
--
-- select conname, pg_get_constraintdef(oid)
-- from pg_constraint
-- where conrelid = 'system.system_source_snapshots'::regclass
--   and conname = 'system_source_snapshots_boundary_id_fkey';
--
-- select indexname, indexdef
-- from pg_indexes
-- where schemaname = 'system'
--   and tablename = 'system_import_boundaries'
-- order by indexname;
--
