-- =============================================================================
-- Local migration 017: protected-area staging + ref seed (pipeline only)
-- =============================================================================
-- Does NOT write Supabase production.
-- =============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS ref;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS prod_mirror;

CREATE TABLE IF NOT EXISTS ref.ref_protected_area_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name_en text NOT NULL,
  name_mm text NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_public boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_protected_area_classes_code_key UNIQUE (code),
  CONSTRAINT ref_protected_area_classes_code_chk CHECK (btrim(code) <> ''),
  CONSTRAINT ref_protected_area_classes_name_en_chk CHECK (btrim(name_en) <> '')
);

INSERT INTO ref.ref_protected_area_classes AS c (
  code, name_en, name_mm, sort_order, is_public, is_active
)
VALUES
  ('national_park', 'National Park', 'အမျိုးသားဥယျာဉ်', 10, true, true),
  ('nature_reserve', 'Nature Reserve', 'သဘာဝထိန်းသိမ်းရေးနယ်မြေ', 20, true, true),
  ('wildlife_protected_area', 'Wildlife Protected Area', 'တောရိုင်းတိရစ္ဆာန်ကာကွယ်ရေးနယ်မြေ', 30, true, true),
  ('forest_reserve', 'Forest Reserve', 'သစ်တောကြိုးဝိုင်း', 40, true, true),
  ('marine_protected_area', 'Marine Protected Area', 'ပင်လယ်ကာကွယ်ရေးနယ်မြေ', 50, true, true),
  ('other', 'Other Protected Area', 'အခြားကာကွယ်ရေးနယ်မြေ', 90, true, true)
ON CONFLICT (code) DO UPDATE
SET
  name_en = EXCLUDED.name_en,
  name_mm = COALESCE(EXCLUDED.name_mm, c.name_mm),
  sort_order = EXCLUDED.sort_order,
  is_public = EXCLUDED.is_public,
  is_active = true,
  updated_at = now();

CREATE TABLE IF NOT EXISTS staging.staging_protected_area_candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_snapshot_id bigint NOT NULL,
  raw_id bigint NOT NULL,
  external_id text NOT NULL,
  canonical_name text NULL,
  class_code text NOT NULL,
  protected_area_class_id bigint NULL
    REFERENCES ref.ref_protected_area_classes (id),
  normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence_score numeric(6,2) NOT NULL DEFAULT 70,
  match_status text NOT NULL DEFAULT 'new_candidate',
  auto_action text NULL,
  review_status text NOT NULL DEFAULT 'pending',
  review_decision text NULL,
  reviewed_by text NULL,
  reviewed_at timestamptz NULL,
  review_note text NULL,
  normalized_hash text NULL,
  validation_status text NULL,
  validation_notes jsonb NULL,
  source_status text NULL,
  geometry_hash text NULL,
  import_class text NULL,
  import_class_reason jsonb NULL,
  eligible_for_core boolean NULL DEFAULT true,
  core_selection_reason text NULL,
  pmtiles_only_reason text NULL,
  centroid geometry(Point, 4326) NULL,
  area_m2 numeric NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT staging_protected_area_candidates_external_id_chk CHECK (btrim(external_id) <> ''),
  CONSTRAINT staging_protected_area_candidates_class_code_chk CHECK (btrim(class_code) <> ''),
  CONSTRAINT staging_protected_area_candidates_canonical_name_chk
    CHECK (canonical_name IS NULL OR btrim(canonical_name) <> ''),
  CONSTRAINT staging_protected_area_candidates_geom_srid_chk CHECK (ST_SRID(geom) = 4326),
  CONSTRAINT staging_protected_area_candidates_confidence_chk
    CHECK (confidence_score >= 0 AND confidence_score <= 100)
);

CREATE UNIQUE INDEX IF NOT EXISTS staging_protected_area_candidates_snap_ext_uidx
  ON staging.staging_protected_area_candidates (source_snapshot_id, external_id);
CREATE INDEX IF NOT EXISTS staging_protected_area_candidates_source_snapshot_id_idx
  ON staging.staging_protected_area_candidates (source_snapshot_id);
CREATE INDEX IF NOT EXISTS staging_protected_area_candidates_class_code_idx
  ON staging.staging_protected_area_candidates (class_code);
CREATE INDEX IF NOT EXISTS staging_protected_area_candidates_protected_area_class_id_idx
  ON staging.staging_protected_area_candidates (protected_area_class_id);
CREATE INDEX IF NOT EXISTS staging_protected_area_candidates_geom_gix
  ON staging.staging_protected_area_candidates USING GIST (geom);
CREATE INDEX IF NOT EXISTS staging_protected_area_candidates_import_class_idx
  ON staging.staging_protected_area_candidates (source_snapshot_id, import_class);

COMMENT ON TABLE staging.staging_protected_area_candidates IS
  'Local OSM protected-area overlay candidates. Clear safe_* → direct Core; conflicts → import_review.';

-- Slim prod_mirror table for F2 identity match (refresh populates from production).
CREATE TABLE IF NOT EXISTS prod_mirror.core_protected_areas (
  id bigint PRIMARY KEY,
  public_id uuid,
  protected_area_class_id bigint,
  admin_area_id bigint,
  geom geometry(MultiPolygon, 4326),
  centroid geometry(Point, 4326),
  area_m2 numeric,
  external_id text,
  source_registry_id bigint,
  source_snapshot_id bigint,
  source_feature_type text,
  source_feature_id bigint,
  region_code text,
  source_tags jsonb,
  source_refs jsonb,
  normalized_data jsonb,
  confidence_score numeric,
  is_verified boolean,
  verification_status text,
  manual_override boolean,
  is_active boolean,
  deleted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  mirror_content_hash text,
  mirrored_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS prod_mirror_core_protected_areas_external_id_idx
  ON prod_mirror.core_protected_areas (external_id);
CREATE INDEX IF NOT EXISTS prod_mirror_core_protected_areas_source_identity_idx
  ON prod_mirror.core_protected_areas (source_registry_id, source_feature_type, source_feature_id)
  WHERE source_registry_id IS NOT NULL AND source_feature_type IS NOT NULL AND source_feature_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS prod_mirror_core_protected_areas_geom_gix
  ON prod_mirror.core_protected_areas USING GIST (geom);

COMMIT;
