-- =============================================================================
-- Local: OSM category normalize prerequisites (pipeline-only)
-- =============================================================================
-- Seeds ref.ref_land_area_classes + ref.ref_water_classes by CODE (not numeric IDs).
-- Adds staging class FK columns, coastline candidates, unmapped-tag report table.
-- Does NOT write production / Supabase data.
-- =============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS ref;
CREATE SCHEMA IF NOT EXISTS staging;

-- ---------------------------------------------------------------------------
-- ref.ref_land_area_classes (local seed; mirrors 031 + 155 codes)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref.ref_land_area_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name_en text NOT NULL,
  name_mm text NULL,
  parent_id bigint NULL REFERENCES ref.ref_land_area_classes (id),
  sort_order integer NOT NULL DEFAULT 100,
  min_zoom numeric NOT NULL DEFAULT 12,
  default_import_confidence numeric NOT NULL DEFAULT 70,
  is_public boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_land_area_classes_code_key UNIQUE (code),
  CONSTRAINT ref_land_area_classes_code_format_chk
    CHECK (btrim(code) <> '' AND code ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'),
  CONSTRAINT ref_land_area_classes_min_zoom_chk
    CHECK (min_zoom >= 0 AND min_zoom <= 24),
  CONSTRAINT ref_land_area_classes_default_import_confidence_chk
    CHECK (default_import_confidence >= 0 AND default_import_confidence <= 100)
);

CREATE INDEX IF NOT EXISTS ref_land_area_classes_code_idx
  ON ref.ref_land_area_classes (code);
CREATE INDEX IF NOT EXISTS ref_land_area_classes_parent_id_idx
  ON ref.ref_land_area_classes (parent_id);
CREATE INDEX IF NOT EXISTS ref_land_area_classes_is_active_idx
  ON ref.ref_land_area_classes (is_active);

-- Roots / mid parents
INSERT INTO ref.ref_land_area_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom,
  default_import_confidence, is_public, is_active
)
VALUES
  ('landuse', 'Land use', 'မြေအသုံးချမှု', NULL, 10, 10, 70, true, true),
  ('landcover', 'Land cover', 'မြေဖုံးအုပ်မှု', NULL, 20, 10, 70, true, true),
  ('wetland', 'Wetland', 'စိုစွတ်မြေ', NULL, 30, 11, 70, true, true),
  ('urban', 'Urban', 'မြို့ပြဧရိယာ', NULL, 11, 11, 70, true, true),
  ('agriculture', 'Agriculture & village', 'ကျေးလက်နှင့် စိုက်ပျိုးရေး', NULL, 12, 11, 75, true, true),
  ('institution', 'Institution & public', 'ပြည်သူ့အဆောက်အအုံ', NULL, 13, 12, 70, true, true),
  ('green', 'Green & recreation', 'သစ်တော / အပန်းဖြေ', NULL, 14, 11, 70, true, true),
  ('transport', 'Transport area', 'သယ်ယူပို့ဆောင်ရေးဧရိယာ', NULL, 15, 12, 75, true, true),
  ('special', 'Special', 'အထူး', NULL, 16, 12, 50, true, true)
ON CONFLICT (code) DO UPDATE
SET name_en = EXCLUDED.name_en,
    name_mm = COALESCE(c.name_mm, EXCLUDED.name_mm),
    is_active = true,
    updated_at = now();

-- Attach mid groups under landuse root when present
UPDATE ref.ref_land_area_classes AS child
SET parent_id = root.id, updated_at = now()
FROM ref.ref_land_area_classes AS root
WHERE root.code = 'landuse'
  AND child.code IN ('urban', 'agriculture', 'institution', 'green', 'transport', 'special')
  AND child.parent_id IS DISTINCT FROM root.id;

INSERT INTO ref.ref_land_area_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom,
  default_import_confidence, is_public, is_active
)
SELECT v.code, v.name_en, v.name_mm, p.id, v.sort_order, v.min_zoom,
       v.conf, v.is_public, true
FROM (VALUES
  ('urban', 'residential', 'Residential', 'လူနေရပ်ကွက်', 0, 12::numeric, 75::numeric, true),
  ('urban', 'commercial', 'Commercial', 'စီးပွားရေးဧရိယာ', 1, 12, 75, true),
  ('urban', 'retail', 'Retail', 'အရောင်းအဝယ်ဧရိယာ', 2, 13, 75, true),
  ('urban', 'industrial', 'Industrial', 'စက်မှုဧရိယာ', 3, 12, 75, true),
  ('urban', 'government', 'Government', 'အစိုးရဧရိယာ', 4, 13, 75, true),
  ('urban', 'construction', 'Construction', 'ဆောက်လုပ်ရေးမြေ', 5, 14, 75, true),
  ('agriculture', 'farmland', 'Farmland', 'စိုက်ပျိုးမြေ', 0, 12, 75, true),
  ('agriculture', 'paddy', 'Rice paddy', 'စပါးလယ်', 1, 12, 75, true),
  ('agriculture', 'orchard', 'Orchard', 'ဥယျာဉ်ခြံမြေ', 2, 13, 75, true),
  ('agriculture', 'aquaculture', 'Aquaculture', 'ငါး/ပုစွန်မွေးမြူရေးကန်', 3, 13, 70, true),
  ('agriculture', 'farmyard', 'Farmyard', 'လယ်ယာဝင်း', 4, 13, 75, true),
  ('institution', 'education', 'Education compound', 'ပညာရေးဝင်း', 0, 14, 70, true),
  ('institution', 'healthcare', 'Healthcare compound', 'ကျန်းမာရေးဝင်း', 1, 14, 70, true),
  ('institution', 'religious', 'Religious compound', 'ဘာသာရေးဝင်း', 2, 14, 70, true),
  ('institution', 'cemetery', 'Cemetery', 'သင်္ချိုင်း', 3, 14, 70, true),
  ('green', 'park', 'Park', 'ပန်းခြံ', 0, 13, 70, true),
  ('green', 'recreation_ground', 'Recreation ground', 'အားကစား/အပန်းဖြေမြေ', 1, 13, 70, true),
  ('special', 'military', 'Military', 'စစ်ဘက်ဧရိယာ', 0, 13, 65, false),
  ('special', 'vacant', 'Vacant', 'မြေလွတ်', 1, 14, 50, true),
  ('special', 'quarry', 'Quarry', NULL::text, 2, 13, 65, true),
  ('special', 'landfill', 'Landfill', NULL, 3, 13, 60, true),
  ('special', 'other', 'Other', 'အခြား', 4, 12, 50, true)
) AS v(parent_code, code, name_en, name_mm, sort_order, min_zoom, conf, is_public)
JOIN ref.ref_land_area_classes p ON p.code = v.parent_code
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name_en = EXCLUDED.name_en,
    name_mm = COALESCE(c.name_mm, EXCLUDED.name_mm),
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

INSERT INTO ref.ref_land_area_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom,
  default_import_confidence, is_public, is_active
)
SELECT v.code, v.name_en, v.name_mm, p.id, v.sort_order, v.min_zoom, v.conf, true, true
FROM (VALUES
  ('forest', 'Forest', 'သစ်တော', 0, 11::numeric, 75::numeric),
  ('grassland', 'Grassland', 'မြက်ခင်းပြင်', 1, 12, 75),
  ('scrub', 'Scrub', NULL::text, 2, 12, 70),
  ('heath', 'Heath', NULL, 3, 12, 70),
  ('sand', 'Sand', NULL, 4, 12, 70),
  ('beach', 'Beach', NULL, 5, 13, 70),
  ('bare_rock', 'Bare rock', NULL, 6, 13, 70),
  ('mud', 'Mud', NULL, 7, 13, 70)
) AS v(code, name_en, name_mm, sort_order, min_zoom, conf)
JOIN ref.ref_land_area_classes p ON p.code = 'landcover'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name_en = EXCLUDED.name_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

INSERT INTO ref.ref_land_area_classes AS c (
  code, name_en, name_mm, parent_id, sort_order, min_zoom,
  default_import_confidence, is_public, is_active
)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, v.conf, true, true
FROM (VALUES
  ('marsh', 'Marsh', 0, 13::numeric, 70::numeric),
  ('swamp', 'Swamp', 1, 13, 70),
  ('mangrove', 'Mangrove', 2, 12, 75),
  ('reedbed', 'Reedbed', 3, 13, 70),
  ('wet_meadow', 'Wet meadow', 4, 13, 70),
  ('saltmarsh', 'Salt marsh', 5, 13, 70),
  ('tidalflat', 'Tidal flat', 6, 13, 70),
  ('bog', 'Bog', 7, 13, 65),
  ('fen', 'Fen', 8, 13, 65)
) AS v(code, name_en, sort_order, min_zoom, conf)
JOIN ref.ref_land_area_classes p ON p.code = 'wetland'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name_en = EXCLUDED.name_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

-- ---------------------------------------------------------------------------
-- ref.ref_water_classes (local seed; mirrors 156)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref.ref_water_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name_en text NOT NULL,
  name_mm text NULL,
  parent_id bigint NULL REFERENCES ref.ref_water_classes (id),
  sort_order integer NOT NULL DEFAULT 100,
  min_zoom numeric NOT NULL DEFAULT 12,
  is_public boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_water_classes_code_key UNIQUE (code),
  CONSTRAINT ref_water_classes_code_format_chk
    CHECK (btrim(code) <> '' AND code ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'),
  CONSTRAINT ref_water_classes_min_zoom_chk
    CHECK (min_zoom >= 0 AND min_zoom <= 24)
);

CREATE INDEX IF NOT EXISTS ref_water_classes_code_idx ON ref.ref_water_classes (code);
CREATE INDEX IF NOT EXISTS ref_water_classes_parent_id_idx ON ref.ref_water_classes (parent_id);
CREATE INDEX IF NOT EXISTS ref_water_classes_is_active_idx ON ref.ref_water_classes (is_active);

INSERT INTO ref.ref_water_classes AS c (code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active)
VALUES
  ('flowing_water', 'Flowing water', NULL, NULL, 10, 8, true, true),
  ('standing_water', 'Standing water', NULL, NULL, 20, 8, true, true),
  ('water_structure', 'Water structure', NULL, NULL, 30, 12, true, true),
  ('other', 'Other water', NULL, NULL, 90, 12, true, true)
ON CONFLICT (code) DO UPDATE
SET name_en = EXCLUDED.name_en, parent_id = NULL, is_active = true, updated_at = now();

INSERT INTO ref.ref_water_classes AS c (code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, true, true
FROM (VALUES
  ('river', 'River', 0, 8::numeric),
  ('stream', 'Stream', 1, 11),
  ('canal', 'Canal', 2, 11),
  ('tidal_channel', 'Tidal channel', 3, 12),
  ('ditch', 'Ditch', 4, 13),
  ('drain', 'Drain', 5, 13)
) AS v(code, name_en, sort_order, min_zoom)
JOIN ref.ref_water_classes p ON p.code = 'flowing_water'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id, name_en = EXCLUDED.name_en, sort_order = EXCLUDED.sort_order,
    is_active = true, updated_at = now();

INSERT INTO ref.ref_water_classes AS c (code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, true, true
FROM (VALUES
  ('water', 'Water body', 0, 8::numeric),
  ('lake', 'Lake', 1, 9),
  ('reservoir', 'Reservoir', 2, 10),
  ('pond', 'Pond', 3, 13),
  ('basin', 'Basin', 4, 13),
  ('lagoon', 'Lagoon', 5, 12),
  ('oxbow', 'Oxbow', 6, 12),
  ('fishpond', 'Fishpond', 7, 13),
  ('moat', 'Moat', 8, 13),
  ('stream_pool', 'Stream pool', 9, 14),
  ('wastewater', 'Wastewater', 10, 14)
) AS v(code, name_en, sort_order, min_zoom)
JOIN ref.ref_water_classes p ON p.code = 'standing_water'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id, name_en = EXCLUDED.name_en, sort_order = EXCLUDED.sort_order,
    is_active = true, updated_at = now();

INSERT INTO ref.ref_water_classes AS c (code, name_en, name_mm, parent_id, sort_order, min_zoom, is_public, is_active)
SELECT v.code, v.name_en, NULL, p.id, v.sort_order, v.min_zoom, true, true
FROM (VALUES
  ('dam', 'Dam', 0, 12::numeric),
  ('weir', 'Weir', 1, 13),
  ('lock', 'Lock', 2, 13),
  ('lock_gate', 'Lock gate', 3, 14),
  ('sluice_gate', 'Sluice gate', 4, 14),
  ('waterfall', 'Waterfall', 5, 13),
  ('dock', 'Dock', 6, 13),
  ('boatyard', 'Boatyard', 7, 14)
) AS v(code, name_en, sort_order, min_zoom)
JOIN ref.ref_water_classes p ON p.code = 'water_structure'
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id, name_en = EXCLUDED.name_en, sort_order = EXCLUDED.sort_order,
    is_active = true, updated_at = now();

-- ---------------------------------------------------------------------------
-- Staging FK columns
-- ---------------------------------------------------------------------------
ALTER TABLE IF EXISTS staging.staging_landuse_candidates
  ADD COLUMN IF NOT EXISTS land_area_class_id bigint;

ALTER TABLE IF EXISTS staging.staging_water_line_candidates
  ADD COLUMN IF NOT EXISTS water_class_id bigint;

ALTER TABLE IF EXISTS staging.staging_water_polygon_candidates
  ADD COLUMN IF NOT EXISTS water_class_id bigint;

DO $$
BEGIN
  IF to_regclass('staging.staging_landuse_candidates') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'staging_landuse_candidates_land_area_class_id_fkey'
         AND conrelid = 'staging.staging_landuse_candidates'::regclass
     ) THEN
    ALTER TABLE staging.staging_landuse_candidates
      ADD CONSTRAINT staging_landuse_candidates_land_area_class_id_fkey
        FOREIGN KEY (land_area_class_id) REFERENCES ref.ref_land_area_classes (id) NOT VALID;
  END IF;

  IF to_regclass('staging.staging_water_line_candidates') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'staging_water_line_candidates_water_class_id_fkey'
         AND conrelid = 'staging.staging_water_line_candidates'::regclass
     ) THEN
    ALTER TABLE staging.staging_water_line_candidates
      ADD CONSTRAINT staging_water_line_candidates_water_class_id_fkey
        FOREIGN KEY (water_class_id) REFERENCES ref.ref_water_classes (id) NOT VALID;
  END IF;

  IF to_regclass('staging.staging_water_polygon_candidates') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conname = 'staging_water_polygon_candidates_water_class_id_fkey'
         AND conrelid = 'staging.staging_water_polygon_candidates'::regclass
     ) THEN
    ALTER TABLE staging.staging_water_polygon_candidates
      ADD CONSTRAINT staging_water_polygon_candidates_water_class_id_fkey
        FOREIGN KEY (water_class_id) REFERENCES ref.ref_water_classes (id) NOT VALID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS staging_landuse_candidates_land_area_class_id_idx
  ON staging.staging_landuse_candidates (land_area_class_id);
CREATE INDEX IF NOT EXISTS staging_water_line_candidates_water_class_id_idx
  ON staging.staging_water_line_candidates (water_class_id);
CREATE INDEX IF NOT EXISTS staging_water_polygon_candidates_water_class_id_idx
  ON staging.staging_water_polygon_candidates (water_class_id);

-- ---------------------------------------------------------------------------
-- Coastline staging (local pipeline; not import_review in this step)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staging.staging_coastline_candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_snapshot_id bigint NOT NULL,
  raw_id bigint NOT NULL,
  external_id text NOT NULL,
  canonical_name text NULL,
  class_code text NOT NULL DEFAULT 'coastline',
  normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence_score numeric NOT NULL DEFAULT 70,
  match_status text NOT NULL DEFAULT 'new_candidate',
  auto_action text NULL,
  review_status text NOT NULL DEFAULT 'pending',
  geom geometry(Geometry, 4326) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT staging_coastline_candidates_external_id_chk CHECK (btrim(external_id) <> ''),
  CONSTRAINT staging_coastline_candidates_class_code_chk CHECK (btrim(class_code) <> ''),
  CONSTRAINT staging_coastline_candidates_geom_srid_chk CHECK (ST_SRID(geom) = 4326)
);

CREATE UNIQUE INDEX IF NOT EXISTS staging_coastline_candidates_snap_ext_uidx
  ON staging.staging_coastline_candidates (source_snapshot_id, external_id);
CREATE INDEX IF NOT EXISTS staging_coastline_candidates_source_snapshot_id_idx
  ON staging.staging_coastline_candidates (source_snapshot_id);
CREATE INDEX IF NOT EXISTS staging_coastline_candidates_geom_gix
  ON staging.staging_coastline_candidates USING GIST (geom);

-- ---------------------------------------------------------------------------
-- Unmapped OSM tag report (coverage; not a Core category dump table)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staging.staging_osm_unmapped_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_snapshot_id bigint NOT NULL,
  entity_family text NOT NULL,
  osm_feature_type text NULL,
  osm_id bigint NULL,
  external_id text NULL,
  tag_key text NOT NULL,
  tag_value text NULL,
  reason text NOT NULL,
  tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT staging_osm_unmapped_tags_reason_chk CHECK (btrim(reason) <> ''),
  CONSTRAINT staging_osm_unmapped_tags_entity_family_chk CHECK (btrim(entity_family) <> '')
);

CREATE INDEX IF NOT EXISTS staging_osm_unmapped_tags_snapshot_idx
  ON staging.staging_osm_unmapped_tags (source_snapshot_id);
CREATE INDEX IF NOT EXISTS staging_osm_unmapped_tags_family_reason_idx
  ON staging.staging_osm_unmapped_tags (source_snapshot_id, entity_family, reason);
CREATE INDEX IF NOT EXISTS staging_osm_unmapped_tags_kv_idx
  ON staging.staging_osm_unmapped_tags (source_snapshot_id, tag_key, tag_value);

COMMENT ON TABLE staging.staging_osm_unmapped_tags IS
  'Pipeline coverage report for unrecognized OSM tags. Not a Core category registry.';

COMMIT;
