-- =============================================================================
-- Local migration 021: settlement staging + slim prod_mirror target (pipeline only)
-- =============================================================================
-- Canonical types match infrastructure/database/migrations/supabase/192_core_settlements.sql:
--   city | town | village | local_area
-- Does NOT write Supabase production. Does NOT populate footprint_geom from OSM.
-- =============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS prod_mirror;

CREATE TABLE IF NOT EXISTS staging.staging_settlement_candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_snapshot_id bigint NOT NULL,
  raw_id bigint NULL,
  source_entity_type text NOT NULL,
  external_id text NOT NULL,
  canonical_name text NULL,
  class_code text NOT NULL,
  source_place_type text NULL,
  name_mm text NULL,
  name_en text NULL,
  population integer NULL,
  point_geom geometry(Point, 4326) NULL,
  confidence_score numeric(6,2) NOT NULL DEFAULT 65,
  match_status text NOT NULL DEFAULT 'new_candidate',
  auto_action text NULL,
  review_status text NOT NULL DEFAULT 'pending',
  import_class text NULL,
  import_class_reason jsonb NULL,
  source_status text NULL,
  validation_status text NULL,
  validation_notes jsonb NULL,
  normalized_hash text NULL,
  normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT staging_settlement_candidates_external_id_chk CHECK (btrim(external_id) <> ''),
  CONSTRAINT staging_settlement_candidates_class_code_chk
    CHECK (class_code = ANY (ARRAY['city', 'town', 'village', 'local_area']::text[])),
  CONSTRAINT staging_settlement_candidates_canonical_name_chk
    CHECK (canonical_name IS NULL OR btrim(canonical_name) <> ''),
  CONSTRAINT staging_settlement_candidates_point_geom_srid_chk
    CHECK (point_geom IS NULL OR ST_SRID(point_geom) = 4326),
  CONSTRAINT staging_settlement_candidates_confidence_chk
    CHECK (confidence_score >= 0 AND confidence_score <= 100),
  CONSTRAINT staging_settlement_candidates_population_chk
    CHECK (population IS NULL OR population >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS staging_settlement_candidates_snap_ext_uidx
  ON staging.staging_settlement_candidates (source_snapshot_id, external_id);
CREATE INDEX IF NOT EXISTS staging_settlement_candidates_source_snapshot_id_idx
  ON staging.staging_settlement_candidates (source_snapshot_id);
CREATE INDEX IF NOT EXISTS staging_settlement_candidates_class_code_idx
  ON staging.staging_settlement_candidates (class_code);
CREATE INDEX IF NOT EXISTS staging_settlement_candidates_point_geom_gix
  ON staging.staging_settlement_candidates USING GIST (point_geom)
  WHERE point_geom IS NOT NULL;
CREATE INDEX IF NOT EXISTS staging_settlement_candidates_import_class_idx
  ON staging.staging_settlement_candidates (source_snapshot_id, import_class);

COMMENT ON TABLE staging.staging_settlement_candidates IS
  'OSM settlement candidates (place=city/town/village/hamlet/quarter/suburb/neighbourhood/locality). Canonical types only. V1 point_geom; no OSM footprint.';

-- Slim local F2 target. Empty until 192 exists in production and prod_mirror is refreshed.
CREATE TABLE IF NOT EXISTS prod_mirror.core_settlements (
  id bigint PRIMARY KEY,
  public_id uuid,
  settlement_type_id bigint,
  canonical_name text,
  name_mm text,
  name_en text,
  point_geom geometry(Point, 4326),
  footprint_geom geometry(MultiPolygon, 4326),
  township_id bigint,
  population integer,
  importance_score numeric,
  external_id text,
  source_type_id bigint,
  source_refs jsonb,
  is_public boolean,
  is_verified boolean,
  verification_status text,
  verified_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  deleted_at timestamptz,
  mirrored_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS prod_mirror_core_settlements_external_id_idx
  ON prod_mirror.core_settlements (external_id)
  WHERE external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS prod_mirror_core_settlements_point_geom_gix
  ON prod_mirror.core_settlements USING GIST (point_geom)
  WHERE point_geom IS NOT NULL;

COMMIT;
